### ISSUE TITLE
Error when running NanoPlot

### ISSUE THREAD

**Issue by icymiktreize** [wdecoster/NanoPlot#10]
Hi there,

I used your tool to generate some statistics plot for my data and got this error:

Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 9, in <module>
    load_entry_point('NanoPlot==0.12.8', 'console_scripts', 'NanoPlot')()
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 47, in main
    datadf, lengthprefix, logBool, readlengthsPointer, stamp = getInput(stamp, args)
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 132, in getInput
    getStats(datadf, args.outdir)
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 190, in getStats
    statdict = nanomath.readstats(np.array(datadf["lengths"]), np.array(datadf["quals"]))
TypeError: readstats() takes exactly 1 argument (2 given)

This is the command line I used:  
NanoPlot --fastq "/2D/HLA_Nov_merged.fastq" -o "/Stats/NanoPlot/" -p all. 

It is quite interesting that I used NanoPlot a month ago and it worked very well. Now, I am trying to recall what I have done and redoing everything. The FASTQ file and the NanoPlot version are the same but it did not work this time. I would appreciate if you can help me to figure out the reason.

Best wishes

KT

**Comment by Dramenia** [comment]
why did you ad the " to the command? when i use it, i use it without the ", and it seems to work fine.
Did you use the same fastq as previously used?

**Comment by icymiktreize** [comment]
I am just too lazy to type the directory of the file, so simply right-click to copy it into the envirornment. I think the " is not the problem as it is fine with other scripts. 
Yes, the fastq file is the same. I can send it to you if you want.

**Comment by Dramenia** [comment]
yes please. just to check if anything is wrong with the file or the input method. my mail is info@removethisdramenia.nl

**Comment by icymiktreize** [comment]
I emailed to the above address but it is said the domain  removethisdramenia.nl  could not be found. Can you check your email again, please? Thanks a lot for your support.

**Comment by wdecoster** [comment]
Hi icymiktreize,

Thanks for reporting this and my apologies for the late reply, I'm just back from my holidays.
This looks a lot like you have one outdated submodule installed together with a more recent NanoPlot version. I expect installing the latest versions using `pip install NanoPlot --upgrade` would solve this. I'll look into more detail in this in a couple of hours.

It would be helpful if you could include the log file when you report an issue, this gives me a better idea of what's going on and which versions were used.

Cheers,
Wouter

**Comment by wdecoster** [comment]
More precisely, the nanomath module appears to be up to date, but NanoPlot itself isn't. Note that the latest version on Pypi is 0.16.4, and you are using 0.12.8.

**Comment by icymiktreize** [comment]
Hi,
You're right that I have an older version of Nanoplot. I have removed the old one and updated as your suggestion. It works perfectly now. Thanks a lot for your support.
Cheers
KT

**Comment by wdecoster** [comment]
Hi,

Good to hear! If encounter more issues or have suggestions/feature request I would be happy to take a look at them.

Cheers,
Wouter
