### ISSUE TITLE
'Weighted' histograms - what are they weighted by?

### ISSUE THREAD

**Issue by ggstatgen** [wdecoster/NanoPlot#111]
Hi guys

Sorry not an issue, rather a request for clarification. I was not able to find the meaning of the 'weighted' histograms in NanoPlot (both linear and log scaled). What are they weighted by? Thanks and keep up the good work!

**Comment by wdecoster** [comment]
They're weighted by the number of nucleotides per bin. As such longer reads count 'heavier'. The height of the bar, therefore, does not represent the number of reads, but the number of nucleotides in that bin. That's the same as the MinKNOW visualization you get during the run.

Does that help?

**Comment by ggstatgen** [comment]
Perfect thanks!

**Comment by peflanag** [comment]
Can I ask a stupid question, what do you mean by "bin" when you say they are weighted by number of nucleotides per bin?

**Comment by peflanag** [comment]
Cheers, it does!

**Comment by zhenLiuExplr** [comment]
Hi. I have a question about the weighted histograms. I think each bin in the weighted histogram is equal to sum(number_of_reads*reads_length), which should more than the bin in the unweighted histogram. But I got a weighted histogram lower than the unweighted one on the y-axis. Is there something wrong?
![图片](https://user-images.githubusercontent.com/47103400/60413930-26bbee80-9c09-11e9-8f04-83289cb8e199.png)
![图片](https://user-images.githubusercontent.com/47103400/60413936-35a2a100-9c09-11e9-8641-0c24dcbb13eb.png)
![图片](https://user-images.githubusercontent.com/47103400/60413941-3b988200-9c09-11e9-8ccb-0a0b13e29345.png)
![图片](https://user-images.githubusercontent.com/47103400/60413947-3fc49f80-9c09-11e9-8c17-443fe7d5552f.png)

**Comment by wdecoster** [comment]
I thought I knew, and now I'm as confused as you are. I'll get back to you if I have figured it out.

**Comment by wdecoster** [comment]
I believe this might be related to an issue I just opened on the numpy repository: https://github.com/numpy/numpy/issues/13879  
I will see what they say there, and make the required changes to NanoPlot.

**Comment by zhenLiuExplr** [comment]
Thanks ;) I will follow with the issue

**Comment by wdecoster** [comment]
I'll fix this in NanoPlot by upcasting the array to an uint64 before making these histograms. I think you only got these wrong weighted histograms if all your reads are shorter than 65535 bp as the column in the dataframe is then downcasting to an uint16 (to save memory). Anyway, I have made a new version available through pip (v1.26.1), can you check if things are fixed?

**Comment by zhenLiuExplr** [comment]
I update to NanoPlot 1.26.1 and it works fine. Thanks ;)
