### ISSUE TITLE
Control extent of y/quality axis on length-vs-quality plots

### ISSUE THREAD

**Issue by standage** [wdecoster/NanoPlot#113]
First, I want to say thanks for sharing this awesome library!

For the read length vs read quality plots, it looks like you can control the X axis with the `--minlength`, `--maxlength`, and `--loglength` settings. Is there any way to do the same with the Y axis? I see the `--minqual` setting, but that's actually not what I'm worried about. It looks like there are very few reads with average quality above 10, yet the Y axis extends all the way to 70.

![lengthvsqualityscatterplot_kde](https://user-images.githubusercontent.com/566823/50402685-54117680-0766-11e9-9daf-f6f478eeeb2a.png)

I'm re-running NanoPlot now with `--maxlength 20000 --loglength`, which should improve the X axis a lot. What can I do to improve the Y axis?

**Comment by standage** [comment]
Curious. My latest run with `--maxlength 20000 --loglength` produced a plot with the Y axis truncated at 12, which makes a much nicer plot. Was this a result of using the `--loglength` setting? In any case, it might make sense to truncate the Y axis whether the X axis is plotted in log scale or not.

**Comment by standage** [comment]
It looks like the `--minlength 100` setting is the culprit. There are a non-trivial number of reads around 10bp in length, and at least 1 of these must have a high average quality, which throws the whole plot off.

**Comment by wdecoster** [comment]
This issue should be fixed in version 1.20 (available on PyPI). Now reads are automatically removed if they have both a short length (< 20) and a high quality (> 30).
