### ISSUE TITLE
Conda install throws warning

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [wdecoster/NanoPlot#114]
Hi there.
NanoPlot throws a RuntimeWarning when install with conda. 

*/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

Might be related to https://github.com/ContinuumIO/anaconda-issues/issues/6678.

**Comment by wdecoster** [comment]
As far as I understand it is an incompatibility between the numpy version against which pandas was built and the one installed on the user system.
