### ISSUE TITLE
NanoPlot Error: libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by lianggong24** [wdecoster/NanoPlot#115]
When I launch NanoPlot, here is the error:
ImportError: /home/usr/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/usr/anaconda3/lib/python3.6/site-packages/pandas/_libs/window.cpython-36m-x86_64-linux-gnu.so)

**Comment by wdecoster** [comment]
How did you install NanoPlot? Are you using an old operating system/compiler?

**Comment by lianggong24** [comment]
Hi, thanks for your reply. I always install NanoPlot through conda install. There is no problem when I installed and used NanoPlot v1.18.2. Here is my info: 
conda version : 4.5.12
conda-build version : 3.17.6
python version : 3.6.6.final.0
user-agent : conda/4.5.12 requests/2.21.0 CPython/3.6.6 Linux/2.6.32-754.3.5.el6.x86_64 centos/6.5 glibc/2.12

**Comment by wdecoster** [comment]
I think this is more an issue from pandas, a module used by NanoPlot. I'll see if I can find a way to help.

**Comment by wdecoster** [comment]
To confirm my hypothesis, can you check if the error is reproduced by `python -c "import pandas"`?

**Comment by lianggong24** [comment]
I didn't figure it out. But it works now after several rounds of install and uninstall of NanoPlot, and "conda update --all". Thanks.
