### ISSUE TITLE
Unable to install with conda

### ISSUE THREAD

**Issue by stopalopa** [wdecoster/NanoPlot#116]
After installing NanoPlot with Conda, I kept getting a NanoPlot: command not found error when I ran the following command: NanoPlot --cram combined_2018-08-10.hg38.sorted.cram --loglength -o summaryplots. I am using conda 4.3.34 on Debian GNU/Linux 8 (jessie).  I was able to install NanoPlot using pip.

**Comment by wdecoster** [comment]
That error message means your operating system cannot find the NanoPlot program. Probably the directory which is used by conda (on my system `~/anaconda3/bin/`) is not in the $PATH environmental variable. See e.g. [this SO question](https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix).

**Comment by Annie-msi** [comment]
I am trying to install Nanoplot with conda, 
Command: conda install -c bioconda nanoplot
Getting following error
Process killed for exceeding 15 minutes of user CPU time on a login node.
