### ISSUE TITLE
non-tuple sequence issue?

### ISSUE THREAD

**Issue by cliu32** [wdecoster/NanoPlot#118]
I ran this code "NanoPlot -t 2 --fastq reads.fastq" and got the following message, which I don't understand. Thanks for your help!
.../anaconda2/envs/nanoplot/lib/python3.5/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval

**Comment by wdecoster** [comment]
Seems like a mostly harmless warning to me. I also think it is not something I have to (or can) adjust, but rather a dependency of NanoPlot (seaborn/matplotlib/plotly?) that uses code which is going to get deprecated eventually - let's hope the maintainers fix it.

**Comment by cliu32** [comment]
Ok, sounds good. Thank you!
