### ISSUE TITLE
ImportError: cannot import name 'margin_plot'

### ISSUE THREAD

**Issue by Adelaam** [wdecoster/NanoPlot#121]
Traceback (most recent call last):
  File "/home/markwilks/anaconda3/bin/NanoPlot", line 6, in <module>
    from nanoplot.NanoPlot import main
  File "/home/markwilks/anaconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 25, in <module>
    import nanoplotter
  File "/home/markwilks/anaconda3/lib/python3.6/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter import *
  File "/home/markwilks/anaconda3/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 42, in <module>
    from pauvre.marginplot import margin_plot
ImportError: cannot import name 'margin_plot'
I have been running NanoPlot for a while with no problems. But Today I have found this error.
Thank you!

**Comment by wdecoster** [comment]
Have you installed NanoPlot using conda or pip? Can you please show me the output of the following command?

`~/anaconda3/bin/python -c "import pauvre ; print(pauvre.__version__)"`

**Comment by Adelaam** [comment]
I used pip


~/anaconda3/bin/python -c "import pauvre ; print(pauvre.__version__)"
0.1.3

**Comment by wdecoster** [comment]
Well, updating pauvre might work, but could you first try updating NanoPlot itself? That should correct the version of pauvre as well...

**Comment by Adelaam** [comment]
I have got Nanoplot version : NanoPlot                           1.20.1

**Comment by wdecoster** [comment]
Please try `pip install pauvre==0.1.86` and see if that helps.

**Comment by Adelaam** [comment]
pip install pauvre==0.1.86
Requirement already satisfied: pauvre==0.1.86 in ./anaconda3/lib/python3.6/site-packages (0.1.86)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (0.18.1)
Requirement already satisfied: pandas>=0.20.1 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (0.23.4)
Collecting numpy>=1.12.1 (from pauvre==0.1.86)
  Downloading https://files.pythonhosted.org/packages/f5/bf/4981bcbee43934f0adb8f764a1e70ab0ee5a448f6505bd04a87a2fda2a8b/numpy-1.16.1-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 3.1MB/s 
Requirement already satisfied: biopython>=1.68 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (1.72)
Requirement already satisfied: matplotlib>=2.0.2 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (3.0.2)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.20.1->pauvre==0.1.86) (2.6.0)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.20.1->pauvre==0.1.86) (2016.10)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.2->pauvre==0.1.86) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.2->pauvre==0.1.86) (2.1.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.2->pauvre==0.1.86) (1.0.1)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.20.1->pauvre==0.1.86) (1.10.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.2->pauvre==0.1.86) (40.8.0)
Installing collected packages: numpy
  Found existing installation: numpy 1.11.3
    Uninstalling numpy-1.11.3:
      Successfully uninstalled numpy-1.11.3
Successfully installed numpy-1.16.1
But then again the same error:
Traceback (most recent call last):
  File "/home/markwilks/anaconda3/bin/NanoPlot", line 6, in <module>
    from nanoplot.NanoPlot import main
  File "/home/markwilks/anaconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 25, in <module>
    import nanoplotter
  File "/home/markwilks/anaconda3/lib/python3.6/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter_main import *
  File "/home/markwilks/anaconda3/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 38, in <module>
    from pauvre.marginplot import margin_plot
ImportError: cannot import name 'margin_plot'

**Comment by wdecoster** [comment]
Do you have multiple python installations?
What do you get with `which python`?
And what with `python -c "import pauvre ; print(pauvre.__version__)"`?

**Comment by Adelaam** [comment]
Yes, I think so.
 which python
/home/markwilks/anaconda3/bin/python

python -c "import pauvre ; print(pauvre.__version__)"
0.1.3

**Comment by Adelaam** [comment]
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux

Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2

**Comment by wdecoster** [comment]
Please try `python -m "pip install pauvre==0.1.86"`

**Comment by Adelaam** [comment]
python -m "pip install pauvre==0.1.86"
/home/markwilks/anaconda3/bin/python: Error while finding module specification for 'pip install pauvre==0.1.86' (ModuleNotFoundError: No module named 'pip install pauvre==0')

**Comment by wdecoster** [comment]
Woops, that should have been without quotes:

`python -m pip install pauvre==0.1.86`

**Comment by Adelaam** [comment]
python -m pip install pauvre==0.1.86
Requirement already satisfied: pauvre==0.1.86 in ./anaconda3/lib/python3.6/site-packages (0.1.86)
Requirement already satisfied: pandas>=0.20.1 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (0.23.4)
Requirement already satisfied: matplotlib>=2.0.2 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (3.0.2)
Requirement already satisfied: biopython>=1.68 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (1.72)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (0.18.1)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda3/lib/python3.6/site-packages (from pauvre==0.1.86) (1.16.1)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.20.1->pauvre==0.1.86) (2.6.0)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.20.1->pauvre==0.1.86) (2016.10)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.2->pauvre==0.1.86) (2.1.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.2->pauvre==0.1.86) (1.0.1)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib>=2.0.2->pauvre==0.1.86) (0.10.0)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas>=0.20.1->pauvre==0.1.86) (1.10.0)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.0.2->pauvre==0.1.86) (40.8.0)

**Comment by wdecoster** [comment]
Is your default python a python3?

`python --version`?

If so, can you open a python terminal (using `python`) and try the following and let me know if that works, and return the output:

`import pauvre.marginplot`
and
`dir(pauvre.marginplot)`

**Comment by wdecoster** [comment]
And if all of that goes well, could you try in your python terminal:

`pauvre.__file__` and `pauvre.marginplot.__file__`

**Comment by Adelaam** [comment]
python
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pauvre.marginplot
>>> dir(pauvre.marginplot)
['LinearSegmentedColormap', 'SeqIO', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'logger', 'logging', 'marginplot', 'matplotlib', 'mplpatches', 'np', 'opath', 'parse_fastq_length_meanqual', 'pd', 'platform', 'plt', 'rcparams', 'run', 'stats']
>>> `pauvre.__file__` and `pauvre.marginplot.__file__`
  File "<stdin>", line 1
    `pauvre.__file__` and `pauvre.marginplot.__file__`
    ^
SyntaxError: invalid syntax

**Comment by wdecoster** [comment]
That last part were two commands:
`pauvre.__file__`
and
`pauvre.marginplot.__file__`

**Comment by wdecoster** [comment]
Alright, let's try a nuclear solution, remove everything you have from pauvre and install it again:
```
pip uninstall pauvre
conda uninstall pauvre --force

cd /home/markwilks/anaconda3/lib/python3.6/site-packages
rm -r paurve*

conda install paurve==0.1.86
￼```

**Comment by Adelaam** [comment]
/anaconda3/lib/python3.6/site-packages$ conda install paurve==0.1.86

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - paurve==0.1.86

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by wdecoster** [comment]
Sorry, I had a typo:

`conda install pauvre==0.1.86`

**Comment by Adelaam** [comment]
Ok, now is working! 

But now I have got his error:

Traceback (most recent call last):
  File "/home/markwilks/anaconda3/bin/NanoPlot", line 6, in <module>
    from nanoplot.NanoPlot import main
ImportError: No module named nanoplot.NanoPlot

**Comment by wdecoster** [comment]
errr maybe you have to uninstall NanoPlot as well and install it again, similar to how I told you to do with pauvre. You have a problem with multiple python versions and conda environments...

**Comment by Adelaam** [comment]
Hello again,

Thank I have fixed the problem with python. I basecalled with guppy. 

But I have got this error now: 
ERROR: expected columns in summary file /media/markwilks/Elements/20190213_1525_MN24482_FAK28377_eed2d9cb/Abs-Cry_Guppy/barcoding_summary.txt not found:
 read_id, run_id, channel, start_time, duration, sequence_length_template, mean_qscore_template
Thank you!

**Comment by wdecoster** [comment]
Could you show me the header of the summary file? 

`head -n 1 barcoding_summary.txt`

**Comment by Adelaam** [comment]
read_id	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index

**Comment by wdecoster** [comment]
The header of a sequencing_summary.txt file looks like this:

`filename        read_id run_id  channel start_time      duration        num_events      passes_filtering        template_start  num_events_template     template_duration       sequence_length_template        mean_qscore_template    strand_score_template   median_template mad_template`

**Comment by Adelaam** [comment]
So the ones I get from guppy cannot be use with NanoPlot?

**Comment by wdecoster** [comment]
Guppy also creates a sequencing_summary.txt

**Comment by Adelaam** [comment]
Yes, I see. But not be separate by barcodes?

**Comment by wdecoster** [comment]
NanoPlot has a `--barcoded` option to split a summary file and create plots and stats per barcode.

**Comment by Adelaam** [comment]
Ah, ok thank you!!

**Comment by wdecoster** [comment]
Let me know if you need anything else!

**Comment by Adelaam** [comment]
Hello again,

I have tried with the summary sequence and --barcoded and I am getting this error: 

NanoPlot --barcoded --summary  '/media/markwilks/Elements/20190213_1525_MN24482_FAK28377_eed2d9cb/sequencing_summary/CLN_SMD_048994_20190213_FAK28377_MN24482_sequencing_run_Abs_cryp_74442_sequencing_summary.txt' 

ERROR: expected columns in summary file /media/markwilks/Elements/20190213_1525_MN24482_FAK28377_eed2d9cb/sequencing_summary/CLN_SMD_048994_20190213_FAK28377_MN24482_sequencing_run_Abs_cryp_74442_sequencing_summary.txt not found:
 read_id, run_id, channel, start_time, duration, sequence_length_template, mean_qscore_template, barcode_arrangement

An it is working well when I don't use --barcoded.
Thank you!

**Comment by wdecoster** [comment]
Can you show me the first line of your summary file? I don't know how guppy handles barcodes nowadays.

**Comment by Adelaam** [comment]
This is for the summary:
filename_fastq	filename_fast5	read_id	run_id	channel	mux	start_time	duration	num_events	passes_filtering	template_start	num_events_template	template_duration	sequence_length_template	mean_qscore_template	strand_score_template	median_template	mad_template

This for the barcoded summary: 

read_id	barcode_arrangement	barcode_full_arrangement	barcode_kit	barcode_variant	barcode_score	barcode_front_id	barcode_front_score	barcode_front_refseq	barcode_front_foundseq	barcode_front_foundseq_length	barcode_front_begin_index	barcode_rear_id	barcode_rear_score	barcode_rear_refseq	barcode_rear_foundseq	barcode_rear_foundseq_length	barcode_rear_end_index

**Comment by wdecoster** [comment]
Hmm with that information then no, --barcoded does not work.

**Comment by Adelaam** [comment]
ok, thank you!

**Comment by wdecoster** [comment]
You can now split a sequencing_summary.txt by the barcodes from the barcoded_summary.txt using this helper script: https://github.com/wdecoster/NanoPlot/blob/master/scripts/split_summary_on_barcodes.py

**Comment by ieknot** [comment]
Hi Wouter,
I thought I had to use the barcoding_summary.txt file with the --barcoded flag, but after reading this thread I realise I should use the sequencing_summary.txt file. How would I use the helper script you included above? Can I just type this in the terminal? Or should I save this as a file and run it using chmod or something else?
Thanks in advance!

**Comment by wdecoster** [comment]
You should save it as a file, e.g. `split_summary_on_barcodes.py` and run it as 

`python split_summary_on_barcodes.py sequencing_summary.txt barcoding_summary.txt`

No need to use chmod
