### ISSUE TITLE
behavour / rationale in downsampling

### ISSUE THREAD

**Issue by mblaxter** [wdecoster/NanoPlot#125]
Running nanoplot (brilliant btw) with downsample on a minION fastQ to even very small numbers of reads does not result in the expected time savings (e.g. 1.2 M minION reads: full analysis 25.1 min on 16 cores, --downsample 10000 25.0 min). Is downsample still processing all and then subsampling some? Or does it only come into its own when analysing 10's of M reads?

**Comment by wdecoster** [comment]
Good question, I implemented that because it was easy to do, not because I had a really good reason to do so. The program wil still extract data from all reads, then do the downsampling before plotting. Depending on the input format you will save some time... But I have never benchmarked that really.

**Comment by mblaxter** [comment]
Hi Wouter

yes... I tried 1000, 10000 and 100000 downsample from a 1 million read ONT minION fastq set, and the full IM took 25 mins (16 cores), with the downsamples taking between 24.5 and 25.5 mins (ie sometimes taking marginally longer).I am guessing that with the time taken to process all the data into memory, the plotting steps are actually a small proportion of the total time. I should probably rather subsample the readset and analyse that; maybe this can be commented in the docs?

Many thanks!

Mark


Professor Mark Blaxter
Institute of Evolutionary Biology
University of Edinburgh

Director, Genome Science
Edinburgh Genomics
http://genomics.ed.ac.uk




> On 17 Mar 2019, at 20:42, Wouter De Coster <notifications@github.com> wrote:
>
> Good question, I implemented that because it was easy to do, not because I had a really good reason to do so. The program wil still extract data from all reads, then do the downsampling before plotting. Depending on the input format you will save some time... But I have never benchmarked that really.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336.

**Comment by wdecoster** [comment]
I would naively assume that you would see a better improvement if you use the summary files. Processing fastq files is rather slow indeed. That would be worth improvin, bbut I don't have a time frame for it. Note that you can use multiple fastq files as input, which would be parsed in parallel then.

Indeed, subsampling before would probably save more. The log file contains time stamps, so you can get an idea about the most time consuming steps. Also some plots are quite slow, such as the kernel density estimates (kde).

Thanks for the suggestion, I'll add a line about subsampling before running NanoPlot to the documentation when I'm back in the office in a week.

**Comment by wdecoster** [comment]
I have added some things to consider about speed to the README at https://github.com/wdecoster/NanoPlot#notes
