### ISSUE TITLE
violin plot of speed over time

### ISSUE THREAD

**Issue by osilander** [wdecoster/NanoPlot#128]
I don't see the option right now, but it would be great to have speed vs. time to look for opportunities to refuel, or at the effects of a refuel (e.g. https://twitter.com/Scalene/status/1110186371757424641 )

**Comment by wdecoster** [comment]
That's a plot which is already included in NanoPlot (which is also what Josh used for that plot). It is created by default when time information is provided, which I would suggest you do with the sequencing summary file(s).

There is also a script which skips all other plots and makes just this sequencing speed plot: https://github.com/wdecoster/NanoPlot/blob/master/scripts/sequencing_speed_only.py

Let me know if anything is unclear.

**Comment by osilander** [comment]
shoot, thanks. Obviously haven't run the plotting yet
