### ISSUE TITLE
Stat summary only performed on passing filter reads ?

### ISSUE THREAD

**Issue by CedricMariac** [wdecoster/NanoPlot#129]
Hello,
can you confirm to me that the stat (N50, mean length ...) of the statistical summary are made only on the reads which are passing filter.
best
Cédric

**Comment by wdecoster** [comment]
_My answer assumes you have a recent version of NanoPlot, as for a very old version the behavior used to be different._

To give you a more precise answer: Which filter(s) exactly are you talking about?

If you are filtering on something that does affect the stats you will get two NanoStat files, one prior to applying filters and one after ("_post_filtering").

However, if you use a length filter (--maxlength, --minlength) then those will not be removed from the dataset, but only get **hidden** in length plots. I agree that the documentation on this is not as clear as it should be and will change that.

Does that answer your question? Is this behavior what you would expect?

**Comment by CedricMariac** [comment]
Hello,
Our basecalling is done with guppy which generates a summary sequencing file. This file is the input in my Nanoplot analysis.
In this file each read is assigned False or True in the field "passes_filtering". 
I wonder if False reads are excluded by Nanoplot when calculating stats summary.
Best regards
Cédric

**Comment by wdecoster** [comment]
Hi Cédric,

No, that column is ignored. It does correspond to a minimum quality score of 7, so you could use that for filtering in NanoPlot if you want to obtain results for only the passes_filtering=True reads.

Hope that helps,
Wouter
