### ISSUE TITLE
Columns Not Found

### ISSUE THREAD

**Issue by peflanag** [wdecoster/NanoPlot#130]
Hi,

I was running NanoPlot on a summary.txt file I got after basecalling with Guppy but it wont work. I've attached a screenshot below.

Cheers,

P

![Screenshot 2019-04-09 at 10 20 53](https://user-images.githubusercontent.com/32863969/55790079-8b0c5d80-5ab3-11e9-96aa-8bd5451ed4ae.png)

**Comment by wdecoster** [comment]
Guppy basecalling will not do demultiplexing, so there is no column "barcode_arrangement", and therefore `--barcoded` doesn't work.

If you want to split the sequencing_summary.txt per barcode you can use the barcoding_summary.txt from guppy with this script which I uploaded a couple of hours ago:
https://github.com/wdecoster/NanoPlot/blob/master/scripts/split_summary_on_barcodes.py

Please let me know if that doesn't solve your problem.

**Comment by peflanag** [comment]
Cheers. I don't have a barcoding_summary.txt file though. How do I generate that? Also I don't quite understand the script you wrote. As in I don't know what I do with it! Im a Microbiologist and don't understand script language if that makes sense. I'm kind of learning as I go!

**Comment by wdecoster** [comment]
I think you did an experiment with barcodes, right?

So you did guppy basecalling, but did you also do the demultiplexing step?
(demultiplexing = splitting the fastq file in the separate samples)
From what I understood, demultiplexing with guppy would generate the barcoding_summary.txt, but as we don't use barcodes I'm not too sure about that either ;-)

You would save this script somewhere and execute it as 
`python split_summary_on_barcodes.py sequencing_summary.txt barcoding_summary.txt`
and it would split your sequencing_summary.txt in multiple parts based on the information provided in the barcoding_summary.txt

**Comment by peflanag** [comment]
I didn't demux with guppy, I demuxed and trimmed with porechop Which means I would have to basecall again with guppy and demux! Cheers for the information though, it helps. I might give it a try again and see what happens!

**Comment by wdecoster** [comment]
Oh yeah, porechop can also be used, but doesn't generate a barcoding_summary.txt then. Oh well, messy situation. I'll close this now, let me know if I can help with something.

**Comment by claczny** [comment]
Thanks @wdecoster for the`split_summary_on_barcodes.py`, it is a very handy script!

May I just add a sneaky suggestion ;)
Couldn't it be modified to create a "barcoded" `sequencing_summary.txt` which could be directly used in NanoPlot, i.e., adding the barcode column instead of splitting into separate files?
Just an idea ;)

Best,

Cedric

P.S. Maybe I'll find the time to write it myself, but I would guess that @wdecoster could write it in a tiny fraction of the time it would take me ;)

**Comment by wdecoster** [comment]
Sure, that would be possible. I am not sure when I'll do some coding, so you are welcome to give it a go :)

**Comment by wdecoster** [comment]
I added `add_barcodes_to_summary.py`, which should do what you suggested.

**Comment by claczny** [comment]
That is awesome! Thanks a lot!
