### ISSUE TITLE
How is the N50 value calculated when there is no assembly?

### ISSUE THREAD

**Issue by BioinformaticsBro** [wdecoster/NanoPlot#132]
Won't there be redundant and overlapping sequences? If that's the case, how is it calculated? Or is N50 more synonymous to median in this context?

**Comment by wdecoster** [comment]
The N50 in the context of a long read sequencing library is a "read length N50", not a "contig N50" as used after genome assembly. But it is the same calculation, treating every read as it's a contig. There will definitely be overlapping and redundant sequences, but that's not the point. You're just looking at the distribution of the read lengths, in the same way that you look at the distribution of the contig lengths. 

Does that help?

**Comment by BioinformaticsBro** [comment]
Thanks for your response. What is the advantage of looking at the read N50 over the median?

**Comment by wdecoster** [comment]
Good question. It is a metric commonly used by the community, so I implemented it. Personally, I don't find it particularly intuitive and prefer a histogram over just some numbers.

**Comment by BioinformaticsBro** [comment]
Sure, so it's just convention. Thanks!
