### ISSUE TITLE
If I use a .bam file as input I have several warning

### ISSUE THREAD

**Issue by Matteo1988** [wdecoster/NanoPlot#133]
It still work, so maybe is not important, but if I use a .bam file as input I have several warning:
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/statsmodels/nonparametric/kernels.py:128: RuntimeWarning: divide by zero encountered in true_divide
  return (1. / np.sqrt(2 * np.pi)) * np.exp(-(Xi - x)**2 / (h**2 * 2.))
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/statsmodels/nonparametric/kernels.py:128: RuntimeWarning: invalid value encountered in true_divide
  return (1. / np.sqrt(2 * np.pi)) * np.exp(-(Xi - x)**2 / (h**2 * 2.))
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/statsmodels/nonparametric/_kernel_base.py:513: RuntimeWarning: invalid value encountered in true_divide
  dens = Kval.prod(axis=1) / np.prod(bw[iscontinuous])
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/matplotlib/contour.py:1557: UserWarning: Warning: converting a masked element to nan.
  self.zmax = float(z.max())
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/matplotlib/contour.py:1558: UserWarning: Warning: converting a masked element to nan.
  self.zmin = float(z.min())
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/matplotlib/contour.py:1203: RuntimeWarning: invalid value encountered in less
  under = np.nonzero(lev < self.zmin)[0]
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/matplotlib/contour.py:1205: RuntimeWarning: invalid value encountered in greater
  over = np.nonzero(lev > self.zmax)[0]
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/matplotlib/contour.py:1557: UserWarning: Warning: converting a masked element to nan.
  self.zmax = float(z.max())
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/matplotlib/contour.py:1558: UserWarning: Warning: converting a masked element to nan.
  self.zmin = float(z.min())
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/seaborn/axisgrid.py:1847: UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
  warnings.warn(UserWarning(msg))
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/seaborn/axisgrid.py:1847: UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
  warnings.warn(UserWarning(msg))
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/seaborn/axisgrid.py:1847: UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
  warnings.warn(UserWarning(msg))
/home/matteo/anaconda3/envs/nanoplot/lib/python3.6/site-packages/seaborn/axisgrid.py:1847: UserWarning: JointGrid annotation is deprecated and will be removed in a future release.
  warnings.warn(UserWarning(msg))

**Comment by wdecoster** [comment]
Hi,

Thanks for reporting this. I expect those to be quite harmless. Could you let me know which version of seaborn and matplotlib is installed?

You can get those using 
```
python -c "import seaborn ; print(seaborn.__version__)"
python -c "import matplotlib ; print(matplotlib.__version__)"
```

Updating these could also make some warnings disappear.

Cheers,
Wouter

**Comment by Matteo1988** [comment]
Hi, thanks for the answer.
seaborn: 0.9.0
matplotlib: 3.0.3

**Comment by wdecoster** [comment]
Hm yeah those are the most recent. If everything looks as expected I wouldn't worry about those warnings.

Please let me know if you encounter other issues.
