### ISSUE TITLE
--minlength flag not woking 

### ISSUE THREAD

**Issue by harmeet1990** [wdecoster/NanoPlot#136]
I am running NanoPlot 1.24.0 with a bam file as an input with minlength=5000 and minqual=7 flags. However, in the "NanoStats_post_filtering" file I still see reads smaller then 5000bp in the  "Top 5 highest mean base-call quality scores and their read lengths" section. They are filtered out in plots but shouldn't they also be filtered out in report? I am attaching the log, pre, and post filtering report
[NanoPlot_20190606_0810.log](https://github.com/wdecoster/NanoPlot/files/3260872/NanoPlot_20190606_0810.log)
[NanoStats.txt](https://github.com/wdecoster/NanoPlot/files/3260873/NanoStats.txt)
[NanoStats_post_filtering.txt](https://github.com/wdecoster/NanoPlot/files/3260875/NanoStats_post_filtering.txt)

 files.

Cheers!!
Harmeet

**Comment by wdecoster** [comment]
Hi Harmeet,

Thanks for opening this issue. I agree that it would make more sense to also remove those reads from the post_filtering stats file.
This should be fixed in NanoPlot v1.25.0 which is now available through pip.

Let me know if you have more feedback!

Cheers,
Wouter

**Comment by harmeet1990** [comment]
Works!! Thanks a ton for a fast fix!!
