### ISSUE TITLE
control scaling of plots?

### ISSUE THREAD

**Issue by johnsolk** [wdecoster/NanoPlot#137]
Hi! I really like NanoPlot and am putting together several figures for a publication comparing read quality vs. lengths from four different flow cell runs. I have run NanoPlot separately for each run, consistently using the same command with `--loglength`. However, the plots each have different scales. And I cannot figure out how to get the data out to make the plots myself, controlling the axis scales so they are fixed and comparable. Is there a way to control axis scales in NanoPlot, or get the summary data off?

Thank you for this tool and your time.

**Comment by wdecoster** [comment]
Did you try with `--maxlength` to restrict the plots to a certain length? That's however not guaranteed to give you plots with the same scale on the quality axis.

To get the data out, NanoPlot has a `--raw` option which will create a tab separated file of the numbers it is using for plotting. It also has a `--store` option which creates a .pickle file, containing the pandas DataFrame. I'm not sure if you are familiar with pickle and pandas, but I can walk you through on how to start plotting with those.

By the way, for comparing multiple runs you could have a look at [NanoComp](https://github.com/wdecoster/nanocomp), if you haven't already. But I realize that doesn't show the specific read quality vs read length plot that you are looking for, so that won't really help here.

**Comment by ljcohen** [comment]
Thank you for your quick reply! I am re-running NanoPlot with the three options you suggested above, and will see. Thanks again!

**Comment by wdecoster** [comment]
Alright let me know how it goes.

**Comment by ljcohen** [comment]
With the pickle I have been attempting to re-create the quality vs. read length plots. (`--maxlength` did not work to make plots for each run on the same axis) Would you be willing to take a look and possibly give me some tips for formatting, or point me towards some code? My plot does not seem to look anything like the ones generated in the NanoPlot report.

Plot attempt:
https://github.com/ljcohen/hybrid_genome_assembly/blob/master/ont_qc/nanoplotting.ipynb

Original NanoPlot report:
https://github.com/ljcohen/hybrid_genome_assembly/blob/master/ont_qc/Axen_nanoplot/LengthvsQualityScatterPlot_dot.png

Thank you

**Comment by wdecoster** [comment]
Part of the difference is that you don't have the read lengths log transformed. I'll make a change to nanoplotter, probably tomorrow, and get back to you on how to fix this. I'll make things a little easier.

**Comment by wdecoster** [comment]
If you update nanoplotter to v1.9.1 (available through pip) you can use the `scatter()` function as below. 

Getting your data:
```
import pandas as pd
from nanoplotter import scatter
import numpy as np
df = pd.read_pickle("./test-cases/NanoPlot-data.pickle")
```
Required arguments to `scatter()` are the following (for example):
```
scatter(x=df["lengths"], y=df["quals"], names=["Read lengths", "Average quality"], path="./QvsL", plots={"hex": 0, "kde": 0, "dot": 1, "pauvre": 0})
```

Optional arguments (and their defaults) are:
```
color="#4CB391",
figformat="png",
stat=None,
log=False,
minvalx=0,
minvaly=0,
xmax=None,
ymax=None
title=None,
plot_settings={}
```

You could set xmax and ymax using optional arguments:
```
scatter(x=df["lengths"], y=df["quals"], names=["Read lengths", "Average quality"], path="./QvsL", plots={"hex": 0, "kde": 0, "dot": 1, "pauvre": 0}, xmax=15000, ymax=11)
```

Using log transformation could be done as below:
```
scatter(x=np.log10(df["lengths"]), y=df["quals"], names=["Read lengths", "Average quality"], path="./QvsL", plots={"hex": 0, "kde": 0, "dot": 1, "pauvre": 0}, log=True)
```

Setting the xmax on a log transformation will include the next power of 10. To restrict the plot to 10000, use xmax=9999
```
scatter(x=np.log10(df["lengths"]), y=df["quals"], names=["Read lengths", "Average quality"], path="./QvsL", plots={"hex": 0, "kde": 0, "dot": 1, "pauvre": 0}, log=True, xmax=np.log10(9999))
```

Note that this code snippet may change slightly in the future, as I am thinking of moving the plotting functions from the nanoplotter submodule back into NanoPlot itself and as such reduce complexity for maintenance a bit.

Please let me know if this doesn't work.

**Comment by ljcohen** [comment]
Thank you! This is helpful. Kind of a silly question, how do you display the plot? The output of the scatter function looks like this for me:
```
[<nanoplotter.plot.Plot at 0x1775750f0>]
```
I've tried adding `%matplotlib inline`, but it did not work.

![scatter_object](https://user-images.githubusercontent.com/4043732/59718823-d471db00-91cf-11e9-8179-2f5085ab52f6.png)

**Comment by wdecoster** [comment]
The `scatter()` function will return a list of `Plot` class instances. The code for that custom class is [here](https://github.com/wdecoster/nanoplotter/blob/master/nanoplotter/plot.py).

Basically, it gives me some methods to `.save()` the file to an image and to an html, and hide some code away which is used over and over again. I could maybe add showing the image to those methods, but as far as I know you are the first to use the plotting functions interactively - and not as an image file or html report. But that's cool :)

I'm not sure if this is going to work, but you could try the following with %matploblib inline:
```
plots = scatter(...etc...)
my_plot = plots[0] # probably only one item in the list, depends on the plots dictionary in the function call
my_plot.fig.show()
```

If that doesn't work I'll add see if I can `my_plot.show()` method.

**Comment by ljcohen** [comment]
I see - thank you for the explanation.

It did not seem to work, unfortunately:
![plot_AttributeError](https://user-images.githubusercontent.com/4043732/59722130-ce7ff800-91d7-11e9-90d8-3172a9f0572b.png)

Basically, what I am trying to achieve is a faceted plot with all four of my runs for a publication. I want to control the axis ranges, label and title font sizes. Somewhat like this (pasted from four separate NanoPlot reports). Here, the axis labels are unreadable.

![face_qual_v_length](https://user-images.githubusercontent.com/4043732/59722377-5ebe3d00-91d8-11e9-950c-0502eedeff3c.png)

**Comment by wdecoster** [comment]
In nanoplotter v1.10.0, which I just made available through pip, there is a .show() method for Plot instances.

You can now do the following:

```
plots = scatter(x=df["lengths"], y=df["quals"], names=["Read lengths", "Average quality"], path="./QvsL", plots={"hex": 0, "kde": 0, "dot": 1, "pauvre": 0})
my_plot = plots[0]
my_plot.show() #show the figure if you are using %matplotlib inline
foo = my_plot.show() # assign the matplotlib.figure.Figure object to a variable
foo # show the figure if you are using %matplotlib inline
foo.suptitle("Look I am adding a title")
foo.axes #See which ax objects are there: 3 objects (main plot and marginal histograms)
foo.axes[0].set_ylabel("my new ylabel!!")
foo # show the figure again if you are using %matplotlib inline
```

Let me know if there is anything else I can help you with.

**Comment by wdecoster** [comment]
Could you get this working?
