### ISSUE TITLE
JPG and JPEG output

### ISSUE THREAD

**Issue by willemdek11** [wdecoster/NanoPlot#138]
In case of choosing jpg or jpeg as output format, you get the following error:
Invalid format jpeg, using default.

**Comment by wdecoster** [comment]
I'll check later what I get, but I believe the code checks which output formats are possible on your system. I'll get back to you.

**Comment by wdecoster** [comment]
I took a look in the code and indeeds, the code checks for which filetypes are possible depending on your system. I do not know what enables jpeg. 

You can check what's available on your system if you open a python terminal and execute:

```
import matplotlib.pyplot as plt
fig = plt.figure()
list(fig.canvas.get_supported_filetypes().keys())
```

Hope that helps.

**Comment by willemdek11** [comment]
Okay yes thank you!
