### ISSUE TITLE
information output

### ISSUE THREAD

**Issue by aspitaleri** [wdecoster/NanoPlot#139]
Hi there,
I am successfully running NanoPlot on my sequence_summary.txt from Albacore. Now I'd like to analyse the bam files from minimap2 run. I need to know please few things:
1. --bam  alignment1.bam alignment2.bam alignment3.bam makes an analysis averaging the 3 bam files? So if I need the plot for each file separately I will run NanoPlot in a loop, right?
2. --runtime_until option works only with sequency_summary? I tried with bam files but NanoPlot crashed. My idea is to analyze the bam file as function of time and I thought that this option could be perfect.  It seems that only way is to extract the reads as function of time, align them and then use NanoPlot to analyze them.
3. the plot percent identity vs read quality could be related to the error rate?
Thanks a lot for any help
Best

**Comment by wdecoster** [comment]
Hi,

Thanks for your questions and your interest in using NanoPlot.

1. The bam files will be combined, but every read will still get plotted separately. It doesn't really calculate an average, but the three datasets are pooled. Indeed, if you want plots for every alignment separately you need to run NanoPlot multiple times, for example in a loop. You can also use NanoComp to compare multiple experiments, in that case those three bams would be shown side-by-side.

1. There is no time information in a bam file, so NanoPlot can't show you that. One option would be to use `--store` while running for the summary file and the bam file, and combine the information later to create plots. You can find an example of that approach in [this blog post](https://gigabaseorgigabyte.wordpress.com/2018/12/17/nanopore-sequencing-percent-identity-over-time/).

1. The percent identity is the accuracy. Therefore, `error rate = 100 - percent identity`. A percent identity of 93% corresponds to a 7% error rate.

Let me know if anything else is unclear.

Wouter

There is no

**Comment by aspitaleri** [comment]
Hi Wouter
Thanks so much for the help! Indeed Nanoplot is a great tool!
1. Perfect
2. Yes I thought that using bam and sequence_summary would do the things. I will try your suggestion.
3. Okay. In the error rate calculation in this way will take in account also for the "true" variations . Is there any chance to exclude them e.g. considering the coverage or the frequency?
Thank you

**Comment by wdecoster** [comment]
3. Yes, true variation would also inflate the error rate. Then it also depends on how similar your reference genome is. For a human genome, which I have most experience with, this doesn't matter so much. as you only expect about 0.1% of SNVs. As such it shouldn't influence the accuracy that much.

NanoPlot shows you a "raw" accuracy/error rate, per read and per nucleotide. Taking into account coverage or frequency would require calculating a consensus (e.g. using medaka). That's a lot more complicated and not within the scope of NanoPlot.

**Comment by aspitaleri** [comment]
Yes indeed you are right. I am working on bacteria but I guess the SNPs should not affect so much the true error rate. Thanks a lot! You were so helpful!
Best

**Comment by aspitaleri** [comment]
I reopen the issue just to make sure that I am doing right for the 2.
I have run --store --bam, then --store --summary and the using the script in [https://gigabaseorgigabyte.wordpress.com/2018/12/17/nanopore-sequencing-percent-identity-over-time/](url) and I got a nice plot.
is that okay?

**Comment by wdecoster** [comment]
Yup, that would be perfect.

**Comment by wdecoster** [comment]
I'll close this now, let me know if you have further questions.
