### ISSUE TITLE
Inconsistent X-axis on non-log-transformed plots

### ISSUE THREAD

**Issue by piyuranjan** [wdecoster/NanoPlot#140]
When I generated a report for a fastq file that has sequences longer than 700 bases, the x-axis for read length shows data, for what I would suppose, is less than 500. The log-transformed axis for length shows the pattern that is expected in the same report.
![image](https://user-images.githubusercontent.com/2341240/60051541-3aaf9f80-96a1-11e9-85ee-3dcc8d51b21c.png)
![image](https://user-images.githubusercontent.com/2341240/60051557-4307da80-96a1-11e9-87fb-abeca4c82be6.png)

I am attaching NanoPlot reports from my pre- and post-filter fastq files.
[NanoPlotReports.zip](https://github.com/wdecoster/NanoPlot/files/3322592/NanoPlotReports.zip)
These are the commands I used to generate them:
```
NanoPlot -t 6 -o chn1NanoporeLib1_trim_NanoPlot --N50 --fastq chn1NanoporeLib1_trim.fastq
NanoPlot -t 6 -o chn1NanoporeLib1_trim_gt700_NanoPlot --N50 --fastq chn1NanoporeLib1_trim_gt700.fastq
```

I am using NanoPlot 1.25.1 installed via conda.

**Comment by wdecoster** [comment]
I think it is okay, based on what I can see. The log-transformed normal plot should use the same data. Comparing the non-filtered with the filtered histogram you can see the white gridline in the second plot, and the histogram goes to only 3000 reads (y-axis). There are also clear differences in the scatter plots below. It may be hard to see if 700bp are indeed absent if the plot goes up to 100000. Note that NanoPlot has a `--minlength` and `--maxlength` option to hide respectively shorter or longer reads in length-related plots. 

If you plot with `--maxlength 10000` you could hide everything > 10000 and see if there are reads < 700 bp. Also note that if you use a sequencing_summary for plotting you'll get more plots - as these contain more information.

Were these reads generated with a recent basecaller? I'm a bit surprised to see (in the scatter plot and stats) reads with both a very short length (1-5bp) and a high quality (~20-30). I consider these artifacts of the basecalling and these should get removed. My code automatically removes reads with a length below 20 and quality over 30, but that seems not stringent enough in your case.

**Comment by piyuranjan** [comment]
You are right. Sorry, it was my mistake for not reading the graphs correctly. For some reason, I was overlooking a zero on the x-axis several times I saw the non-log transformed graph... some days when you are too busy. :smile: 
When I visited the graphs a few days later, I saw where I was seeing them wrong.

**Comment by wdecoster** [comment]
Happy to help, let me know if there is anything else.
