### ISSUE TITLE
Lengths of sequence and quality values differs

### ISSUE THREAD

**Issue by woodoo46** [wdecoster/NanoPlot#141]
Hi there,

I ran Nanoplot as this:

NanoPlot --fastq test/test.fastq -t 2 

But I had this error:
ValueError: Lengths of sequence and quality values differs

I checked the length are actually the same in the fastq file. Do I need to specify some extra parameters? 

Thanks!

George

**Comment by wdecoster** [comment]
Please share the full log file. I will probably have time to look into this on Monday.

**Comment by wdecoster** [comment]
Do you have an update on this?

**Comment by woodoo46** [comment]
Sorry forgot to update, I think it is the package problem. I installed NanoPlot locally ( for my account only ). Initially, I added the library path (required for NanoPlot) after original $PYTHONPATH; that is how I dot the problem. After I switched the order, the program seems work properly. I do not know exactly which package causes the problem.

**Comment by wdecoster** [comment]
Did you use pip or conda for installation? With neither of these you should change your $PYTHONPATH

**Comment by woodoo46** [comment]
I used pip. I installed on a linux cluster without root right. I installed the pacakage on a specified directory, I am not sure if that is the problem. Or I may have made a stupid mistake I did not notice during the installation.

**Comment by wdecoster** [comment]
I usually do `pip install nanoplot --user`, but I don't know if your setup requires differently. But good to hear that now all is well. 

I'll close this issue now, but please let me know if you encounter other problems.
