### ISSUE TITLE
reads wronlgy barcoded

### ISSUE THREAD

**Issue by aspitaleri** [wdecoster/NanoPlot#143]
Hi,
not sure if it is possible to get. I wondering whether there is a possibility to calculate/plot  the percentage of reads wrongly barcoded by the tools such as porechop, guppy, etc ...

**Comment by wdecoster** [comment]
How do you know which is wrong?

**Comment by aspitaleri** [comment]
Indeed you are right. I estimate the percentage of reads wrongly barcoded just averaging  the number of reads present in the wrong barcoded (I mean the barcode that should not contains reads at all). I was just wondering whether was possible to extract from the log files from demultiplexing

**Comment by wdecoster** [comment]
I don't really understand which input information you have, and which calculation or plot you would like to obtain.

**Comment by aspitaleri** [comment]
Basically, doing demultiplexing of the fastq, both guppy albacore assigns few reads to wrong barcode. No information is possible to get from the log file. So, I estimated the percentage of wrong barcode reads looking to the barcode file which should NOT contain reads since they are not used in the sequencing exp. So I am wondering it would be useful to have a plot of <reads> per barcode sample in order to estimate the wrong barcode classifications. Hope I have been clearer. Cheers

**Comment by aspitaleri** [comment]
Basically, doing demultiplexing of the fastq, both guppy albacore assigns few reads to wrong barcode. No information is possible to get from the log file. So, I estimated the percentage of wrong barcode reads looking to the barcode file which should NOT contain reads since they are not used in the sequencing exp. So I am wondering it would be useful to have a plot of <reads> per barcode sample in order to estimate the wrong barcode classifications. Hope I have been clearer. Cheers

**Comment by wdecoster** [comment]
I won't support anything related to albacore, as that basecaller is deprecated and you should be using guppy.

I would prefer to work with the guppy sequencing_summary files for this. Do you have a sequencing_summary file which contains column `barcode_arrangement`?
Or do you have a barcoding_summary.txt?

**Comment by aspitaleri** [comment]
No, I have not such column in the sequencing_summary file. Does it should be there?

**Comment by wdecoster** [comment]
Do you then have a barcoding_summary.txt? Which data do you have? Only fastq files?

**Comment by aspitaleri** [comment]
In the guppy sequencing_summary is not present. Neither barcoding_summary.txt. In the albacore2 is present that column in sequencing_summary. Actually the sequencing from albacore2 contains much more info that in the guppy one.

**Comment by wdecoster** [comment]
Guppy does create a sequencing_summary file. If you use guppy to demultiplex, which files do you get?

**Comment by aspitaleri** [comment]
Ah okay. The barcoding  step was done for the guppy on another cluster which at the moment is down for maintenance. As soon as it will be back I let you know. From that file you want get the summary of barcoding process?
