### ISSUE TITLE
AttributeError with nanoplotter

### ISSUE THREAD

**Issue by Adaachill** [wdecoster/NanoPlot#144]
Hi, I have the AttributeError with nanoplotter
This is my code 
>NanoPlot -t 4 -o output/dir/path -p prefix --maxlength 40000 --title "title" --fastq path/to/fastq/all_2d.fq

Here is the error message

> If you read this then NanoPlot has crashed :-(
> Please try updating NanoPlot and see if that helps...
> 
> If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
> If you could include the log file that would be really helpful.
> Thanks!
> 
> 
> 
> Traceback (most recent call last):
>   File "/home/keiya/workspace/miniconda3/bin/NanoPlot", line 10, in <module>
>     sys.exit(main())
>   File "/home/keiya/workspace/miniconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 39, in main
>     args.format = nanoplotter.check_valid_format(args.format)
> AttributeError: module 'nanoplotter' has no attribute 'check_valid_format'

This error happened when I change input file bam.

This maybe filename error with nanoplotter but I cannnot handle it

**Comment by wdecoster** [comment]
Which version are you using? How did you install NanoPlot? Did you try updating?

**Comment by Adaachill** [comment]
Thanks for replying.
 I installed via miniconda3
And the version is 1.26.1

> ~/workspace/miniconda3/bin/NanoPlot -v
>NanoPlot 1.26.1

**Comment by wdecoster** [comment]
Could you please give me the output of:

```
python -c "import nanoplotter ; print(nanoplotter.__version__)"
python -c "import nanoplotter ; print(nanoplotter.__file__)"
```

**Comment by Adaachill** [comment]
Output is here 

>-bash-4.2$ python -c "import nanoplotter ; print(nanoplotter.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'nanoplotter' has no attribute '__version__'
-bash-4.2$ python -c "import nanoplotter ; print(nanoplotter.__file__)"
None
-bash-4.2$

**Comment by wdecoster** [comment]
Alright, that the `__version__` doesn't work is as expected for the current version.
However, I'm surprised that you get `None` for `__file__`. I tried installation on another system using conda, and I get a path.

Could you just uninstall and install NanoPlot and see if you get any errors?

**Comment by Adaachill** [comment]
Sorry for late reply.
I suceeded by uninstall and reinstall by conda.
thx
