### ISSUE TITLE
Unusably large html produced

### ISSUE THREAD

**Issue by kpalin** [wdecoster/NanoPlot#145]
At some point between versions 1.20 and 1.26 the HTML output has become extremely large completely crashing the web browser. The the plotly images, while nice looking, result in 700MB HTML files.

**Comment by wdecoster** [comment]
I agree - that's something I have to fix. Perhaps the easiest is to just leave the plotly image(s) out of the report. Shame they're so large though.

**Comment by wdecoster** [comment]
I have pushed a new version, v1.26.2, to PyPI, which removes this issue by simply not including these dynamic histograms in the report. 

In the long term, I would rather find a way to include them, probably by downsampling the number of points shown.

**Comment by wdecoster** [comment]
In the latest version, v1.26.3, now available through pip, a random sample of 10 000 reads is taken for these plotly histograms, making their incorporation in the html report again feasible.

Please let me know if you experience further issues!
