### ISSUE TITLE
Fraction of reads above 100Kb

### ISSUE THREAD

**Issue by rmsaha** [wdecoster/NanoPlot#146]
Hi! I was attempting to calculate the percentage of reads above 100kb from my PromethION dataset using a summary.txt file. Is there a good way to do it? 
--minlenghth appears to just hide the reads below specified length 
--minqual gives you a summary stats post filtering above the specified q value. Can something similar be done for read lengths? Thanks!

**Comment by wdecoster** [comment]
The quickest solution is probably to use awk for that.

Assuming a gzip-compressed summary file, the following gives you the number of lines with column 11 > 100000 (make sure to confirm that column 11 is sequence_length_template):

`zcat sequencing_summary.txt.gz | awk '$11 > 100000 {print ;}' | wc -l`

To get all lines/reads:

`zcat sequencing_summary.txt.gz | wc -l`

Note that for this last number the header line is included, although that probably won't influence your percentage that much. But to be correct, subtract 1.

It would be possible to add this to the NanoStats file, theoretically, but I'm not sure there is enough interest for doing that.

**Comment by rmsaha** [comment]
Thanks a lot for your reply!
