### ISSUE TITLE
NanoPlot installation issue

### ISSUE THREAD

**Issue by ilisem** [wdecoster/NanoPlot#148]
Hi,

I tried to install NanoPlot and related packages on my new Ubuntu 18 PC.
The installation appears to be succesful. However when I want to run NanoPlot, it simply says
`NanoPlot: command not found
`
I tried several ways of installing/uninstalling NanoPlot, each time with the same result. 
The installation also appears to be OK , after I checked by trying to reinstall with the command: pip3 install NanoPlot

`Requirement already satisfied: NanoPlot in ./.local/lib/python3.6/site-packages (1.27.0)
Requirement already satisfied: biopython in ./.local/lib/python3.6/site-packages (from NanoPlot) (1.74)
Requirement already satisfied: pysam>0.10.0.0 in ./.local/lib/python3.6/site-packages (from NanoPlot) (0.15.3)
Requirement already satisfied: pandas>=0.22.0 in ./.local/lib/python3.6/site-packages (from NanoPlot) (0.25.1)
Requirement already satisfied: numpy in ./.local/lib/python3.6/site-packages (from NanoPlot) (1.17.1)
Requirement already satisfied: scipy in ./.local/lib/python3.6/site-packages (from NanoPlot) (1.3.1)
Requirement already satisfied: python-dateutil in ./.local/lib/python3.6/site-packages (from NanoPlot) (2.8.0)
Requirement already satisfied: seaborn>=0.9.0 in ./.local/lib/python3.6/site-packages (from NanoPlot) (0.9.0)
Requirement already satisfied: matplotlib>=2.1.0 in ./.local/lib/python3.6/site-packages (from NanoPlot) (3.1.1)
Requirement already satisfied: nanoget>=1.9.0 in ./.local/lib/python3.6/site-packages (from NanoPlot) (1.9.0)
Requirement already satisfied: nanomath>=0.23.1 in ./.local/lib/python3.6/site-packages (from NanoPlot) (0.23.1)
Requirement already satisfied: pauvre==0.1.86 in ./.local/lib/python3.6/site-packages (from NanoPlot) (0.1.86)
Requirement already satisfied: statsmodels>=0.8.0 in ./.local/lib/python3.6/site-packages (from NanoPlot) (0.10.1)
Requirement already satisfied: plotly>=3.4.2 in ./.local/lib/python3.6/site-packages (from NanoPlot) (4.1.0)
Requirement already satisfied: pytz>=2017.2 in ./.local/lib/python3.6/site-packages (from pandas>=0.22.0->NanoPlot) (2019.2)
Requirement already satisfied: six>=1.5 in ./.local/lib/python3.6/site-packages (from python-dateutil->NanoPlot) (1.12.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib>=2.1.0->NanoPlot) (2.4.2)
Requirement already satisfied: kiwisolver>=1.0.1 in ./.local/lib/python3.6/site-packages (from matplotlib>=2.1.0->NanoPlot) (1.1.0)
Requirement already satisfied: cycler>=0.10 in ./.local/lib/python3.6/site-packages (from matplotlib>=2.1.0->NanoPlot) (0.10.0)
Requirement already satisfied: patsy>=0.4.0 in ./.local/lib/python3.6/site-packages (from statsmodels>=0.8.0->NanoPlot) (0.5.1)
Requirement already satisfied: retrying>=1.3.3 in ./.local/lib/python3.6/site-packages (from plotly>=3.4.2->NanoPlot) (1.3.3)
Requirement already satisfied: setuptools in ./.local/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib>=2.1.0->NanoPlot) (41.2.0)
`

Is there something obvious that I am missing? Or is my Ubuntu 18.04.2 LTS simply not compatible with Nanoplot. I used to have biolinux installed, but not anymore ...

**Comment by wdecoster** [comment]
It should definitely be compatible. The error indicates that the directory in which pip has NanoPlot installed is not in your $PATH, the set of locations in which your operating system will search for executables. You can check that using `echo $PATH`.

Did you install with sudo or just for your user?

**Comment by ilisem** [comment]
Yes, you are right. NanoPlot is not installed in my $PATH. I tried installing both using sudo as for my user. 
Do you have any idea how I can change the $PATH? After googling, I tried several commands but without any success. I probably need to remove and reinstall? 
Sorry for bothering you with - what is probably - a basic problem...

**Comment by wdecoster** [comment]
It's indeed a basic problem (and not specific to NanoPlot), but don't worry about it.

Remove and reinstall shouldn't be necessary. Usually, sudo is not necessary either.
Let's start with searching where your NanoPlot executable ended up by searching in your home directory:

`find ~ -name NanoPlot`

Say that this returns 
/home/youruser/bin/NanoPlot

You'll have to add that location to $PATH, for example in your ~/.bashrc configuration file you could add the following:

Open that configuration file with gedit or any other text editor you like:

`gedit ~/.bashrc`

`export PATH=/home/youruser/bin/:$PATH`

The directories in PATH are separated by `:`. In the example above I prepended the directory we found above to your PATH. As such your operating system will search there first. The rest of the PATH is kept as is.

**Comment by ilisem** [comment]
Thanks, it worked!
