### ISSUE TITLE
Cannot call NanoPlot using process substitution

### ISSUE THREAD

**Issue by BCArg** [wdecoster/NanoPlot#149]
I am trying to call `NanoPlot` using _process substitution_ to avoid calling it from the (huge) concatenated `.fastq`files.

If I do:
```
NanoPlot -t 8 -o out_QC/nanoplot/PD170815 -p PD170815 --loglength --N50 --fastq_rich <(cat /path/to/dir1/fastq_pass/*fastq /path/to/dir2/fastq_pass/*fastq /path/to/dir3/fastq_pass/*fastq)
```

I get the following error message:
```
File provided doesn't exist or the path is incorrect: /dev/fd/63
```

As I don't see any syntax error in my command, my question is whether or not `NanoPlot` is supposed to work using process substitution. I think that some conditions have to be met in order for a program to work with process substitution, as described [here](https://unix.stackexchange.com/questions/544732/store-cat-output-as-a-placeholder).

In case `NanoPlot` does not work with process substitution, is there a recommended way of calling it without having to save the concatenated `.fastq` file?

**Comment by wdecoster** [comment]
NanoPlot takes multiple files as input, so you could just do:  

`NanoPlot --fastq_rich /path/to/dir1/fastq_pass/*fastq /path/to/dir2/fastq_pass/*fastq /path/to/dir3/fastq_pass/*fastq`

You could also use (gzip) compressed fastq files

**Comment by BCArg** [comment]
But then I guess it will generate a report for each of the fastq files, no? I need to, somehow, concatenate them because they are from a single sample

**Comment by wdecoster** [comment]
No, it will combine all data from these files to generate one report.
