### ISSUE TITLE
No variation in Average read quality, skipping bivariate plot

### ISSUE THREAD

**Issue by rozaimirazali** [wdecoster/NanoPlot#151]
Hello.

I am not getting any of the read quality based figures.

Could you please explain what does this message means?

> 2019-10-21 14:05:16,120 Created length plots
> 2019-10-21 14:05:16,665 NanoPlot:  Creating Read lengths vs Average read quality plots using statistics from 9750083 reads.
**> 2019-10-21 14:05:16,819 NanoPlot:  No variation in Average read quality, skipping bivariate plot**
> 2019-10-21 14:05:16,820 Created LengthvsQual plot
> 2019-10-21 14:05:16,820 Writing html report.
> 2019-10-21 14:06:01,169 Finished!

Thanks!

**Comment by wdecoster** [comment]
It means that there is only one quality score found for all reads, and therefore no plot of read length vs average quality is made. Which input data do you use?

**Comment by rozaimirazali** [comment]
This is strange.

I am using fastq data which i converted from unaligned bam (the output from Pacbio Sequel machine)

This was my command:

> NanoPlot -t 32 --verbose --raw --outdir ../output/ --N50 --fastq ../input/QMD_87_04_p10.fastq.gz ../input/QMD_87_04_p11.fastq.gz ../input/QMD_87_04_p12.fastq.gz ../input/QMD_87_04_p13.fastq.gz ../input/QMD_87_04_p14.fastq.gz ../input/QMD_87_04_p15.fastq.gz ../input/QMD_87_04_p1.fastq.gz ../input/QMD_87_04_p2.fastq.gz ../input/QMD_87_04_p3.fastq.gz ../input/QMD_87_04_p4.fastq.gz ../input/QMD_87_04_p5.fastq.gz ../input/QMD_87_04_p6.fastq.gz ../input/QMD_87_04_p7.fastq.gz ../input/QMD_87_04_p8.fastq.gz ../input/QMD_87_04_p9.fastq.gz

**Comment by wdecoster** [comment]
Can you open one of the fastq files (e.g. using less) and take a look at the quality ascii string in there. I think they'll all be the same.

**Comment by rozaimirazali** [comment]
yes, they all have the same ascii string. Maybe the issue is during the conversion from bam to fastq in bam2fastq. ok thanks

**Comment by wdecoster** [comment]
I'm not sure, but I think not all PacBio data (maybe the older data) did not have quality scores assigned. So, therefore, they might get a "fake" quality score when converting to fastq.

**Comment by rozaimirazali** [comment]
Does Nanoplot accept unaligned bam as input ?

**Comment by wdecoster** [comment]
Yes, you can use `--ubam`. It seems this is not yet documented in the README, but it is in the help you get from `NanoPlot --help`.

**Comment by rozaimirazali** [comment]
I got an error when using --ubam

> 2019-10-21 16:51:59,585 Nanoget: Starting to collect statistics from ubam file ../input/m54107_190131_095334.subreads.bam.
> 2019-10-21 16:55:49,768 file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
> concurrent.futures.process._RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
>     r = call_item.fn(*call_item.args, **call_item.kwargs)
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
>     return [fn(*args) for args in chunk]
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
>     return [fn(*args) for args in chunk]
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 128, in process_ubam
>     samfile = pysam.AlignmentFile(bam, "rb")
>   File "pysam/libcalignmentfile.pyx", line 737, in pysam.libcalignmentfile.AlignmentFile.__cinit__
>   File "pysam/libcalignmentfile.pyx", line 986, in pysam.libcalignmentfile.AlignmentFile._open
> ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 61, in main
>     huge=args.huge)
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/site-packages/nanoget/nanoget.py", line 90, in get_input
>     dfs=[out for out in executor.map(extraction_function, files)],
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/site-packages/nanoget/nanoget.py", line 90, in <listcomp>
>     dfs=[out for out in executor.map(extraction_function, files)],
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
>     for element in iterable:
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
>     yield fs.pop().result()
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/gpfs/software/tools/python3.6.9/Python-3.6.9/install/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

my command was:

> NanoPlot -t 32 --verbose --raw --outdir ../output_input_is_bam/ --N50 --ubam ../input/m54106_190121_052820.subreads.bam ../input/m54106_190121_155539.subreads.bam ../input/m54106_190127_080112.subreads.bam ../input/m54106_190127_182553.subreads.bam ../input/m54106_190128_100929.subreads.bam ../input/m54106_190128_203552.subreads.bam ../input/m54107_190120_081543.subreads.bam ../input/m54107_190128_082633.subreads.bam ../input/m54107_190128_184834.subreads.bam ../input/m54107_190129_051813.subreads.bam ../input/m54107_190129_154921.subreads.bam ../input/m54107_190130_021825.subreads.bam ../input/m54107_190130_125040.subreads.bam ../input/m54107_190130_232213.subreads.bam ../input/m54107_190131_095334.subreads.bam

**Comment by wdecoster** [comment]
I think I identified the issue. It is raised if there initially was no index for the bam file. Next time it should be fixed (and in nanoget v1.9.1 is shouldn't return an error anymore, but I haven't made that version available yet).

**Comment by rozaimirazali** [comment]
Could you please tell me which line in NanoPlot.py I need to edit to get the ubam to work properly?

Thanks!

**Comment by wdecoster** [comment]
No manual changes required, you have to update the `nanoget` submodule to v1.9.1 which I just made available on pypi.

`pip install nanoget -U`

**Comment by rozaimirazali** [comment]
Thanks! Anyway, I just found out that even in the BAM all the bases in all the reads have the same value. I read somewhere this is because Pacbio Sequel machine does not output a quality value.

I was really hoping to produce the pauvre plot but it seems this is not possible since all of them have the same quality score. 

Anyway, thanks a lot for your kind assistance!
