### ISSUE TITLE
Creating plot with loglength option and without in the same run

### ISSUE THREAD

**Issue by Seajull** [wdecoster/NanoPlot#153]
Hi,

I've been using nanoplot for a while and it worked perfectly.
However, one little things bother me : it requires two run to get "classic" plot and loglength transformed plot.
Is there any way to get both in one run ?  

Thanks

**Comment by wdecoster** [comment]
Hi,

Thanks for the suggestion. Do you mean the bivariate/scatter plots, e.g. plotting read length against average quality?  I can think of changing how it is currently done.
If you are on a reasonably recent version then you should already get both standard and log-transformed histograms at the same time.

Some sort of a workaround to speed up multiple runs with the same input data is to use `--store`, which will create a NanoPlot-data.pickle file containing all metrics for plotting, which can then be used with `--pickle` later on as input source, avoiding parsing of the summary/fastq/bam file(s).

Cheers,
Wouter

**Comment by Seajull** [comment]
Yes for the scatter plot of read length vs average quality, 
As you said, i already both standard and log-transformed for histograms 
I've installed NanoPlot with conda, the version returned is 1.27.0

I'll try the store option for now,
Thanks !

**Comment by wdecoster** [comment]
I have just released v1.28.0 (on PyPI, conda will probably follow later this week), in which  `--loglength` will create the log-transformed scatter plots (and also length over time plots) **in addition** to the normal ones. The log-transformed plots will get a different file name accordingly to avoid overwriting.

Let me know if something unexpected happens or you have more suggestions!
