### ISSUE TITLE
Nanoplot installation with conda error

### ISSUE THREAD

**Issue by Annie-msi** [wdecoster/NanoPlot#154]
I am trying to install Nanoplot with conda,
Command: conda install -c bioconda nanoplot
Getting following error
Process killed for exceeding 15 minutes of user CPU time on a login node.
Conda version 4.5.4

**Comment by wdecoster** [comment]
This is not an installation error specific to NanoPlot. Rather, it seems your conda command took so long and got killed by the system. To prevent that you might have to talk to a sysadmin.

You can probably speed up conda by creating a separate environment:
`conda create -n nanoplot -c bioconda nanoplot`

which you can then activate using
`conda activate nanoplot`

It looks like you are trying to install NanoPlot on a cluster. I don't know much about installing software on log nodes and compute nodes.

Cheers,
Wouter
