### ISSUE TITLE
TypeError: get_input() got an unexpected keyword argument 'huge'

### ISSUE THREAD

**Issue by ieknot** [wdecoster/NanoPlot#155]
Hi, 

I've just successfully installed NanoPlot and wanted to try it out using a summary file. I tried it three times, twice with a Guppy sequencing_summary.txt file and once with a Guppy barcoding_summary.txt file.

The commands were 
`NanoPlot --summary sequencing_summary.txt`
and
`NanoPlot --summary barcoding_summary.txt --barcoded`

Summary_sequencing.txt log files:
[NanoPlot_20191115_1739.log](https://github.com/wdecoster/NanoPlot/files/3852696/NanoPlot_20191115_1739.log)
[NanoPlot_20191115_1810.log](https://github.com/wdecoster/NanoPlot/files/3852697/NanoPlot_20191115_1810.log)
Barcoding_summary.txt log file:
[NanoPlot_20191115_1819.log](https://github.com/wdecoster/NanoPlot/files/3852707/NanoPlot_20191115_1819.log)

All times I got the error message below. Any clue whether it's something I'm doing wrong or whether it's a bug? I've just installed it so it should be the latest version (NanoPlot 1.28.0):

If you read this then NanoPlot has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/Users/tiboug/miniconda3/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/Users/tiboug/miniconda3/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 61, in main
    huge=args.huge)
TypeError: get_input() got an unexpected keyword argument 'huge'

Thanks in advance!

**Comment by wdecoster** [comment]
It seems your nanoget is outdated, so you should update, so you need to update nanoget. Did you install NanoPlot using pip or conda?

**Comment by ieknot** [comment]
Hi Wouter, thanks for your quick reply. I installed NanoPlot using conda. Can I just update nanoget by installing it through conda? Like this:
`conda install -c bioconda nanoget`
Or do I need to uninstall it first?

**Comment by wdecoster** [comment]
Updating like that would be fine, please let me know how it goes!

**Comment by wdecoster** [comment]
Good to hear that!
