### ISSUE TITLE
invalid value encountered in greater_equal: IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by valery-shap** [wdecoster/NanoPlot#160]
Hello again)

Now i have sequencing_summary.txt file from guppy (FLO-MIN106, SQK-LSK108). This file is before barcoding.
my command was:
NanoPlot -t 30 --summary sequencing_summary.txt -o Documents
Error:
invalid value encountered in greater_equal

If you read this then NanoPlot has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/nanoplot/NanoPlot.py", line 72, in main
    settings["statsfile"] = [make_stats(datadf, settings, suffix="")]
  File "/usr/local/lib/python3.5/dist-packages/nanoplot/NanoPlot.py", line 112, in make_stats
    outputfile=statsfile)
  File "/usr/local/lib/python3.5/dist-packages/nanomath/nanomath.py", line 142, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/usr/local/lib/python3.5/dist-packages/nanomath/nanomath.py", line 142, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/usr/local/lib/python3.5/dist-packages/nanomath/nanomath.py", line 35, in __init__
    self.n50 = get_N50(np.sort(df["lengths"]))
  File "/usr/local/lib/python3.5/dist-packages/nanomath/nanomath.py", line 59, in get_N50
    return readlengths[np.where(np.cumsum(readlengths) >= 0.5 * np.sum(readlengths))[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

IndexError: index 0 is out of bounds for axis 0 with size 0

log file:
[NanoPlot_20191129_1510.log](https://github.com/wdecoster/NanoPlot/files/3905148/NanoPlot_20191129_1510.log)

**Comment by wdecoster** [comment]
Could you take a look at the end of the file, using tail? I suspect that the last line is corrupted because something went wrong during the creation or transfer of the file.

If that looks normal, could you please share the file so I can have a look?

**Comment by valery-shap** [comment]
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	f3fd833a-1756-435c-8c0b-15c3777faeab	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	418	3	17073.173000	72.717000	145434	TRUE	17073.200500	145379	72.689500	26804	12.448853	0.000000	73.265266	9.571471
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	49e35287-a42c-4589-a953-1ae23c3fdf2c	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	371	2	17157.943750	1.725750	3451	TRUE	17158.155250	3028	1.514250	501	10.735317	0.000000	75.179558	10.093552
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	eee1645a-e718-4f90-8bc8-ede15578725e	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	20	4	17138.074000	0.746500	1493	FALSE	17138.140500	1360	0.680000	349	4.498760	0.000000	72.047081	5.916910
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	4f869966-9b21-4fcb-b5d5-1faa2773d0db	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	250	3	17152.194500	19.887750	39775	TRUE	17152.250500	39663	19.831750	8026	10.483952	0.000000	74.135399	9.397445
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	6a844989-dc6c-4867-acba-6b85f50f64ab	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	147	2	17143.844750	1.238500	2477	TRUE	17143.893750	2379	1.189500	429	11.460755	0.000000	74.135399	9.397445
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	a1649d4a-e849-46b4-8c1d-427b973401b0	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	370	2	17168.658500	0.928000	1856	TRUE	17168.689000	1795	0.897500	337	7.338943	0.000000	78.312042	10.267579
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	c0300d95-0c41-481f-90d8-4119fed3704d	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	29	2	17172.841250	4.403250	8806	TRUE	17172.999250	8490	4.245250	1555	9.445163	0.000000	74.135399	8.875364
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	510b6f8a-6319-47b4-8c46-4dcee18ea6ae	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	19	3	17168.025500	1.516250	3032	TRUE	17168.223500	2636	1.318250	474	9.954142	0.000000	77.789963	7.657177
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	f9e3a9eb-f202-4798-8ba1-7e47e0474eee	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	271	3	17150.081500	5.159500	10319	TRUE	17150.296000	9890	4.945000	2052	10.169583	0.000000	74.657478	8.875364
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_403.fast5	b4643c4d-e5d8-408d-a144-1473d2022632	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1721	222	2	17166.889000	3.469500	6939	TRUE	17167.074000	6569	3.284500	536	10.539491	0.000000	76.049690	8.701338

**Comment by valery-shap** [comment]
Looks like everything is ok, isn't?

**Comment by wdecoster** [comment]
On first glance yes.

**Comment by wdecoster** [comment]
Okay, so it was not the end of your file which is corrupted, but somewhere in the middle. Specifically, lines 8001-8006 or something like that. 

Looks like:

```
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_667.fast5	6f1a210c-ef98-4e14-9491-47b094aa08c4	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1	296	1	29485.365250	2.011000	4022	TRUE	29485.598250	3556	1.778000	616	12.230894	0.000000	76.397743	9.049392
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_667.fast5	d4bc0dbc-bab1-4bca-b21a-e9d26ae282ea	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	1	360	1	29445.883500	1.962000	3924	TRUE	29445.895500	3900	1.950000	640	13.565303	0.000000	76.919830	9.745499
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5	de5afb91-11c0-4e9f-9d91-4c47f172d130	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5	3f59bb9e-fbe8-49e6-b79a-f361b0241697	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5	36f26b73-a200-48ef-934c-d74a275f1a51	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5	41a8ef3b-fb17-4660-9815-45aa751b52c5	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	2	434	1	28233.588750	1.407750	2815	TRUE	28233.625250	2742	1.371250	537	11.490999	0.000000	79.182175	9.397445
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5	e30bfc5f-d007-405a-96ea-3f2953969974	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	2	397	4	28233.984500	0.896250	1792	TRUE	28234.010000	1741	0.870750	328	8.167258	0.000000	78.312042	8.527311
FAK88622_e3a27109d32dbfa87b0df7c4deb01d53d0e969b7_642.fast5	a3373b91-e5b8-4d1b-baf5-aea45b3f79f4	e3a27109d32dbfa87b0df7c4deb01d53d0e969b7	2	218	1	28226.614250	5.003000	10006	TRUE	28226.830250	9574	4.787000	1714	13.091834	0.000000	72.917213	9.223418

```

**Comment by valery-shap** [comment]
Ok, l'll look at the log file of guppy, because there were no errors during the process.
Maybe these reads are very important for me)
Could you please explain me how you checked it so quick and find the error strings? Or is it developer's magic?)

**Comment by wdecoster** [comment]
I first saved the dataframe that NanoPlot uses to a .pickle file using

NanoPlot --summary sequencing_summary.txt --store

Then I did it in python:

```
import pandas as pd
df = pd.read_pickle("NanoPlot-data.pickle")
readlengths = df["lengths"]
readlengths.sort_values()
```

That shows that there are NaN values at lines 8000-8004.

**Comment by valery-shap** [comment]
Thank you very much, I'll try to do it by myself. Sorry for worrying you again.
