### ISSUE TITLE
NAnoplot command not found

### ISSUE THREAD

**Issue by turbo4xl** [wdecoster/NanoPlot#161]
I installe everything on ubuntu tested package and version now when i use the code 
Nanoplot --summary sequencing_summary.txt --loglength -o summary-plots-log-transformed
I get command not found 
I am new to  anaconda so I am probably using it wrong any basic help will be great.

**Comment by wdecoster** [comment]
You should check if ~/anaconda4/bin is in your $PATH

**Comment by turbo4xl** [comment]
here is the path for an environment i created: (ngs) fdelago@fdelago-System-Product-Name:~/analysis$ $eecho $PATH
bash: /home/fdelago/anaconda3/envs/ngs/bin:/home/fdelago/anaconda3/bin:/home/fdelago/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin: No such file or directory

**Comment by turbo4xl** [comment]
(ngs) fdelago@fdelago-System-Product-Name:~/analysis$ echo $PATH
/home/fdelago/anaconda3/envs/ngs/bin:/home/fdelago/anaconda3/bin:/home/fdelago/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

**Comment by turbo4xl** [comment]
I thing the problem was the command spelling. it is case sensitive should be NanoPlot.
