### ISSUE TITLE
Plotting read length vs quality with axes not starting from zero

### ISSUE THREAD

**Issue by oliemery** [wdecoster/NanoPlot#163]
Hello, first thank you for this nice piece of software which is highly appreciated.
I was wondering if it was possible to make the read length vs average read quality plot so that, for example, the axes coordinates start at 250 bp for the length and at 10 for the quality values?
In my case, I would like to display filtered values (=reads of min 250bp and max 400bp, with minimum quality of 10) and this make most of my plot empty (without data points) as it starts with zero on both axes.
![image](https://user-images.githubusercontent.com/26964826/70860797-7e83b300-1f26-11ea-8494-54440015587a.png)
Here is the command I used:
NanoPlot -t 2 --fastq filtSeqs.fastq --minlength 250 --maxlength 400 --minqual 10 --plots hex dot -o outputPlot

**Comment by wdecoster** [comment]
Hi oliemery,

I agree that your plot would look nicer by cropping the empty space. That's definitely possible, technically, but I'm not sure if I want to add other flags to NanoPlot to limit plots to these minimal read lengths and quality scores. Do you think this is something you or others would use often?
I don't want to create a tool with hundreds of options :)

Anyway, I want to point you to this thread: https://github.com/wdecoster/NanoPlot/issues/137
It shows you how to use the `scatter()` function from NanoPlot and set the x and y-limits. It's definitely more work than just running the tool from the command line though. Let me know if that doesn't work for you.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Did using the scatter() function interactively help?
