### ISSUE TITLE
new feature: use lbzip2 libs instead of bzip2

### ISSUE THREAD

**Issue by spock** [wdecoster/NanoPlot#165]
Hi,

thank you for implementing support for compressed input files!

I've been happily using `lbzip2` as a drop-in replacement for `bzip2` for several years now, and I'm super-happy about the speed up I'm getting from it.

When using NanoPlot on uncompressed input and .bz2 input, I noticed that .bz2 processing is slower. I've conda-installed `lbzip2`, but that doesn't seem to have any effect - I guess NanoPlot binds into `bzip2` library, given the `missing libbz2.so.x` I had to workaround.

On a compressed `sequencing_summary.txt.bz2` file:
```
2:40.66 total, 12.95s kernel, 162.57s user ; max RES 3134008 Kb ; 20355 [I/O] waits
```

On a plain `sequencing_summary.txt` file:
```
1:43.34 total, 13.06s kernel, 105.12s user ; max RES 3126292 Kb ; 20380 [I/O] waits
```

Do you think it would be worth the effort to use lbzip2 libraries if/when present?
Or maybe even as the default, instead of bzip2?
I didn't check deeper, but I suspect that the 1-minute speed difference does come from single-threaded bz2 decompression.

**Comment by wdecoster** [comment]
Hi spock,

I directly use the bz2 module from the python standard library (https://docs.python.org/3/library/bz2.html), and as such don't explicitly control if lbzip2 or bzip2 is used for (de)compression.
I assume `bz2` uses `bzip2` and therefore gives you the slower decompression.

Have you tested process substitution for decompression?
Something like `NanoPlot --summary <(lbzip2 your_summary.txt.bz2)` 

I agree that's not too elegant, but I don't think I want to support and/or maintain optional decompression with lbzip2 if available, and use standard bzip2 when it's not. It's a nice speedup, but also too much trouble. What would be best here is that the `bz2` python module gets changed to do what you want.

Please let me know what you think.

Cheers,
Wouter

**Comment by spock** [comment]
Makes perfect sense to me 🙂
