### ISSUE TITLE
ValueError plotly with bam file

### ISSUE THREAD

**Issue by aroelo** [wdecoster/NanoPlot#169]
Hi Wouter, 

I'm trying to run NanoPlot on a bam file and get an error from plotly.

The cmd I ran is:
`NanoPlot --bam test.bam -o tomaat_nanoplot --title test --verbose 2>&1 | tee log.txt`

And the corresponding [log.txt](https://github.com/wdecoster/NanoPlot/files/4211955/log.txt) file.
And error:
`Invalid properties specified for object of type plotly.graph_objs.Layout: ('yaxis_title', 'xaxis_title')`  

It might be good to know that this file was successfully analysed with NanoComp. I did have to cheat a little, and commented out 3 lines that check for the SO:coordinate line, because this is not in the header of my bam file (https://github.com/wdecoster/nanoget/blob/ff90232eab81b530168d5f9788293ff24796ccd1/nanoget/extraction_functions.py#L107), but I'm sure that it is sorted.

Any idea what could be going wrong?

Thanks

**Comment by wdecoster** [comment]
Thanks for reporting, I'll try later today if I can reproduce this. Meanwhile, could you have a look at your plotly version?

Executing this in your command line should work:
`python -c "import plotly ; print(plotly.__version__)"`

Cheers,
Wouter

**Comment by aroelo** [comment]
Thanks for the quick reply and looking into it.

Executing the above command gives version '3.7.1'

**Comment by wdecoster** [comment]
I was able to reproduce this by downgrading my plotly installation to 3.7.1, but did not have the issue originally on plotly 4.1.0. I have now changed the minimal required plotly version to be 4.1.0, could you verify that the error goes away with updating?

**Comment by aroelo** [comment]
Thanks, this fixed the issue!
