### ISSUE TITLE
Misleading channel heatmap for flongle flowcells

### ISSUE THREAD

**Issue by dariober** [wdecoster/NanoPlot#170]
Hi- I'm looking at some data from [flongle](https://nanoporetech.com/products/flongle) flowcells. I think the plot "Number of reads generated per channel" is a bit misleading because flongle has 126 channels instead of 512. This results in a heatmap where it seems only the channels on the sides of the flowcell are active. See below, this is with nanoplot 1.28.2.

![image](https://user-images.githubusercontent.com/6883382/75685003-cb5b6800-5c91-11ea-970a-88364bbbeb15.png)

**Comment by wdecoster** [comment]
That's right, the code is not yet okay for Flongle. I'll have to add the Flongle layout

**Comment by wdecoster** [comment]
This should be fixed in NanoPlot v1.29.0, please let me know if you see anything unexpected.
