### ISSUE TITLE
Why does the plot look abnormal？

### ISSUE THREAD

**Issue by 18616831168** [wdecoster/NanoPlot#172]
![LengthvsQualityScatterPlot_dot](https://user-images.githubusercontent.com/57974961/76588121-28241180-6521-11ea-8d6e-72eadbd91959.png)
![LengthvsQualityScatterPlot_hex](https://user-images.githubusercontent.com/57974961/76588133-2c502f00-6521-11ea-8952-f333e1e56fe2.png)
![LengthvsQualityScatterPlot_kde](https://user-images.githubusercontent.com/57974961/76588135-2e19f280-6521-11ea-9f02-397a8337fe8e.png)
![LengthvsQualityScatterPlot_pauvre](https://user-images.githubusercontent.com/57974961/76588137-2f4b1f80-6521-11ea-8eb5-442e433519fc.png)

**Comment by wdecoster** [comment]
I can see which plot you mean, but would you mind giving some information or actually type out a question? I'd need to know how you installed NanoPlot, which version you have and which version of pauvre you have installed. The pauvre version you can get with `python -c 'import pauvre ; print(pauvre.__version__)'`.

**Comment by liuguoqi** [comment]
@wdecoster 
hi,thank you for developing this tools, it is quite good,but my LengthvsQualityScatterPlot_pauvre.png look abnormal and my pauvre version is 0.1.86 
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
atk                       2.25.90           hf2eb9ee_1001    conda-forge
bioconductor-rhdf5        2.24.0           r341hfc679d8_0    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
bioconductor-rhdf5lib     1.2.1            r341h470a237_0    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
biopython                 1.76             py36h516909a_0    conda-forge
bokeh                     2.0.1            py36h9f0ad1d_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
curl                      7.61.0               h93b3f91_2    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
gdk-pixbuf                2.32.2                        1    bioconda
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gobject-introspection     1.56.1          py36h9e29830_1001    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gsl                       2.2.1                h0c605f7_3    defaults
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
gtk2                      2.24.31           h5baeb44_1000    conda-forge
harfbuzz                  1.9.0             he243708_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.9                      pypi_0    pypi
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.2.0            py36hdb11119_0    conda-forge
krb5                      1.14.6                        0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.9.2                he1b5a44_0    conda-forge
markupsafe                1.1.1            py36h8c4c3a4_1    conda-forge
matplotlib                3.1.1                    py36_0    conda-forge
matplotlib-base           3.1.1            py36hfd891ef_0    conda-forge
nanofilt                  2.6.0                      py_0    bioconda
nanoget                   1.12.1                     py_0    bioconda
nanomath                  0.23.1                     py_1    bioconda
nanoplot                  1.29.0                     py_0    bioconda
nanoqc                    0.9.2                      py_0    bioconda
nanostat                  1.2.0                      py_0    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.18.1           py36h7314795_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.0.2u               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py36h830a2c2_1    conda-forge
pango                     1.40.14           hf0c64fd_1003    conda-forge
parallel                  20160622                      1    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
patsy                     0.5.1                      py_0    conda-forge
pauvre                    0.1.86                     py_1    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-threaded             5.26.0                        0    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
pillow                    7.1.1            py36h8328e55_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
plotly                    4.6.0              pyh9f0ad1d_0    conda-forge
psutil                    5.7.0                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pysam                     0.15.3           py36hda2845c_1    bioconda
python                    3.6.7             hd21baee_1002    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3.1            py36h8c4c3a4_0    conda-forge
qt                        5.6.2             hbe13537_1012    conda-forge
r-base                    3.4.1                h4fe35fd_8    conda-forge
r-bit                     1.1_12           r341h470a237_2    conda-forge
r-bit64                   0.9_7            r341hc070d10_0    conda-forge
r-data.table              1.11.6           r341hc070d10_0    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
r-digest                  0.6.18           r341hc070d10_0    conda-forge
r-htmltools               0.3.6            r341hfc679d8_2    conda-forge
r-httpuv                  1.3.6.2          r341hfc679d8_1    conda-forge
r-jsonlite                1.5              r341hc070d10_2    conda-forge
r-mime                    0.5              r341hc070d10_2    conda-forge
r-pore                    0.24                   r3.4.1_0    https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
r-r6                      2.2.2            r341h6115d3f_1    conda-forge
r-rcpp                    1.0.0            r341h9d2a408_0    conda-forge
r-rstudioapi              0.7              r341h6115d3f_1    conda-forge
r-shiny                   1.0.5                  r3.4.1_0    conda-forge
r-sourcetools             0.1.7            r341hfc679d8_0    conda-forge
r-svdialogs               1.0.0            r341h6115d3f_0    conda-forge
r-svgui                   1.0.0            r341h6115d3f_0    conda-forge
r-xtable                  1.8_3                 r341_1000    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.23.0                   pypi_0    pypi
retrying                  1.3.3                      py_2    conda-forge
scipy                     1.4.1            py36h2d22cac_3    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
setuptools                46.1.3           py36h9f0ad1d_0    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
statsmodels               0.11.1           py36h8c4c3a4_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
typing_extensions         3.7.4.1          py36h9f0ad1d_3    conda-forge
urllib3                   1.25.9                   pypi_0    pypi
wheel                     0.34.2                     py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.4                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge


![LengthvsQualityScatterPlot_pauvre](https://user-images.githubusercontent.com/16409585/79712929-d41a0300-82fe-11ea-98a4-25b2fd63d367.png)

**Comment by wdecoster** [comment]
Hmm I don't immediately have an idea what could be wrong, what do you think @conchoecia?

**Comment by liuguoqi** [comment]
ok,thx, I I think it might be about the layout of plot or package version

**Comment by conchoecia** [comment]
v0.2 was just released. My best guess at this point is to just try that, and report back if it does not work.

**Comment by liuguoqi** [comment]
@conchoecia @wdecoster  Thx for your reply ,I have tested v0.2 is ok !
