### ISSUE TITLE
Fix axis between two different plots or combine two plots in one

### ISSUE THREAD

**Issue by hrpelg** [wdecoster/NanoPlot#173]
![image](https://user-images.githubusercontent.com/32914805/76819202-6c3e4b80-686c-11ea-84d2-e989f2e740c7.png)
![image](https://user-images.githubusercontent.com/32914805/76819228-7b24fe00-686c-11ea-9ffa-10bd62522940.png)
 I would like to have the same y-axis in these two plots coming from two different datasets, is taht possible? 

Is it possible to combine both datasets in the same plot, with different color or pattern?

Cheers, 

E

**Comment by wdecoster** [comment]
Hi,

This question is very similar to https://github.com/wdecoster/NanoPlot/issues/137, so please see if the answers there are helpful.
But anyway, for comparing multiple datasets I would suggest [NanoComp](https://github.com/wdecoster/nanocomp). I don't plan to add a way to combine multiple plots in NanoPlot, but could if needed add other visualizations to NanoComp.

Cheers,
Wouter
