### ISSUE TITLE
inconsistent read length plots : Bam vs Fastq

### ISSUE THREAD

**Issue by nhartwic** [wdecoster/NanoPlot#175]
As part of preprocessing for assembly, I frequently subset down to some reasonable coverage (30x) of the longest reads. I noticed during my most recent test of nanoplot that the read length distribution derived from the bam files is not correct. You can check out the attached images for an example. The top image was generated by nanoplot when provided bam input. The bottom was generated by nanoplot when provided fastq input. I've verified with my own script that the plot generated by the fastq input is correct. Is this error when providing bam input a known bug? Perhaps a limitation of the file format?

![bam_Weighted_LogTransformed_HistogramReadlength](https://user-images.githubusercontent.com/13526494/76981103-56c23380-68f7-11ea-9c23-606d4df87c9e.png)
![fastq_Weighted_LogTransformed_HistogramReadlength](https://user-images.githubusercontent.com/13526494/76981105-575aca00-68f7-11ea-81b9-2ff764f7a4a9.png)

**Comment by wdecoster** [comment]
Hi,

You are right that the plots are different, but not necessarily one of them is wrong. Related issue: https://github.com/wdecoster/nanoget/issues/17
First, NanoPlot with bam input doesn't show you reads which did not align (are unmapped). Second, the thing is that during alignment reads get split into primary and supplementary (chimeric) alignments. It's an open question of what to do with those. Part of my reasoning for the current implementation can be found in this pull request: https://github.com/wdecoster/nanoget/pull/18

Does that make sense to you?

Cheers,
Wouter

**Comment by nhartwic** [comment]
Makes sense. At the very least the labels should be considered erroneous. Reads aren't being represented, mappings are. 

Is my understanding correct that when run in bam mode, the Y axis should be "number of mapped bases" and the X axis should be "Mapped Length" and the title should be "Weighted histogram of mapping lengths after log transform"?

Long term, I think my most desirable behavior would be to make fastq or summary files a required input regardless of whether or not bam files are provided. That way, nanoplot could generate both types of plots that accurately represent the reads and the mappings as appropriate rather than conflating the two.

**Comment by wdecoster** [comment]
NanoPlot now has a --no_supplementary option to omit supplementary alignments when extracting features from a bam or cram file. I hope that helps.

> Is my understanding correct that when run in bam mode, the Y axis should be "number of mapped bases" and the X axis should be "Mapped Length" and the title should be "Weighted histogram of mapping lengths after log transform"?
Indeed, everything in bam mode relates to alignments and mapped bases.
