### ISSUE TITLE
NanoPlot Error

### ISSUE THREAD

**Issue by IMSS-DMS** [wdecoster/NanoPlot#179]
I'm getting a "ValueError: Whitespace is not allowed in the sequence" when I try to run NanoPlot with a particular fastq file. It doesn't seem to be the version/require an update, since I have no issues with other fastq files.
[NanoPlot_20200416_0949.log](https://github.com/wdecoster/NanoPlot/files/4488373/NanoPlot_20200416_0949.log)

**Comment by wdecoster** [comment]
Is that a fastq file you can share?

**Comment by IMSS-DMS** [comment]
I resolved the error with the fastq file and NanoPlot is working.
Thanks!

**Comment by wdecoster** [comment]
Oh, perfect!
