### ISSUE TITLE
Nanoplot error

### ISSUE THREAD

**Issue by rnroland** [wdecoster/NanoPlot#180]
Hi, Trying to run Nanoplot here. I load the files OK  but the nanoplot returns the following error. 

"If you read this then NanoPlot has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!"

I don't know how to update Nanoplot?
<img width="1662" alt="Screen Shot 2020-05-06 at 9 28 28 AM" src="https://user-images.githubusercontent.com/60156276/81206525-15f2ac80-8f81-11ea-9b29-08cb7d9a8dd8.png">

**Comment by rnroland** [comment]
Sorry, Thank you for your time, but I'm not sure how I will see a response to my query?

**Comment by wdecoster** [comment]
I don't maintain or use NanoPlot through Galaxy, can you find the log file? Don't worry about the updating part, you most likely can't.

**Comment by rnroland** [comment]
Hello, Thank you for getting back. Please let me know how to locate the log file. I searched Galaxy Help to find out how to do this but could find the information.

**Comment by wdecoster** [comment]
I've asked the Galaxy people for help.

**Comment by mvdbeek** [comment]
@rnroland please submit a bug report by clicking on one of the red datasets. There is a bug icon, if you expand the dataset. If you click on this you can submit the report.

<img width="231" alt="Screenshot 2020-05-08 at 12 31 26" src="https://user-images.githubusercontent.com/6804901/81397580-f1850480-9127-11ea-8364-63b48e317e42.png">

<img width="683" alt="Screenshot 2020-05-08 at 12 31 37" src="https://user-images.githubusercontent.com/6804901/81397594-f3e75e80-9127-11ea-8a42-f9e43f2ec714.png">

If there is anything wrong with nanoplot itself (and not the usage or the galaxy wrapper) we'll follow up, but I think you can close this issue, and thanks for the ping @wdecoster.

**Comment by mmiladi** [comment]
@rnroland Which of the (public) Galaxy servers are you using?

**Comment by mvdbeek** [comment]
it's .org, you can see the banner on top of the screenshot.

**Comment by mmiladi** [comment]
@mvdbeek so true, no logo but the banner is for sure a unique identifier :-)

**Comment by wdecoster** [comment]
Thanks for following up, let me know if there is something I have to fix. I'll close this for now...
