### ISSUE TITLE
crash on ubuntu 18 conda installation

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#182]
Hi Wouter, 
Just getting back to Nanopore sequencing lately, and I am getting a crash that I can't understand.
Command:
![nanoplot_command](https://user-images.githubusercontent.com/33500125/83335602-fe56cd00-a27b-11ea-8b0e-0a045789ae50.PNG)
log file:
[NanoPlot_20200530_1301.log](https://github.com/wdecoster/NanoPlot/files/4706167/NanoPlot_20200530_1301.log)

**Comment by wdecoster** [comment]
I think I messed up there. I'll try to get to the computer later today and fix it, but it could take a little longer too. The code is trivial, but I'm on some sort of holiday thing at home.

**Comment by wdecoster** [comment]
nanoget v1.13.1 has fixed code, thanks for reporting!

**Comment by tchrisboles** [comment]
Wouter, Thanks for your trouble last week. 
I updated NanoPlot through the conda update method this morning, and reran the analysis that previously crashed the application. This time NanoPlot didn't crash , but did still spew a slew of computer invective at my terminal. Log is attached. Is it running properly now?  (should I ignore the invective?)
Chris
[NanoPlot_20200601_1128.log](https://github.com/wdecoster/NanoPlot/files/4712331/NanoPlot_20200601_1128.log)

**Comment by wdecoster** [comment]
It's safe to ignore those messages. 

Some of the dynamic HTML plots can get very large, and to make it easier to quickly take a look at them also a static image (PNG) is created, but that requires additional dependencies (psutil, orca) which are more tricky to install on some systems and therefore not necessarily required for running NanoPlot.

Cheers,
Wouter

**Comment by tchrisboles** [comment]
OK, great. The plots now look fine (as usual) -- I just didn't understand the significance (or insignificance) of the messages. Thanks again.
