### ISSUE TITLE
BAM csi index

### ISSUE THREAD

**Issue by JasonDFiedler** [wdecoster/NanoPlot#184]
Large chromosomes require a .csi BAM index (instead of default .bai), please update to allow for this option.

**Comment by wdecoster** [comment]
Hi Jason,

Thank you for the nicely formulated request.

I've never had to use a .csi index, and all BAM parsing is handled using Pysam and not in NanoPlot itself. Did you get an error with your bam file? Please add some information.

Cheers,
Wouter

**Comment by JasonDFiedler** [comment]
If the BAM files are indexed beforehand (with csi), then there is no problem with plotting I should have checked that first. 
Thanks

**Comment by wdecoster** [comment]
You're most welcome.
