### ISSUE TITLE
barcoded stats from fastq

### ISSUE THREAD

**Issue by aspitaleri** [wdecoster/NanoPlot#188]
Hi,
--barcoded does not work using fastq.gz files but only with --summary. Could be possible to feed Nanoplot with a set of fastq.gz and get back a stats from each instead the overall?
So far the only way is going one by one in a loop.
Best

**Comment by wdecoster** [comment]
By default NanoPlot and NanoStat is going to merge all datasets you give it, so running it separately is what you would have to do to get a report for each barcode, You can get per-dataset stats in one go using NanoComp, which will not merge all datasets but keep them separate.

**Comment by aspitaleri** [comment]
okay! perfect. I forgot about NanoComp ...
Thanks again

**Comment by wdecoster** [comment]
Happy to help, let me know if there is anything else.
