### ISSUE TITLE
MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.

### ISSUE THREAD

**Issue by JoshLoecker** [wdecoster/NanoPlot#193]
When running NanoPlot, I get a warning that says `MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API`. In addition, this warning comes up when calling `NanoPlot --listcolormaps`.

**Comment by wdecoster** [comment]
Thanks for reporting this, I'll have a look.

**Comment by wdecoster** [comment]
This is solved in v1.32.2.

Please let me know if there is something else you encounter!

**Comment by iferres** [comment]
Hi, thanks for fixing this issue. Any clue of when the fix will be available in conda? The last available version there is 1.32.1.
