### ISSUE TITLE
barcoded summary

### ISSUE THREAD

**Issue by husamia** [wdecoster/NanoPlot#196]
What is the proper use of the --barcoded option with --summary?

**Comment by wdecoster** [comment]
If a sequencing_summary file contains the column `barcode_arrangement` (from Guppy demultiplexing) then NanoPlot with --barcoded will split the sequencing_summary based on the barcodes specified in that column.

**Comment by wdecoster** [comment]
Did that help?

**Comment by husamia** [comment]
Guppy demultiplexing is the guppy_barcoder?

**Comment by wdecoster** [comment]
Probably yes.

**Comment by husamia** [comment]
barcode_arrangement column is in the barcoding_summary.txt file

**Comment by wdecoster** [comment]
You can use the barcoding_summary.txt to modify the sequencing_summary.txt, there is a script in the repository here:
https://github.com/wdecoster/NanoPlot/blob/master/scripts/add_barcodes_to_summary.py

**Comment by husamia** [comment]
How do I run the script?

**Comment by wdecoster** [comment]
save the content of the script to e.g. `add_barcodes_to_summary.py` and execute as 
`python add_barcodes_to_summary.py sequencing_summary.txt barcoding_summary.txt`
The script will create a file called `barcoded_sequencing_summary.txt.gz`
