### ISSUE TITLE
ValueError: `bins` should be a positive integer

### ISSUE THREAD

**Issue by MMS413** [wdecoster/NanoPlot#198]
Hello,  I am using Python 3.7 via Spyder 3.3.6 (as part of the Anaconda suite) as part of a class I'm currently taking. (I'm new to Python, so I apologize in advance if the answer to resolving this error seems obvious.)
How do I move past this error?

import pandas
import numpy
import seaborn
import matplotlib.pyplot as plt
data = pandas.read_csv('classdata_pds.csv', low_memory=False)

sub2['PACKSPERMONTH']=sub2['NUMCIGMO_EST'] / 20
c12 = sub2.groupby('PACKSPERMONTH').size()
print(c12)

sub2['PACKCATEGORY']=pandas.cut(sub2.PACKSPERMONTH, 0, 5, 10, 20, 30, 147)

****# produced ValueError: `bins` should be a positive integer.**** 

Thank you

**Comment by wdecoster** [comment]
How is this related to NanoPlot?
