### ISSUE TITLE
open N50 issue in loglength plots

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [wdecoster/NanoPlot#2]
The N50 value in the loglength plots with outliers removed was off for me. Also the cumulative yield plots are wrong in both case (normal length and log) aka units on y-axis are not correct.

**Comment by BenjaminSchwessinger** [comment]
Also the all time plots vs Length and basecall quality seem to have issues with the x-axis. In regards to the length plot I am also confused about the y-axis.
thanks!

**Comment by wdecoster** [comment]
Hi Benjamin,

Thanks for the feedback. Do you mean the N50 was wrongly calculated, wrongly displayed or both? Note that the logging file also contains the calculated value. I've fixed something with the math earlier, I'm not sure which version you are using.

Regarding the time-based plots I've noticed something was wrong with the time/x axis, which I think I addressed in a recent update. Could you please check if updating to NanoPlot 0.10.0 (and more specifically the nanoplotter module 0.10.2) fixes those issues?

I'm essentially just getting my feet wet with writing scripts for others so I'm very thankful for your testing and reports of errors.

Cheers,
Wouter

**Comment by BenjaminSchwessinger** [comment]
Was using 0.9.2 and will have a look at the latest version 0.10.2 if this has similar issues.

Thanks for sharing all your programs they are really helpful and people at our MinION workshop here in Australia really liked them. More soon.

**Comment by wdecoster** [comment]
I think this one is probably solved, if you find any more issue please let me know!
