### ISSUE TITLE
installation issues: filenotfounderror

### ISSUE THREAD

**Issue by navtronius** [wdecoster/NanoPlot#208]
Hi, I am trying to install nanoplot, but I am running into installation issues:

(base) PS C:\Users\Navtron> pip install nanoplot
Collecting nanoplot
  Using cached NanoPlot-1.33.0.tar.gz (37 kB)
Collecting biopython
  Using cached biopython-1.78-cp37-cp37m-win_amd64.whl (2.3 MB)
Collecting pysam>0.10.0.0
  Using cached pysam-0.16.0.1.tar.gz (3.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Navtron\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Navtron\\AppData\\Local\\Temp\\pip-install-d088bxmj\\pysam\\setup.py'"'"'; __file__='"'"'C:\\Users\\Navtron\\AppData\\Local\\Temp\\pip-install-d088bxmj\\pysam\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Navtron\AppData\Local\Temp\pip-pip-egg-info-d4iiet40'
         cwd: C:\Users\Navtron\AppData\Local\Temp\pip-install-d088bxmj\pysam\
    Complete output (23 lines):
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Navtron\AppData\Local\Temp\pip-install-d088bxmj\pysam\setup.py", line 240, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\Navtron\AppData\Local\Temp\pip-install-d088bxmj\pysam\setup.py", line 68, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\Users\Navtron\Anaconda3\lib\subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "C:\Users\Navtron\Anaconda3\lib\subprocess.py", line 488, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\Navtron\Anaconda3\lib\subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "C:\Users\Navtron\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by navtronius** [comment]
Python v3.7.7
pip v20.2.3
setuptools v50.3.0

**Comment by wdecoster** [comment]
This is just default Windows and not WSL is it? Because on windows you have to use WSL.

**Comment by navtronius** [comment]
I just used a virtual env on my linux machine and it worked! Thanks

**Comment by wdecoster** [comment]
That's good to hear, thanks for th feedback!
