### ISSUE TITLE
barcodes numbers

### ISSUE THREAD

**Issue by pgtb** [wdecoster/NanoPlot#210]
Hi,

Not an issue but an improvement request.

Since sequencing summary contains (again) a "barcode arrangement" column it would be great if you can add a filtering option w/wo barcodes filter.
Moreover a report containing all same numbers and plots as usual but based on each barcodes and unclassified reads.

I know it will take time... I am just asking to Santa d^_^b

best

**Comment by wdecoster** [comment]
Hi,

Are you aware there is a `--barcoded` flag for barcoded summary files? If so, what would you like to see different?

Cheers,
Wouter

**Comment by pgtb** [comment]
Yes sorry I missed that…

Thank you

best

--
Christophe Boury
Assistant Ingénieur (Lab Geek)
Plateforme Genome Transcriptome de Bordeaux
[PGTB_Marie]
INRAE - UMR 1202 BIOGECO
69 route d'Arcachon
33612 Cestas - Pierroton
FRANCE
05.35.38.53.36
[Bloc-Logo-Signature-INRAE]
https://pgtb.cgfb.u-bordeaux.fr/
https://twitter.com/pgt_bordeaux

christophe.boury@inrae.fr<mailto:christophe.boury@inrae.fr> - pgtb@inrae.fr<mailto:pgtb@inrae.fr>

De : Wouter De Coster [mailto:notifications@github.com]
Envoyé : jeudi 1 octobre 2020 08:30
À : wdecoster/NanoPlot <NanoPlot@noreply.github.com>
Cc : pgtb <pgtb@inrae.fr>; Author <author@noreply.github.com>
Objet : Re: [wdecoster/NanoPlot] barcodes numbers (#210)


Hi,

Are you aware there is a --barcoded flag for barcoded summary files? If so, what would you like to see different?

Cheers,
Wouter

**Comment by wdecoster** [comment]
No problem! Let me know if there are other features you would like to see added!
