### ISSUE TITLE
Error: tsv source

### ISSUE THREAD

**Issue by zoeamaris** [wdecoster/NanoPlot#212]
Error:

If you read this then NanoPlot 1.32.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/gstore/home/amarisz/.conda/envs/py3_default/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/gstore/home/amarisz/.conda/envs/py3_default/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 77, in main
    settings["statsfile"] = [make_stats(datadf, settings, suffix="", tsv_stats=args.tsv_stats)]
  File "/gstore/home/amarisz/.conda/envs/py3_default/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 119, in make_stats
    as_tsv=tsv_stats)
TypeError: write_stats() got an unexpected keyword argument 'as_tsv'"

**Comment by wdecoster** [comment]
How did you install NanoPlot? Please try updating the nanomath submodule (`pip install nanomath -U`).

**Comment by zoeamaris** [comment]
I updated with "conda install -c bioconda nanoplot". 

I installed and this was the output:
"Collecting nanomath
  Downloading nanomath-1.0.1.tar.gz (17 kB)
Requirement already satisfied, skipping upgrade: pandas in ./.conda/envs/py3_default/lib/python3.6/site-packages (from nanomath) (1.1.2)
Requirement already satisfied, skipping upgrade: numpy>1.8 in ./.conda/envs/py3_default/lib/python3.6/site-packages (from nanomath) (1.16.1)
Collecting Python-Deprecated
  Downloading Python-Deprecated-1.1.0.tar.gz (2.9 kB)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in ./.conda/envs/py3_default/lib/python3.6/site-packages (from pandas->nanomath) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in ./.conda/envs/py3_default/lib/python3.6/site-packages (from pandas->nanomath) (2019.3)
Requirement already satisfied, skipping upgrade: six>=1.5 in ./.conda/envs/py3_default/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas->nanomath) (1.15.0)
Building wheels for collected packages: nanomath, Python-Deprecated
  Building wheel for nanomath (setup.py) ... done
  Created wheel for nanomath: filename=nanomath-1.0.1-py3-none-any.whl size=30515 sha256=cd6c01cf1410672a4ab92352d8a251e852517b255653286225be57f54df4bbcd
  Stored in directory: /gstore/home/amarisz/.cache/pip/wheels/7a/be/a2/a29eba37908c4933eb14732a36ebf56e3e447830a9b0e4534b
  Building wheel for Python-Deprecated (setup.py) ... done
  Created wheel for Python-Deprecated: filename=Python_Deprecated-1.1.0-py2.py3-none-any.whl size=3069 sha256=623fb8779918ab265e4bcb643d9a55013197f73843a9ef45ccaa8a46dbc0a0e4
  Stored in directory: /gstore/home/amarisz/.cache/pip/wheels/7b/77/f4/889fb222210030f42875d19bb55b64ea2b394428066fd3a6f4
Successfully built nanomath Python-Deprecated
Installing collected packages: Python-Deprecated, nanomath
  Attempting uninstall: nanomath
    Found existing installation: nanomath 0.23.1
    Uninstalling nanomath-0.23.1:
      Successfully uninstalled nanomath-0.23.1
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

nanoplot 1.32.1 requires pauvre==0.2.0, but you'll have pauvre 0.1924 which is incompatible.
Successfully installed Python-Deprecated-1.1.0 nanomath-1.0.1"

**Comment by wdecoster** [comment]
Seems you will have to update pauvre as well then. Sorry for the mess :-)

**Comment by wdecoster** [comment]
Did that solve your issue?
