### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 124: invalid start byte

### ISSUE THREAD

**Issue by Tipplynne** [wdecoster/NanoPlot#213]
Dear Wouter de Coster

Thank you for writing such amazing software and making it open source. 

I got an error message saying I should email you my log while trying to run your softwares yesterday.

I tried running both your nanostat and nanoplot softwares on our promethion reads and in our hpc that was recently updated. The software is locally installed to my user account but, I still need to explicitly run the software in python using the full path to my installation;

python /home/c/crystal/.local/lib/python3.6/site-packages/nanostat/NanoStat.py etc...

I had to reinstall numpy, and one or two other things but still end up with the error below. Python environment is 3.6. The out put 
NanoPlot_20201020_1113.log
[Nanoplot_log.txt](https://github.com/wdecoster/NanoPlot/files/5405951/Nanoplot_log.txt)

Please let me know what I can do to correct this?

Thanks and kind regards
Crystal

**Comment by wdecoster** [comment]
Hi Crystal,

Python complains about finding an unexpected weird character in the file (0x80 in bytes) which it can't encode to UTF-8.
Did you do anything with this fastq file before using NanoPlot/NanoStat? Or is it like this directly from the sequencer?
Do you think it would be possible to share the file with me?

Thanks,
Wouter

**Comment by Tipplynne** [comment]
Dear Wouter 
Thanks for getting back to me, I realised the problem was due to corruption of the promethion data (probably during compression or moving stuff around with our recent migration to the new server). Both nanostat and nanoplot are running now!
Thanks and kind regards
Crystal

**Comment by wdecoster** [comment]
Good to hear! Thanks for the feedback.
