### ISSUE TITLE
NanoPlot crash 

### ISSUE THREAD

**Issue by Maria-sdu** [wdecoster/NanoPlot#214]
[NanoPlot_20201021_1126.log](https://github.com/wdecoster/NanoPlot/files/5414847/NanoPlot_20201021_1126.log)

I am trying to run NanoPlot on data from MinION sequencing of cfDNA basecalled with Guppy. I have tried with sequencing summary text file and fastq file, but each time it crashes. I have updated NanoPlot, but that didn't help. 
I do get some plots out before it crashes but not all, any idea as to why it keeps crashing?

**Comment by wdecoster** [comment]
Hi,

The same problem is reported in https://github.com/wdecoster/NanoPlot/issues/201
Please downgrade seaborn to 0.10.1.

Wouter
