### ISSUE TITLE
NanoPlot crashed

### ISSUE THREAD

**Issue by satomitsuhashi** [wdecoster/NanoPlot#217]
Hi, 

I got this message when I ran NanoPlot for sequencing_summary.txt. 
I would be very much grateful if you could help. 

******************************************************
If you read this then NanoPlot has crashed :-(
Please try updating NanoPlot and see if that helps...
If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!
******************************************************

I tried updating but it did not help.

Log files are attached. 
[NanoPlot_20201209_1319.log](https://github.com/wdecoster/NanoPlot/files/5663600/NanoPlot_20201209_1319.log)
[NanoPlot_20201209_1322.log](https://github.com/wdecoster/NanoPlot/files/5663601/NanoPlot_20201209_1322.log)

Thank you very much for your help!

Best wishes,
Satomi

**Comment by wdecoster** [comment]
Hi Satomi,

Looks like a duplicate of https://github.com/wdecoster/NanoPlot/issues/201
Could you try downgrading your seaborn module to 0.10.1?

Regards,
Wouter

**Comment by satomitsuhashi** [comment]
Dear Wouter,

Sorry I have overlooked #201.. 
Downgrading seaborn worked. Thank you very much! 

Kind regards,
Satomi

**Comment by wdecoster** [comment]
Thanks for the feedback!
