### ISSUE TITLE
nanoplot failing due to BrokenProcessPool from futures library

### ISSUE THREAD

**Issue by danmckerricher** [wdecoster/NanoPlot#221]
Hi There,

I am hoping to get some guidance on this error that I've encountered while running Nanoplot:
[nanoplot-log-clean.txt](https://github.com/wdecoster/NanoPlot/files/5798876/nanoplot-log-clean.txt)

(some of the log file has been edited to anonymize)

Nanoplot normally works well for my team, and is now only failing with one particular sample/sequencing summary file.  The file is about 33% larger than another sequencing summary file that recently produced good nanoplot results.  On a hunch, I tried running Nanoplot with significantly more memory than usual (480G instead of 12GB) but we're still hitting the same error after a few minutes of runtime.

Any ideas what could cause this?  I'll do my best to provide any other details that could be useful!

**Comment by danmckerricher** [comment]
After some more searching I realize this may be similar or duplicate of #100

I'm running Nanoplot 1.19 and the sequencing summary file is 7.0G if that helps

**Comment by wdecoster** [comment]
Thanks for reporting this. Could you try if running NanoPlot with --huge makes a difference here? In addition to this log file, are there other errors printed to stdout?

**Comment by danmckerricher** [comment]
Hello,

I tried with "--huge" but that seemed to be an unrecognized argument.

I also previously saw this from stdout:
[nanoplot-log-out-clean.txt](https://github.com/wdecoster/NanoPlot/files/5804422/nanoplot-log-out-clean.txt)

Thanks for your help!

**Comment by wdecoster** [comment]
I see you are using a fairly old version, which may not have --huge yet. Is updating an option?

**Comment by danmckerricher** [comment]
Thanks.  I didn't realize it was old, but now I see there is a version 1.33 already.

I will try updating.

**Comment by danmckerricher** [comment]
Hi again,

I'm happy to say that upgrading appears to have worked!  Thanks again for your help
