### ISSUE TITLE
Enhancement: Add run info to HTML reports.

### ISSUE THREAD

**Issue by kubu4** [wdecoster/NanoPlot#224]
Thanks for putting this program together and continuing to work on it. It's really nice!

I think it would be useful to have run info in the HTML report to make it a bit easier to identify which samples were processed in a given run.

For example, if I have multiple browser tabs open to view the HTML reports from multiple runs, there is no identifying info within the reports to indicate which sample(s) I'm actually viewing.

Along these lines, it'd be a nice bonus if some of the HTML reports also included some additional sample-specific info (maybe just in the summary table?) including reads, N50, total bases, etc.

**Comment by wdecoster** [comment]
Hi,

Thanks for the suggestion! Always looking for ways on how to improve NanoPlot. I have two follow-up questions:

> For example, if I have multiple browser tabs open to view the HTML reports from multiple runs, there is no identifying info within the reports to indicate which sample(s) I'm actually viewing.

Conceptually, would you like to have an option on the command line to add a `--html-comment` or how would you prefer this info to get transferred to the HTML?

> Along these lines, it'd be a nice bonus if some of the HTML reports also included some additional sample-specific info (maybe just in the summary table?) including reads, N50, total bases, etc.

Hmm which additional info do you have in mind? N50, total bases, etc should be there already?

Cheers,
Wouter

**Comment by kubu4** [comment]
> Conceptually, would you like to have an option on the command line to add a --html-comment or how would you prefer this info to get transferred to the HTML?

I was just thinking it be the default behavior. Could be disabled via argument.

> N50, total bases, etc should be there already?

They _are_ there (as a summary of the _combined_ data), but just not for each individual FastQ (assuming multiple FastQs were provided to NanoPlot).

Here's an example of a report (screenshot):

![image](https://user-images.githubusercontent.com/4514104/106802852-5d918c00-6618-11eb-923b-35828f1011da.png)


Here are questions I have when looking at this:

- How was report generated (from summary file, from FastQs, etc)?
- If FastQs, which FastQs?
- If FastQs, how many reads, bases, N50, etc were present in each FastQ

Of course, I know some of the answers (since I ran the command), but if I was to share this report with colleagues, it'd be killer if they had more granular info about what files contributed to the report. That would allow them to notice things (like, what if I accidentally forgot one of the FastQs that was part of the experiment?) and evaluate the plots more critically.

**Comment by wdecoster** [comment]
Aha, that makes sense. For the third point ("If FastQs, how many reads, bases, N50, etc were present in each FastQ") you might be interested in [NanoComp](https://github.com/wdecoster/nanocomp), which is made to compare across files).

**Comment by wdecoster** [comment]
I have just implemented this, and v1.34.0 will have a `--info_in_report` option and is now available through pip. Feedback appreciated!

**Comment by kubu4** [comment]
Whoa! Cool! Thanks for the work on this!
