### ISSUE TITLE
Is there a way to force same axes lengths when processing multiple samples?

### ISSUE THREAD

**Issue by bhargava-morampalli** [wdecoster/NanoPlot#227]
This is a question rather than an issue. I am using the Nanoplot in a pipeline and when comparing results/figures from replicates, I find that the axes are different lengths. This is based on the data I guess but is there a way to make the axes similar across the samples? This makes it easier to compare across the samples. I can take the pickle files for these samples and can do the analysis but was wondering if there is something in the Nanoplot itself.
If there is not, is there a command which I can use just to get the pickle file containing raw data without the figures?

**Comment by wdecoster** [comment]
Hi,

Thanks for your question. Admittedly, there is currently no great way in NanoPlot to do this.
A few suggestions can be found in this thread: https://github.com/wdecoster/NanoPlot/issues/137

But if you want to compare multiple samples, I would first suggest looking at https://github.com/wdecoster/nanocomp

Cheers,
Wouter

**Comment by bhargava-morampalli** [comment]
Ah, okay. Nanocomp is the one that I need I think. 
Thanks Wouter for your excellent packages!!
