### ISSUE TITLE
Feature suggestion: fixed axis limits for plots

### ISSUE THREAD

**Issue by pretsnor** [wdecoster/NanoPlot#229]
Hi all,

Thanks for developing this set of tools: they're super useful.

I am using NanoPlot to produce read length / mean quality biplots of 96 demultiplexed ONT datasets. They are very useful to visualise differences in quality/read length between different barcodes, however, two given plots are not always directly comparable because the axis (of especially the quality scores) are determined automatically by the max values of the quality scores and read lengths:

I suspect the following lines in `nanoplotter_main.py` are responsible:

```python
maxvalx = xmax or np.amax(x)
maxvaly = ymax or np.amax(y)
```

I'm sure I could export all raw data using the `--raw` flag, and then make the plots myself, but having the option to specify your axis limits would be very useful. As the plotting functions has potential arguments `xmax` and `ymax`, implementation should be straightforward.

**Comment by wdecoster** [comment]
Hi,

Thanks for your suggestion.  Have you checked if [NanoComp](https://github.com/wdecoster/nanocomp) helps you compare barcodes in your case?

Cheers,
Wouter

**Comment by pretsnor** [comment]
Hi,

Thanks for pointing me to NanoComp, I will give it a try!

**Comment by wdecoster** [comment]
Let me know if there are features that you are missing.
