### ISSUE TITLE
bonito support

### ISSUE THREAD

**Issue by aspitaleri** [wdecoster/NanoPlot#230]
Hi
still great ever tool!
Do you plan to support bonito summary tsv output from basecalling?

**Comment by wdecoster** [comment]
I have no idea how that looks like, if you can share an example I can have a look.

**Comment by aspitaleri** [comment]
the output is a tsv like this:
```
filename	read_id	run_id	channel	mux	start_time	duration	template_start	template_duration	sequence_length_template	mean_qscore_template
FAF17394_44855949_94.fast5	0017323b-af02-4832-afdb-3a91ae540b4d	44855949b830beb3a211cf87665ad44976228ba3	147	1	65109.156	31.903	65109.156	31.903	5910	0.0

```

**Comment by wdecoster** [comment]
That looks a lot like a guppy summary file, but I guess you tested already if NanoPlot works with the bonito summary?

**Comment by aspitaleri** [comment]
actually I didn't yet. I will.

**Comment by aspitaleri** [comment]
NanoPlot --summary basecalls_summary.tsv.gz -o summary-plots-log --loglength --N50
it worked as a charm!

**Comment by wdecoster** [comment]
Good to hear.
