### ISSUE TITLE
NanoPlot crash with a small file containing a few whales

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#231]
Hi Wouter, 
We're trying a new sample prep aimed at long reads. I created a new AWS instance (ubuntu) and installed minimap2, samtools, and Nanoplot using conda. The fast-basecalled passed output was not large (2 fastq's total about 760mbytes), but there are a good number of very long reads (>700kb, some 1Mb reads). I ran minimap2 with the -L option because of this. Minknow thought the N50 readlength is 160kb.

Caution: I used the fast-basecaller on the minit only. (I know -lazy - but I just wanted to see if the long reads were total junk.)

Hope you are weathering the pandemic in good health and tolerable good spirits.
Chris
[NanoPlot_20210305_2012.log](https://github.com/wdecoster/NanoPlot/files/6093267/NanoPlot_20210305_2012.log)
![Nanoplot_crash_screen](https://user-images.githubusercontent.com/33500125/110171000-032b4d00-7dc9-11eb-8498-caed26a543b2.PNG)

**Comment by wdecoster** [comment]
Hi Chris,

Hope to catch up with you at some conference as soon that is possible again.

Sorry for the inconvenience here, this seems to be the same problem as https://github.com/wdecoster/NanoPlot/issues/201. Downgrading seaborn should fix it.

I'm having some trouble updating the bioconda recipe to take care of that incompatibility, I should really look into that soon...

Hope that helps,
Wouter

**Comment by wdecoster** [comment]
Hi Chris,

Please let me know if this has to be reopened!

Thanks,
Wouter
