### ISSUE TITLE
cannot install using conda

### ISSUE THREAD

**Issue by akshayMpatel** [wdecoster/NanoPlot#234]
$ conda install -c bioconda nanoplot
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                             

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by wdecoster** [comment]
This doesn't look like an issue specific to NanoPlot, but rather something about your conda setup. Please try by installing in a fresh environment using `conda create -n nanoplot -c bioconda nanoplot`

**Comment by akshayMpatel** [comment]
Okay this worked, but I suppose it usually only works within its own environment?

**Comment by wdecoster** [comment]
Glad to hear this worked! It probably depends on how much you have already installed in your base environment.
