### ISSUE TITLE
Conda installation problem

### ISSUE THREAD

**Issue by kokyriakidis** [wdecoster/NanoPlot#236]
Hey @wdecoster ,

I have trouble installing you tool through conda. First I tried to install in MacOS (using it inside a snakemake workflow) but it failed. I thought it may be a OS problem. Then I tried to install it on a new python 3.6.10 conda environment in an Ubuntu system. It failed again.

The command I used is:
```
conda install -c bioconda nanoplot

``` 
Do you have any clue about this issue?

**Comment by wdecoster** [comment]
Hi kokyriakidis,

And what is the error you are getting?

Wouter

**Comment by kokyriakidis** [comment]
(nanoplot) kokyriakidis@XAROS-WORKSTATION:~$ conda install -c bioconda nanoplot
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

**Comment by wdecoster** [comment]
This doesn't look like an issue specific to NanoPlot, but rather something about your conda setup. Please try by installing in a fresh environment using `conda create -n nanoplot -c bioconda nanoplot`
