### ISSUE TITLE
ERROR: expected columns in summary file sequencing_summary.txt not found after updates of minKNOW

### ISSUE THREAD

**Issue by stevebaeyen** [wdecoster/NanoPlot#240]
after this command: 
`
![afbeelding](https://user-images.githubusercontent.com/4630854/111637646-ebf15400-87f9-11eb-8f40-335a8a63ab67.png), I get this error:

![afbeelding](https://user-images.githubusercontent.com/4630854/111637697-f9a6d980-87f9-11eb-8827-4f2624181a9e.png)
the first row is:
filename_fastq	filename_fast5	read_id	run_id	channel	mux	start_time	duration	pore_type	experiment_id	sample_id	end_reason

**Comment by wdecoster** [comment]
Confusingly, there are two types of sequencing summary files created. This is one generated during the actual sequencing but does not include information about the basecalling (read lengths, qualities).

**Comment by stevebaeyen** [comment]
Thanks for your fast reply! Indeed, the basecalling itself was done on another PC than the one used for sequencing... will search for the good file. In the meantime, i ran NanoPlot on the fastq files.
