### ISSUE TITLE
Key Error: missing labels

### ISSUE THREAD

**Issue by mondevert0815** [wdecoster/NanoPlot#248]
Hello, I'm trying to run NanoPlot with a guppy fastq input file using python 3.6.3 . I need guidance on how to get around this key error: 
[merged_TestDataNanoPlot_20210331_2046.log](https://github.com/wdecoster/NanoPlot/files/6240685/merged_TestDataNanoPlot_20210331_2046.log)

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Int64Index([474354, 481881, 477885, 459626, 453807,\n            ...\n            459285, 466919, 470205, 479761, 476156],\n           dtype='int64', length=57). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

I have attached the log file. Thanks!

**Comment by wdecoster** [comment]
Thanks for reporting this! @iliasbukraa is this the one you solved earlier? I probably have to push that one

**Comment by iliasbukraa** [comment]
yes this should have been fixed in the latest fix!

**Comment by wdecoster** [comment]
Hi @mondevert0815 please try installing the latest NanoPlot version, which is v1.35.2 and available on PyPI now :-)

**Comment by mondevert0815** [comment]
Hello, thank you for your help. I've attempted to pip upgrade to either NanoPlot-1.35.3 or NanoPlot-1.35.2 for both python 3.6 and python 3.9, but receive the same error with all attempts: error: package directory 'extra' does not exist . I am using pip version 21.0.1 .

**Comment by wdecoster** [comment]
Should be fixed with NanoPlot-1.35.4!

**Comment by mondevert0815** [comment]
It works great now. Thank you for your help!
