### ISSUE TITLE
Output NanoStats_post_filtering.txt if any filtering is chosen on CLI

### ISSUE THREAD

**Issue by bernt-matthias** [wdecoster/NanoPlot#259]
For using Nanoplot in workflows it would be handy if the presence of `NanoStats_post_filtering.txt` would be predictable from the command line parameters, i.e. independent if anything was filtered. 

Currently one check is `num_reads_prior - num_reads_post > 0`

But for instance `maxlength` and `minlength` do not trigger the file creation.

**Comment by wdecoster** [comment]
Hi @bernt-matthias,

Yes, I understand that's not fully clear and a source of confusion. The difference between these settings is that some 'filters' only hide reads in the read-length plots that are too long, without actually removing them for e.g. quality plots or yield plots.

What is your preferred solution?

Wouter

**Comment by bernt-matthias** [comment]
OK got it. I guess then it just needs to be documented somewhere.
