### ISSUE TITLE
read length axis

### ISSUE THREAD

**Issue by paulojt** [wdecoster/NanoPlot#26]
It seems that the axis of the density plot on the top is "out-of-sync"  with with the one of main plot? Is this a known issue?
I'm using NanoPlot 1.2.2.

![log_lengthvsqualityscatterplot_kde 2](https://user-images.githubusercontent.com/14118994/32619901-0dcc2742-c54a-11e7-8fb6-9fff2ed06f60.png)

**Comment by wdecoster** [comment]
That looks indeed really strange. Which figure format did you select? Could you share the log file, and perhaps the data you used?

**Comment by paulojt** [comment]
Thanks for the quick reply.
See the log file attached.
I'll email you the sequencing_summary.txt that I used as input.
[NanoPlot_20171109_1336.log](https://github.com/wdecoster/NanoPlot/files/1458862/NanoPlot_20171109_1336.log)

**Comment by wdecoster** [comment]
Thanks. The issue replicates here on my computer. Interesting...

I'll try a few things today, but it's possible that it will take a few days since I'm on holiday this weekend.

**Comment by paulojt** [comment]
I noticed that a figure you posted recently in a different thread also seem to have this issue (although more subtle with that dataset).
https://github.com/wdecoster/NanoPlot/issues/15

Thanks

**Comment by wdecoster** [comment]
Good catch. Thanks for reporting this!

**Comment by wdecoster** [comment]
This turned out to be reasonably straightforward and should be fixed if you update nanoplotter to v0.24.1 using `pip install nanoplotter -U`

Can you confirm it's corrected now?

Please let me know if you come across other issues or have suggestions/feature requests!

**Comment by paulojt** [comment]
Yes, I confirm the problem is fixed.
NanoPlot is a great tool. Thanks!
