### ISSUE TITLE
Help with plot descriptions 

### ISSUE THREAD

**Issue by utritala** [wdecoster/NanoPlot#261]
Hi, Why is the dynamic read length histogram plotted for a downsampled number of reads? What are the read lengths normalised by in the "Normalised histogram of read lengths" plot? I am using NanoPlot v1.34.1
Thanks.

**Comment by wdecoster** [comment]
Downsampling is done to make sure plots are generated quickly, load quickly in your browser, and don't take up too much space on your hard drive or as an attachment. By downsampling to 10000 reads, we believe the distribution will still be representative of the full dataset. 

Where did you see the Normalised histogram of read lengths? In NanoComp? Or do you mean the 'weighted' histograms?

**Comment by utritala** [comment]
Thank you so much for your prompt response. Very helpful!

Sorry, yes, I meant Normalised histogram of read lengths in NanoComp.

Thanks again.

**Comment by wdecoster** [comment]
The normalised histogram in Nanocomp corrects for differences in the number of reads between the datasets.
If one dataset has ten times more reads as the other dataset it becomes harder to look at differences in library length, unless you normalise.

**Comment by utritala** [comment]
Gotcha! Thanks again. :)

**Comment by wdecoster** [comment]
Glad to help, let me know if anything else is unclear. I should really update the documentation :-(
