### ISSUE TITLE
Format of output figures

### ISSUE THREAD

**Issue by rivera10** [wdecoster/NanoPlot#262]
Hello,

I was running the tool and I got this error
```
NanoPlot: error: unrecognized arguments: -f pdf
```
I am using NanoPlot 1.36.2. Does this version removes the `--format` argument? It is not listed in the help as in other versions. 

Thanks for such great tool. 

Best,
Ramon

**Comment by iliasbukraa** [comment]
Hi @rivera10, thank you for your trust in Nanoplot! The -f/--format option has been temporarily disabled, maybe @wdecoster can expand on what the next steps are for outputting results?

**Comment by wdecoster** [comment]
Yes, we should bring this option back, and that shouldn't be too hard.

**Comment by rivera10** [comment]
Great, thanks!
