### ISSUE TITLE
Support for .sam output produced by Albacore

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#27]
Just getting starting with analysis of Nanopore runs, so this a beginner question. 

My understanding is that Albacore can perform minmap2 alignments directly, if provided with the proper index file. 

Can Nanoplot accept the .sam output files from Albacore directly, as it does .bam aligment files from other aligners.

Chris

**Comment by wdecoster** [comment]
Thanks for your suggestion. I don't immediately  see an added value of keeping sam files, as they take more storage space. So I convert directly to bam. That said I haven't tried if --bam also accepts sam files. I can try next week, not at home this weekend. 

If necessary I can add a sam mode, for sure.

**Comment by tchrisboles** [comment]
Oh ok. Do I understand that Nanoplot directly converts the sam output from the minimap2 alignment performed by Albacore into bam output for your plots?

Thanks again.
(I like your plots!)
Chris

**Comment by wdecoster** [comment]
No, you would have to use samtools for that, e.g.:
`samtools sort -o alignment.bam alignment.sam`. Note that most tools, including NanoPlot, expect sam/bam files to be sorted.

As far as I know there is no reason not to convert to bam.

**Comment by tchrisboles** [comment]
Thanks.

**Comment by wdecoster** [comment]
Glad to help, please let me know if you encounter issues, or have other suggestions or feature requests.
