### ISSUE TITLE
PDFs of read length histograms contain "Loading [MathJax]/extensions/MathMenu.js" message

### ISSUE THREAD

**Issue by thallinger** [wdecoster/NanoPlot#274]
All read length histogram PDFs  generated by NanoPlot 1.38.1 contain the message "Loading [MathJax]/extensions/MathMenu.js" at the bottom of the plot.
As an example here the WeightedHistogrammReadLength plot:
![WeightedHistogramReadlength](https://user-images.githubusercontent.com/31136605/137131950-902cfb87-484f-41f2-9d40-9ebaeb93ed11.png)

This is not the case for Yield-, DOT-, and KDE plots.

**Comment by thallinger** [comment]
Any ideas how this can be avoided?

**Comment by wdecoster** [comment]
Absolutely no idea actually. It seems not related to code that I have written, and probably originates from the plotly package.
