### ISSUE TITLE
Some of the plots generated seems a bit weird...

### ISSUE THREAD

**Issue by adhamzul** [wdecoster/NanoPlot#279]
For the first time in a while, I wanted to do some tests on some of my earlier sequences.
I installed NanoPlot through conda, and I also made sure it was up-to-date.

When I run the following code,

`NanoPlot -o nanoplot_raw --readtype 1D --fastq 20210308_barcode06.fastq.gz --loglength -t 8`

and I check the plots generated, some of the plots generated looked odd. And it is only visually,
as the data points are accurate. Especially the KDE scatter plot.

It is not a massively urgent issue, but it seems to be bugging some people, and I totally get it...

I'm attaching the log file, and the plots produced.

Thank you very much for the great work!

Sincerely,
Adham

![LengthvsQualityScatterPlot_dot](https://user-images.githubusercontent.com/83048822/141073324-d267d43b-334b-4c6a-b391-0685b7a4e634.png)
![LengthvsQualityScatterPlot_kde](https://user-images.githubusercontent.com/83048822/141073327-38cc5324-98a1-4440-97d9-7b591aaf5805.png)
![LengthvsQualityScatterPlot_loglength_dot](https://user-images.githubusercontent.com/83048822/141073331-510b9ee6-7725-42a6-94aa-c50b363b8eab.png)
![LengthvsQualityScatterPlot_loglength_kde](https://user-images.githubusercontent.com/83048822/141073334-c1aa8906-b20d-43b8-9515-5a4d82e192c4.png)
![Non_weightedLogTransformed_HistogramReadlength](https://user-images.githubusercontent.com/83048822/141073337-82664aa9-adb4-475a-8576-dc51f64db0b6.png)
![WeightedHistogramReadlength](https://user-images.githubusercontent.com/83048822/141073341-f3ad1d52-185d-4ab7-9450-76cfe4cfa446.png)
![Yield_By_Length](https://user-images.githubusercontent.com/83048822/141073344-2c6854eb-9832-4c03-8328-6ec7031e8dcd.png)
[NanoPlot_20211110_1638.log](https://github.com/wdecoster/NanoPlot/files/7510863/NanoPlot_20211110_1638.log)

**Comment by wdecoster** [comment]
Can you elaborate on "the plots generated looked odd"? What did you expect to see instead? The KDE plots are indeed weirdly stretched horizontally, not sure on how to fix that, but what is wrong with the histogram of read lengths and the yield by length plot?

**Comment by adhamzul** [comment]
Hello Wouter,

Thank you for the response. It's mainly about how the KDE plots are stretched horizontally, 
but also on the point that both histograms of read lengths only have a vertical grid line.

Sorry for the unclear wording.

Regards,
Adham

**Comment by wdecoster** [comment]
Personally I am not so bothered by only having vertical grid lines (happy to get more opinions though), but yes those KDE plots don't look nice at all.
I have changed some code, and they should be more squared in v1.38.2, which will soon be available through the usual channels.

**Comment by adhamzul** [comment]
Good morning Wouter,

I cannot express how grateful I am!
Thank you very much for the responses!

Will update NanoPlot soon.

Best wishes,
Adham
