### ISSUE TITLE
annotation on plots?

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#28]
How do I have the input file name (or some annotation as to the source of the data) printed somewhere on the plots?

Chris

**Comment by wdecoster** [comment]
Hi Chris,

There is currently no option for that. It could be possible to add that feature, if that would be beneficial for you.

Note that you can use `--prefix`/`-p` to add a string to the name of the output files, or `--outdir`/`-o` to create a directory for your plots. In both the directory and prefix you could add the source name.

Cheers,
Wouter

**Comment by tchrisboles** [comment]
Yes that --prefix option is helpful. But I am printing lots of plots to
share them with my coworkers, so it seems silly to be hand-printing the
data file names on the printouts.

Maybe some option to allow the --prefix to appear alongside the plot....?

Thanks,

Chris

Best regards,

Chris Boles, Ph.D, Chief Scientific Officer
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
chris.boles@sagescience.com

This e-mail may contain information that is confidential or privileged. If
you are not the intended recipient, do not read, copy or distribute the
e-mail or any attachments. Instead, please notify the sender and delete the
e-mail and any attachments. Thank you.

On Tue, Nov 14, 2017 at 11:36 AM, Wouter De Coster <notifications@github.com

**Comment by wdecoster** [comment]
I'll think about this!

Note that you can also aggregate all plots in a html report using `--report`. That might be easier to share with your coworkers...

**Comment by tchrisboles** [comment]
Yes - I'll try that.

But I still like to spread out a bunch of charts on a big table and
classify them by hand (an scribble  on them).

(In addition, I confess that I hate my laptop - so I often carry paper
printouts to meetings .)

Thanks,
Chris

Best regards,

Chris Boles, Ph.D, Chief Scientific Officer
Sage Science, Inc., 500 Cummings Center, Suite 2400, Beverly, MA 01915
Direct Office: +1-978-522-6284, Mobile: +1-781-856-2165
Company: +1-978-922-1832
chris.boles@sagescience.com

This e-mail may contain information that is confidential or privileged. If
you are not the intended recipient, do not read, copy or distribute the
e-mail or any attachments. Instead, please notify the sender and delete the
e-mail and any attachments. Thank you.

On Tue, Nov 14, 2017 at 12:07 PM, Wouter De Coster <notifications@github.com

**Comment by wdecoster** [comment]
Hi Chris,

Seems like you have good arguments for this feature, I'll probably implement it tomorrow.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Turns out I still had some time left today, so I already added your request.

NanoPlot 1.3.0 has a --title argument, allowing you to set a common title to all plots. If the --title argument is not specified, a default title (specific per plot type) is used.

Is this a solution to your request?

**Comment by tchrisboles** [comment]
Yes this will work. thanks.
