### ISSUE TITLE
Nanoplot histgrams has minus bars

### ISSUE THREAD

**Issue by khoriba** [wdecoster/NanoPlot#288]
Hi,
I used Nanoplot for my MinION seq data as follows.
```$ NanoPlot --fastq B01.fq --loglength -t 8 -o B01_np```
Then I got histgrams with minus bars in "weight histogram of read length" and "weight histogram of read length after log transformation".
This Nanoplot was installed using miniconda. Afterward, the version of seaborn was dropped to 0.10.0 to avoid errors. The other nanopore output data is outputting "normally". What are the possible reasons?
![b01](https://user-images.githubusercontent.com/45022668/156141650-065993b2-a9da-425d-a472-6d3472a94be5.png)

**Comment by wdecoster** [comment]
This is most unexpected. Can you tell me which version of NanoPlot you have?
It seems outdated, as current plots are produced with plotly and look a bit different.

**Comment by khoriba** [comment]
Thank you for your reply.

$ NanoPlot -v
NanoPlot 1.20.0

**Comment by wdecoster** [comment]
The most recent version on PyPI (pip) and conda is v1.39.0, could you try upgrading?

**Comment by khoriba** [comment]
I finally got the latest version.
Unfortunately, I couldn't get the latest Nanoplot without specifying the version.
It looks like a normal graph has been created with v1.39.0. Thank you!!
![WeightedHistogramReadlength](https://user-images.githubusercontent.com/45022668/156151429-36168b71-a690-4f22-a5fe-f027ba91593e.png)
!

**Comment by wdecoster** [comment]
Thank you for the feedback!
