### ISSUE TITLE
problem after conda installation

### ISSUE THREAD

**Issue by matt-shenton** [wdecoster/NanoPlot#290]
Hi there
I created an environment:
conda create -n nanoplot -c bioconda nanoplot

` conda activate nanoplot`

`(nanoplot) $ NanoPlot -h
Traceback (most recent call last):
  File "/lustre/home/mshenton/anaconda3/envs/nanoplot/bin/NanoPlot", line 6, in <module>
    from nanoplot.NanoPlot import main
  File "/lustre/home/mshenton/anaconda3/envs/nanoplot/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 20, in <module>
    import nanoplot.report as report
  File "/lustre/home/mshenton/anaconda3/envs/nanoplot/lib/python3.5/site-packages/nanoplot/report.py", line 106
    html_info.append(f"{k}:\t{settings[k]}<br>")
                                              ^
SyntaxError: invalid syntax
`
Is this about my environment, or conda setup?
Here's what's in the environment. Thanks for any help
Cheers
Matt

`name: nanoplot
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - arrow-cpp=0.9.0=py35h165c0fa_7
  - bcftools=1.8=h4da6232_3
  - biopython=1.68=py35_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.3.18=h06a4308_0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - curl=7.71.1=h8f29fe8_2
  - deprecated=1.2.12=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.13.1=h6c09931_0
  - fonts-conda-forge=1=0
  - freetype=2.11.0=h70c0345_0
  - htslib=1.7=0
  - icu=58.2=he6710b0_3
  - intel-openmp=2022.0.1=h06a4308_3633
  - jpeg=9d=h7f8727e_0
  - kaleido-core=0.2.1=h3644ca4_0
  - krb5=1.19.2=hac12032_0
  - libboost=1.65.1=habcd387_4
  - libcurl=7.71.1=h303737a_2
  - libdeflate=1.2=h516909a_1
  - libedit=3.1.20210910=h7f8727e_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.5.2=h6f1eeef_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h7f8727e_2
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.8.1.2=h14c3975_0
  - mathjax=2.7.7=0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - mmtf-python=1.0.2=py35_0
  - msgpack-python=0.5.6=py35h6bb024c_1
  - nanoget=1.16.1=py_0
  - nanomath=1.2.1=pyhdfd78af_0
  - nanoplot=1.36.1=pyhdfd78af_0
  - ncurses=6.3=h7f8727e_2
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numpy=1.15.2=py35h1d66e8a_0
  - numpy-base=1.15.2=py35h81de0dd_0
  - olefile=0.46=py35_0
  - openssl=1.1.1n=h7f8727e_0
  - pandas=0.23.4=py35h04863e7_0
  - parquet-cpp=1.4.0=h3238a2a_0
  - pillow=5.2.0=py35heded4f4_0
  - pip=10.0.1=py35_0
  - plotly=4.14.3=pyhd3eb1b0_0
  - pyarrow=0.9.0=py35hfc40096_2
  - pysam=0.14.1=py35hae42fb6_1
  - python=3.5.6=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - reportlab=3.5.6=py35he686d34_0
  - retrying=1.3.3=py35_2
  - samtools=1.7=1
  - scipy=1.1.0=py35hfa4b5c9_1
  - setuptools=40.2.0=py35_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.8=he6710b0_0
  - sqlite=3.38.0=hc218d9a_0
  - tbb=2021.5.0=hd09550d_0
  - tbb4py=2018.0.5=py35h6bb024c_0
  - thrift-cpp=0.11.0=h02b749d_3
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.10.11=py35h14c3975_2
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.3.3=h84994c4_0
prefix: /lustre/home/mshenton/anaconda3/envs/nanoplot
`

**Comment by wdecoster** [comment]
Hi,

NanoPlot requires minimally python 3.6, so that is most likely the cause of this error.

Best,
Wouter

**Comment by matt-shenton** [comment]
Thanks for checking it out. I am not sure why my conda setup chose python 3.5 for this environment, the base one is 3.7. Anyway, I think this is a conda issue for me to investigate.

Thanks again for the tool and your help.

Best wishes
Matt
