### ISSUE TITLE
TypeError: get_input() got an unexpected keyword argument 'keep_supp'

### ISSUE THREAD

**Issue by os103** [wdecoster/NanoPlot#291]
Hi, 

I get the following error message when running nano plot. I installed via conda and have tried 'conda upgrade NanoPlot'. 

Thanks!
Orie

> If you read this then NanoPlot 1.39.0 has crashed :-(
> Please try updating NanoPlot and see if that helps...
> 
> If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
> If you could include the log file that would be really helpful.
> Thanks!
> 
> 
> 
> Traceback (most recent call last):
>   File "/home/o/os103/miniconda3/envs/nanoplot-venv/bin/NanoPlot", line 10, in <module>
>     sys.exit(main())
>   File "/home/o/os103/miniconda3/envs/nanoplot-venv/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 67, in main
>     keep_supp=not (args.no_supplementary))
> TypeError: get_input() got an unexpected keyword argument 'keep_supp'

**Comment by os103** [comment]
I did see an earlier post where someone had a similar problem resolved via upgrading nano get. I tried that last night and it didn’t work. I’ve just tried it again but from within the nano plot virtual environment I’ve created (I don’t know if this will make a difference, I’m a novice with command line). I got the following output after the update but still NanoPlot is giving the same error.

***@***.*** ~]$ conda activate nanoplot-venv
(nanoplot-venv) ***@***.*** ~]$ conda upgrade nanoget
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/o/os103/miniconda3/envs/nanoplot-venv

  added / updated specs:
    - nanoget


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nss-3.77                   |       h2350873_0         2.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.1 MB

The following packages will be UPDATED:

  nss                                       3.76-h2350873_0 --> 3.77-h2350873_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
nss-3.77             | 2.1 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(nanoplot-venv) ***@***.*** fastq_reads]$ NanoPlot --fastq 12-sample-no-bead-1-cat.fastq



If you read this then NanoPlot 1.39.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!



Traceback (most recent call last):
  File "/home/o/os103/miniconda3/envs/nanoplot-venv/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/home/o/os103/miniconda3/envs/nanoplot-venv/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 67, in main
    keep_supp=not (args.no_supplementary))
TypeError: get_input() got an unexpected keyword argument 'keep_supp'
(nanoplot-venv) ***@***.*** fastq_reads]$



On 31 Mar 2022, at 21:36, Wouter De Coster ***@***.******@***.***>> wrote:



Can you try upgrading the nanoget module using conda?

**Comment by wdecoster** [comment]
Hmm, remarkable. Could it be that there is an older nanoget module that somehow gets precedence?
You could try `python -c "import nanoget ;  print(nanoget.__version__)"` and see if that matches with what you recently installed.

Maybe `pip uninstall nanoget` will remove an older installation.
