### ISSUE TITLE
Support for multi-format output figures

### ISSUE THREAD

**Issue by AyanoClarke** [wdecoster/NanoPlot#292]
Hi,

I can only get one format of plots via the current version of NanoPlot with option `-f`. However, I need to get multiple format plots, png, eps, png, and so on. The way I am doing is using ImageMagick to convert the plots, which is not convenient and sometimes not pretty.

Is there a way to make `--format` option accept multiple values?

**Comment by wdecoster** [comment]
Hi, thanks for the suggestion. This is now supported in NanoPlot v1.40, available on PyPI and soon also on bioconda.

**Comment by AyanoClarke** [comment]
Thanks for the update.
