### ISSUE TITLE
NanoPlot web service input size requirement is a bit small

### ISSUE THREAD

**Issue by ZarulHanifah** [wdecoster/NanoPlot#295]
Hello wdecoster,

Thank you for the wonderful software. I intend to use the web service version, but my summary file is slightly bigger than 100 Mb (131 Mb). I am using an arm64 device, so I don't think I can do it the CLI way. Is it possible if we can allow a bigger input file size for the web service version please?

Thank you.

**Comment by wdecoster** [comment]
Hmm, I don't think that is something we are planning to do.

>  I am using an arm64 device, so I don't think I can do it the CLI way.

Did you try?

**Comment by ZarulHanifah** [comment]
I can't install it on my device. Some python software installation failure happened.

**Comment by wdecoster** [comment]
Hold on let me take my crystal ball and take a look at your error message.
