### ISSUE TITLE
Is there a way just to extract raw data - pickle and tsv format?

### ISSUE THREAD

**Issue by bhargava-morampalli** [wdecoster/NanoPlot#298]
I am trying to include the nanoplot in a nextflow pipeline. For one of the steps in the pipeline, I am using seaborn but the code requires latest version of seaborn and nanoplot is throwing error because of the seaborn version. 

I was wondering if there is a way to just output the raw data without calling the plotting libraries (which might throw the error). 

If there is no way without downgrading seaborn version - if possible, can you please point me to a starting point (which libraries to use to extract info from bam files)? I am currently playing with pysam and see if I can use to extract info. 

Thank you.

**Comment by wdecoster** [comment]
Please have a look at https://github.com/wdecoster/nanoget/blob/master/scripts/create_feather.py, that might do what you are looking for

**Comment by bhargava-morampalli** [comment]
That worked. I really like all your tools.
Thank you very much!
