### ISSUE TITLE
An error with nanoplot

### ISSUE THREAD

**Issue by mahsataghipour** [wdecoster/NanoPlot#299]
I can not use the nanoplot for my dataset and I received this massage :
An error occurred with this dataset:
If you read this then NanoPlot has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thank

**Comment by wdecoster** [comment]
Is that all you saw in the terminal? Please include the log file too.

**Comment by mahsataghipour** [comment]
I have sent you the screenshots of the page and also I tried to send you the file(in WinRAR format) which I wanted to analyze but the size is too big.
Thank you
Kind Regards

**Comment by mahsataghipour** [comment]
![h](https://user-images.githubusercontent.com/105163427/167316984-6d011f4a-2f19-461e-838d-786ae8053acf.PNG)
![h1](https://user-images.githubusercontent.com/105163427/167316987-68681bac-b5ba-4020-a063-13b4e877c67d.PNG)
![h3](https://user-images.githubusercontent.com/105163427/167316988-090bb06f-b1e2-4374-ab4e-e1ff450c9d23.PNG)
![h4](https://user-images.githubusercontent.com/105163427/167316989-6f5be28a-e2f2-4d5e-a77f-9d94e2b7546d.PNG)

**Comment by mahsataghipour** [comment]
https://usegalaxy.eu/datasets/4838ba20a6d86765ebdb4878ff856f5c/display?to_ext=gz
