### ISSUE TITLE
Save in svg and change colors

### ISSUE THREAD

**Issue by maculatus** [wdecoster/NanoPlot#3]
Hello Wouter,
Many thanks for your program, in combination with nanofilt is really great. I am wondering if it is possible to save the figures as svg and if the colors can be change by the user.
Thanks again...

**Comment by wdecoster** [comment]
Hi maculatus,

Thanks for the suggestions, I'll look into it. Both should be feasible!

Cheers,  
Wouter

**Comment by wdecoster** [comment]
Hi macalatus,

The last version supports setting a custom color, see [this list](https://github.com/wdecoster/NanoPlot/blob/master/color_options.txt) for options.
If you have feedback on this, please let me know.

I'll get to saving as svg later...

Cheers.
W

**Comment by maculatus** [comment]
Thanks!

**Comment by wdecoster** [comment]
Hi macalatus,

It took me a bit longer than I planned to, but the latest version supports specifying the output file format using the --format flag. Options are eps, jpg, pdf, png, ps, svg. Png stays the default for now.

To my surprise, the plots in svg format don't look exactly the same as in png format. I'm not sure what's going on.

Cheers,
Wouter

**Comment by maculatus** [comment]
Thanks. I will upgrade and compare the results. I will keep you posted.
Cheers
Gustavo
