### ISSUE TITLE
Albacore .sam files?

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#30]
Hi Wouter, 
I am calling minion runs on an amazon Ubuntu instance using Albacore. I also call for alignment against hg38.fa (downloaded from UCSC), to get both fastq and sam outputs. 

When I run NanoPlot using the fastq outputs, everything seems to work fine. 

However, when I convert the sam output to bam:
samtools sort -o 1948.sorted.bam fastq_runid_bighexnumber_0.sam

and use the produced file "1948.sorted.bam"
NanoPlot --bam 1948.sorted.bam --alength -f pdf -o /aligned/
I get and error that I can't understand.  Log file attached.
[NanoPlot_20171114_2142.log](https://github.com/wdecoster/NanoPlot/files/1472685/NanoPlot_20171114_2142.log)

Please let me know if my commands are wrong.

**Comment by wdecoster** [comment]
Hi Chris,

Hard to tell, but this suggests something is wrong with your bam file - probably incomplete. I'll use albacore for alignment here and see if I can reproduce your issue.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Hi Chris,

I just ran albacore with -a for aligning to the human genome. When I run `samtools view fastq_runid_xxxxx_0.sam` I already get:

```
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 1
[main_samview] truncated file.
```

So it looks like the sam files created by albacore are not valid. Also converting to bam doesn't work for me:

```
samtools sort -o test.bam fastq_runid_xxxxxxxxxxxxxx_0.sam 
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 1
samtools sort: truncated file. Aborting
```

If you do the alignment with minimap2, and not through albacore, everything should be fine.
I'll inform ONT about this.

Alternatively, you can add a header to your sam files as such:

```
samtools faidx genome.fa #creates a .fai index for your reference genome
samtools view -ht genome.fa.fai yourfile.sam | samtools sort -o yourfile.bam`
```

The created file yourfile.bam should be compatible with all downstream applications such as NanoPlot.

**Comment by tchrisboles** [comment]
OK - thanks again for your help.
