### ISSUE TITLE
Feature Request: Additional Quality Cutoffs

### ISSUE THREAD

**Issue by atrull314** [wdecoster/NanoPlot#305]
Hi,

We've been evaluating some nanopore data with the newer chemistries. We are seeing higher qualities overall, and think the ">Q15" block would benefit from being broken up more as the technology continues to evolve. 

Is there anyway that a feature could be added so that additional quality cutoffs could be added in the NanoStats.txt file that is generated? Preferably, it'd be nice if the cutoffs were able to be entered as an optional parameter by the user to provide a degree of customization. 

Thanks!

**Comment by AyanoClarke** [comment]
Hi,
