### ISSUE TITLE
Adaptive sampling info

### ISSUE THREAD

**Issue by nsgarcia27** [wdecoster/NanoPlot#309]
Hello. Is NanoPlot able to generate report on details of an ONT adaptive sampling sequencing run? Specifically want to see if I can get the "Reads completed N50" (for kept reads) and "adaptive sampling voltage reversal N50" (for rejected reads)?

Thanks!

**Comment by wdecoster** [comment]
That is not currently supported and seems so specific that I probably won't add it. Do you want to start from a sequencing summary file?  Is there a column that tells whether the read is completed or rejected?

**Comment by nsgarcia27** [comment]
Thanks for the reply. I actually would like to start from the fastq files. There was one sequencing run that got interrupted towards the end and it was not able to generate the summary file. So I was wondering if this tool could regenerate the reports on the barcoded adaptive sampling run.

**Comment by wdecoster** [comment]
Well, to start I don't know if that information is available in the fastq file, so you'll have to help me understand it here. How do you know for a fastq record/read if the read was completed or rejected?
