### ISSUE TITLE
Tooltip showing log length instead of length

### ISSUE THREAD

**Issue by mbhall88** [wdecoster/NanoPlot#310]
It looks like the tooltip for the bars in the read length histogram are showing the logarithm of the read length?

<img width="737" alt="Screen Shot 2022-09-28 at 10 25 10 am" src="https://user-images.githubusercontent.com/20403931/192660427-1039ff1f-8bf0-4a1c-8fcf-c343ea196179.png">

In the above example, 10<sup>2.982241</sup> is 960 - which matches up with the axis label. Is it possible to get the tooltips showing the real value?

**Comment by wdecoster** [comment]
Hi @mbhall88, 

thanks for reporting this, should be fixed in NanoPlot v1.40.1 :-) 

Wouter
