### ISSUE TITLE
About default min read quality setup

### ISSUE THREAD

**Issue by wuying1984** [wdecoster/NanoPlot#312]
Hi,

I am running NanoPlot to generate the QC matrix of my nanopore reads. 
When I use the following command, I found that nanoplot uses the reads with quality over 5 to generate the report and figures. I wonder if I can setup some parameter so that nanoplot will not drop any reads and use all the reads to generate the report and figure. Thank you very much!
**my command:**  nanoplot -t 12 -o output_folder  --prefix sample_name -f png --fastq input.fastq.gz --plots kde

Best,
Ying

**Comment by wdecoster** [comment]
NanoPlot by default uses all the reads. You may not have any reads with a quality below 5?

**Comment by wuy24** [comment]
Yes, I think so. Thank you very much!
