### ISSUE TITLE
multiple plots

### ISSUE THREAD

**Issue by omarkr8** [wdecoster/NanoPlot#325]
Hello, 
I've yet to test nanoplot, though all the discussion looks promising!
ive read that its possible to get data for multiple samples and then plot them side-by-side.
but im not sure how exactly to do this, first time seeing a pickle file.

I have 25 demultiplexed samples. I'd just like to plot them together, perhaps 5x5.
im fairly new to commands. but i imagine i'd have to make a loop to generate a pickle file for each to plot together later or something?
or is looping built in nanoplot if i point it to a directory with folders of fastqs.

**Comment by wdecoster** [comment]
If you want to get plots side-by-side I recommend you use [NanoComp](https://github.com/wdecoster/nanocomp).
