### ISSUE TITLE
How is mean Qscore calculated? Why is it different from the mean of the mean_qscore from the sequencing_summa

### ISSUE THREAD

**Issue by lgraciamaz** [wdecoster/NanoPlot#327]
How is mean Qscore calculated and why is it different than the value you obtain from calculating the mean of the mean_qscore column from the sequencing_summary.txt file?

**Comment by wdecoster** [comment]
Means are calculated by converting Phred scores to error/accuracy probabilities, taking the mean, and converting back to the Phred scale.
