### ISSUE TITLE
mean quality is different between 1.40.2 and 1.41.0

### ISSUE THREAD

**Issue by lovelynewGao** [wdecoster/NanoPlot#330]
Hi, i run the nanoplot to calculate the quality of the same sequencing data with different versions. And I got the different result: 1.41.0 is 2 lower than 1.40.2. Is it normal?

**Comment by wdecoster** [comment]
There has been a change in how this is calculated, which probably explains the difference you see:  https://github.com/wdecoster/nanostat/issues/40
