### ISSUE TITLE
Not all dots seem to be plotted

### ISSUE THREAD

**Issue by ryotag** [wdecoster/NanoPlot#335]
Thank you for developing this nice tool!

I generated stats and figures using NanoPlot 1.41.0 with a command `NanoPlot -t 8 -o NanoPlot_out --fastq ONT_read.fastq.gz`.
I then found that not all dots are plotted in the generated figures.
For example, top 5 longest reads are not plotted in read length vs average read quality plot.
Actually, there seem to be many dots not shown in this plot.
I did not use options like --drop_outliers or --downsample, so I'm a bit confused why not all read data are shown in the plot.
It would be nice if you could provide some insights into this.

Thank you,

**Comment by wdecoster** [comment]
Can you give an example, show the plots, as well as the missing reads, and add the log file?

Thanks,
Wouter

**Comment by ryotag** [comment]
Thank you for the response.
This is read length vs average read quality plot (zoomed out to show the entire plot).
![length_quality_plot](https://github.com/wdecoster/NanoPlot/assets/39789068/68755827-ac85-4c73-a7a6-5161c26242de)


This is yield by length plot (zoomed out to show the entire plot).
![yield_by_length_plot](https://github.com/wdecoster/NanoPlot/assets/39789068/3a10cbfb-8a3a-467e-a82a-6e09676c8442)


And this is NanoStats.txt
```
General summary:         
Mean read length:                 6,375.4
Mean read quality:                   13.2
Median read length:               5,986.0
Median read quality:                 13.1
Number of reads:                329,803.0
Read length N50:                  7,878.0
STDEV read length:                3,383.7
Total bases:              2,102,620,205.0
Number, percentage and megabases of reads above quality cutoffs
Q5:	329803 (100.0%) 2102.6Mb
Q7:	329803 (100.0%) 2102.6Mb
Q10:	329730 (100.0%) 2102.5Mb
Q12:	227629 (69.0%) 1457.0Mb
Q15:	65476 (19.9%) 406.6Mb
Top 5 highest mean basecall quality scores and their read lengths
1:	29.0 (1)
2:	28.7 (178)
3:	27.3 (66)
4:	25.7 (113)
5:	25.3 (133)
Top 5 longest reads and their mean basecall quality score
1:	39932 (13.1)
2:	38836 (16.1)
3:	38026 (12.0)
4:	35467 (10.8)
5:	34246 (10.5)
```
This is a log file. 
[NanoPlot_20230327_1744.log](https://github.com/wdecoster/NanoPlot/files/11879419/NanoPlot_20230327_1744.log)

Apparently, top 5 reads are not plotted on both plots, and there seems to be discrepancy between two plots (e.g., there is 25461 bp plotted on read length vs average read quality plot but not on yield by length plot.)
My guess is that reads are ramdomly sub-sampled in the plots but I'm not sure.

Thank you,

**Comment by ryotag** [comment]
I might have found the reason.
I used NanoPlot 1.31.0 to plot the same data, and found that all dots seem to be plotted.
This is read length vs average read quality plot.
![LengthvsQualityScatterPlot_dot](https://github.com/wdecoster/NanoPlot/assets/39789068/0b3240e8-3e5e-4f2d-812a-da9af83310e5)

This is yield by length plot.
![Yield_By_Length](https://github.com/wdecoster/NanoPlot/assets/39789068/af50afd2-57ac-4e3c-b387-6ca55314818b)

So my guess is that the older version of NanoPlot (such as version 1.31.0) plots all dots, while newer version (such as version 1.41.0) plots only a subset of dots.

**Comment by wdecoster** [comment]
hmm I do not remember changing anything that would start hiding dots. Let me look into this, but I will only have time for that after my holidays.

**Comment by wdecoster** [comment]
I suspect you may see similar things as reported here, https://github.com/wdecoster/NanoPlot/issues/339, which would be expected behavior.

**Comment by ryotag** [comment]
Thank you for the reply!
That makes sense!
