### ISSUE TITLE
Thank you for your newest github release

### ISSUE THREAD

**Issue by erinyoung** [wdecoster/NanoPlot#338]
From your latest release (https://github.com/wdecoster/NanoPlot/releases/tag/v1.41.6)

> I don't really have the habit of creating releases here, but PyPI and bioconda are always up to date. Let me know if releases are important to you.

And... I wanted to let you know that, yes, your releases on github are important to the [StaPH-B community](https://github.com/StaPH-B) because it's an easy way to tell when a new version exists.

**Comment by wdecoster** [comment]
Thanks for letting me know! I will try to keep that in mind and make regular releases.
