### ISSUE TITLE
Difference in read quality output from bam and summary file

### ISSUE THREAD

**Issue by teodorabu** [wdecoster/NanoPlot#342]
Hi, Thanks for this great tool. I have a question regarding the computation of the mean read quality score in the NanoStat.txt file: why is this value different when computed from the basecalling bam file and summary file of the same run?

Thanks!

**Comment by wdecoster** [comment]
It is computed from the bam file by taking the phred scaled quality scores, converting those to probabilities, taking the mean, and converting that back into the phred scale. When using the summary file the value provided by the basecaller is used directly, without further calculations. It is not disclosed by ONT what else is taken into account to calculate this "per read quality score".
