### ISSUE TITLE
NanoPlot 1.41.6 has crashed 

### ISSUE THREAD

**Issue by SelfShubham** [wdecoster/NanoPlot#343]
[NanoPlot_20231005_1728.log](https://github.com/wdecoster/NanoPlot/files/12818115/NanoPlot_20231005_1728.log)
Hi,
I am getting NanoPlot 1.41.6 has crushed when I am using --legacy hex command for my data. If I ma not using this specific command than NanoPlot is working fine. I had attached the log file also. Thanks for the help.

**Comment by wdecoster** [comment]
That is a duplicate of https://github.com/wdecoster/NanoPlot/issues/222

Please downgrade your seaborn version to v0.10.1
