### ISSUE TITLE
Return only the report

### ISSUE THREAD

**Issue by juanjo255** [wdecoster/NanoPlot#345]
Hello!

Is there a way to only return the NanoPlot-report.html?

Thanks,

Juan

**Comment by wdecoster** [comment]
Not right now, why would that be of interest?

**Comment by juanjo255** [comment]
Not a big deal. It's just to avoid the high number of files generated for quick quality views.

**Comment by wdecoster** [comment]
I am not against it, but the easiest is probably an '&& rm output_directory/*.png'. Practically this could be implemented in the python code too, but I'm not sure if it is worth it. If you want to open a pull request we can discuss further :)
