### ISSUE TITLE
pandas.value_counts is deprecated

### ISSUE THREAD

**Issue by jodjo86** [wdecoster/NanoPlot#348]
I got this error: 
```
/home/user/miniforge3/envs/nano/lib/python3.10/site-packages/nanoplotter/spatial_heatmap.py:76: FutureWarning:
pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
```
To correct the problem, I replaced line 76 of the spatial_heatmap.py with this :
```
valueCounts = pd.Series(array).value_counts()
```
Sorry for not making a pull request.

**Comment by wdecoster** [comment]
Thank you for the detailed report and solution! Okay, I will fix this - or that pull request is still welcome ;)
