### ISSUE TITLE
issue/warning?

### ISSUE THREAD

**Issue by gunjanpandey** [wdecoster/NanoPlot#349]
Could you please help with this error/warning? Could it simply be ignored.
I am still getting all the results files. 

Also it is not using all the cores but only one. 

`**NanoPlot --threads 64  --fastq ../nano.fastq  --store**

 /apps/python/3.11.0/lib/python3.11/site-packages/nanoget/utils.py:19: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, df_int.columns] = df_int.apply(pd.to_numeric, downcast='integer')
/apps/python/3.11.0/lib/python3.11/site-packages/nanoget/utils.py:20: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:, df_float.columns] = df_float.apply(pd.to_numeric, downcast='float')
`

**Comment by wdecoster** [comment]
Safe to ignore :)
