### ISSUE TITLE
Nanoplot Errno32 Broken pipe

### ISSUE THREAD

**Issue by teodorabu** [wdecoster/NanoPlot#353]
Hi!

I am attempting to use Nanoplot to analyse some barcoded Nanopore sequencing data, however I cannot get past a broken pipe errno 32. I have 25 barcodes in my summary file, with some of them containing very few reads, but my guess is that Nanoplot will skip them automatically based on some read nr threshold, so I am not sure if those are the problem here. Hope you can give me an idea what how to circumvent the problem. Attached also the log file 
[NanoPlot_20240118_1932.log](https://github.com/wdecoster/NanoPlot/files/13980592/NanoPlot_20240118_1932.log)
 Thanks!

**Comment by teodorabu** [comment]
upgrading nanoplot solved my issue :)

**Comment by wdecoster** [comment]
Good to hear this is solved!
