### ISSUE TITLE
Web Service not loading in CA

### ISSUE THREAD

**Issue by jennifergribble-nanopore** [wdecoster/NanoPlot#354]
Hi,

A colleague is unable to access the web service when on Canadian networks but is able to in the US.

Thanks!

**Comment by svennd** [comment]
I believe that's the firewall, blocking anything not from Europe/US. I don't think our ISP will be willing to open up further, but I can ask.

**Comment by wdecoster** [comment]
Hi, firewall settings have been adjusted, can you confirm this is fixed?

**Comment by jennifergribble-nanopore** [comment]
Hi, we are currently at an internal meeting in the US and he will be back this weekend. I will update by Jan 29, if that is okay

**Comment by wdecoster** [comment]
Absolutely!

**Comment by jennifergribble-nanopore** [comment]
My colleague in CA can reach the web service, thank you!!
