### ISSUE TITLE
Using barcoded BAM files with no summary

### ISSUE THREAD

**Issue by Ge0rges** [wdecoster/NanoPlot#356]
Hello,

I have a set of unaligned BAMs seperated by barcode given to me by dorado. I was wondering if it would be possible to use these with the `--barcoded` flag to get a summary of each barcode, and a summary of the all together? This seems to require a summary file currently.

**Comment by wdecoster** [comment]
So you have individual bams, and for each bam you want a summary? --barcoded does not support that, indeed, but I think you should use all bams at the same with NanoPlot to get the "all together" report and use them in [NanoComp](https://github.com/wdecoster/nanocomp) to get separate reports/comparison.

**Comment by lucyintheskyzzz** [comment]
@Ge0rges I wonder if its possible to concatenate all the barcoded .bam files into one file then run NanoPlot to get the total read summary from all the barcodes? I will probably try this with NanoComp as well.

**Comment by wdecoster** [comment]
NanoPlot will combine multiple bams, no need to concatenate first

**Comment by lucyintheskyzzz** [comment]
@wdecoster I am actually doing fastq.gz files from dorado and looks like my nanoplot results separated out each barcode into separate directories.  Is there a way to have all the results combined? 
<img width="98" alt="image" src="https://github.com/wdecoster/NanoPlot/assets/71407498/1e02f8d9-1512-4fbf-937e-94dee1ed7c7f">

**Comment by wdecoster** [comment]
You wrote a loop over the fastq directories (in your other issue). Just use all fastqs at the same time.

**Comment by Ge0rges** [comment]
@wdecoster seems like NanoComp only supports aligned BAM files however, what would be the logical way to use it with the unaligned barcodes given by dorado? 

Also what is the difference between using `--barcoded` with a summary file, and just running each barcode individually, then all together? Surely the tool could produce a `per barcode` analysis with the latter option as well?
