### ISSUE TITLE
Wrong value for the mean read quality

### ISSUE THREAD

**Issue by DenisFilloux** [wdecoster/NanoPlot#361]
Hello Wouter,

I noticed an issue with the calculation of the mean read quality in the latest version of NanoPlot (v1.42.0), whereas the value is correct in version 1.40.0 (v1.41.6 untested).

Can you confirm this?

[test.fastq.gz](https://github.com/wdecoster/NanoPlot/files/14863885/test.fastq.gz)

NanoPlot v1.42.0

General summary:         
Mean read length:              417.0
**Mean read quality:               8.1**
Median read length:            402.0
Median read quality:             9.5
Number of reads:               100.0
Read length N50:               425.0
STDEV read length:             119.7
Total bases:                41,700.0
Number, percentage and megabases of reads above quality cutoffs
>Q5:	93 (93.0%) 0.0Mb
>Q7:	83 (83.0%) 0.0Mb
>Q10:	42 (42.0%) 0.0Mb
>Q12:	10 (10.0%) 0.0Mb
>Q15:	0 (0.0%) 0.0Mb
Top 5 highest mean basecall quality scores and their read lengths
1:	14.9 (477)
2:	13.0 (352)
3:	12.9 (533)
4:	12.8 (712)
5:	12.7 (530)
Top 5 longest reads and their mean basecall quality score
1:	798 (10.4)
2:	790 (6.9)
3:	712 (12.8)
4:	671 (10.5)
5:	659 (12.6)

NanoPlot v1.40.0

General summary:         
Mean read length:              417.0
**Mean read quality:               9.3**
Median read length:            402.0
Median read quality:             9.5
Number of reads:               100.0
Read length N50:               425.0
STDEV read length:             119.7
Total bases:                41,700.0
Number, percentage and megabases of reads above quality cutoffs
>Q5:	93 (93.0%) 0.0Mb
>Q7:	83 (83.0%) 0.0Mb
>Q10:	42 (42.0%) 0.0Mb
>Q12:	10 (10.0%) 0.0Mb
>Q15:	0 (0.0%) 0.0Mb
Top 5 highest mean basecall quality scores and their read lengths
1:	14.9 (477)
2:	13.0 (352)
3:	12.9 (533)
4:	12.8 (712)
5:	12.7 (530)
Top 5 longest reads and their mean basecall quality score
1:	798 (10.4)
2:	790 (6.9)
3:	712 (12.8)
4:	671 (10.5)
5:	659 (12.6)

**Comment by wdecoster** [comment]
The reason that it has changed is here: https://github.com/wdecoster/nanostat/issues/40
Does that make sense to you?
