### ISSUE TITLE
Running NanoPlot on aligned bam file demuxed by Dorado?

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#363]
This may be more of a samtools question, but....

I did a MinIon run using Rapid barcoding kit SQK-RBK114-24 using barcodes 1-4. After sup basecalling and alignment to hg38  using Dorado, I used Dorado demux to separate the barcoded reads into separate bam files. After sorting and indexing the bc0x.bam files, I tried to run NanoPlot on them.

Running NanoPlot on the output bam file **before** demuxing gives the usual nice NanoPlot output. 

Running NanoPlot on the bc1.bam data set, NanoPlot throws an error (see attached log). 

Maybe Dorado demux is doing something funny with the bam header? Any suggestions?

Chris

[NanoPlot_20240501_1759.log](https://github.com/wdecoster/NanoPlot/files/15189217/NanoPlot_20240501_1759.log)

**Comment by tchrisboles** [comment]
Answered in Dorado issues by Joyjit Daw:
If dorado basecaller is run with alignment option, dorado demux must be run with "--no-trim" option or else dorado demux will strip out all alignment info from the demuxed bams. 
Issue can be closed.

**Comment by wdecoster** [comment]
Hi @tchrisboles, great to see you are still working with nanopore data. Seems this issue solved itself then :-) Let me know if there is anything else I can help you with!
