### ISSUE TITLE
setup.py problem

### ISSUE THREAD

**Issue by lihaicheng7003** [wdecoster/NanoPlot#365]
![image](https://github.com/wdecoster/NanoPlot/assets/61043072/59233daf-1c3c-4c70-9ebd-48a3173b7fb9)

**Comment by wdecoster** [comment]
That should not be a problem. Those classifiers don't influence the installation process, I believe, or do you encounter an issue?

**Comment by lihaicheng7003** [comment]
python 3.5 has problem(can't install pandas, pandas 1.1.0 requir python >= 3.6)，python 3.6 is work

**Comment by lihaicheng7003** [comment]
I've installed it successfully, just to present my findings, maybe need to make some changes to the setup.py
