### ISSUE TITLE
Adding Q30 and Q50 to summary statistics of NanoPlot report

### ISSUE THREAD

**Issue by Fedeluppi** [wdecoster/NanoPlot#366]
Hi,

I am using NanoPlot both for PacBio and ONT data and I was wondering if it was possible to add Q30 and Q50 in the summary statistics of the NanoPlot report or if there is already a command line option that I am missing out.

Thanks for your resource,

Best,

Federica

**Comment by wdecoster** [comment]
Hi Federica,

According to [these ](https://github.com/wdecoster/nanomath/commit/baa2ca7daee20cbbce1be63612f2a90459191047)changes, the current cutoffs (with the last version) should be 10, 15, 20, 25 and 30. Is that what you are seeing?
That is currently specified only in the code, and it is difficult to set reasonable defaults that work for everyone. I understand Q50 would be useful. But at the same time, I don't want to expose all options on the command line, that would lead to an enormous list of options for users to search through.

Wouter

**Comment by Fedeluppi** [comment]
Hi Wouter,

Thanks for the quick answer! I am using NanoPlot with a singularity image. Unfortunately I tried with different versions that I can fetch from the Docker hub (see below) but I only see the Q scores until Q15 :/.

Docker hub containers:

- [staphb/nanoplot:1.27.0](https://hub.docker.com/layers/staphb/nanoplot/1.27.0/images/sha256-3a92d89571e4cd8eb687aa474b3c540527eda9a89f029c54b373f3131fc6d706?context=explore)
- [nanozoo/nanoplot](https://hub.docker.com/r/nanozoo/nanoplot)

I have tried these two as they seem the most up-to-date versions of NanoPlot on docker hub (https://hub.docker.com/search?q=nanoplot). It would be great if you could point me a different docker file with the relevant changes on the Q metrics.

Thanks a lot,

Best,

Federica

**Comment by wdecoster** [comment]
Hrm singularity is not something that I typically use, but it seems there are more recent version here: https://hub.docker.com/r/staphb/nanoplot/tags ?

**Comment by sandratra-rab** [comment]
Hi,
I tried to use the latest staphb NanoPlot docker image (pullad as a Singularity image) that you linked and both latest NanoPlot bioconda and pip3 packages but they were all built using nanomath==1.3.0. So if I'm not wrong, no current installation mode seems to include the latest code modifications for the 10, 15, 20, 25 and 30 cutoffs.
