### ISSUE TITLE
NanoPlot 1.42.0 has crashed

### ISSUE THREAD

**Issue by mithunbge06** [wdecoster/NanoPlot#369]
Hello Nanoplot community,

I am trying to run QC on PacBio_HiFi long read data (.bam file).

Unfortunately, NanoPlot 1.42.0 keeps crashing. I have attached the log file of the run. 
There was an error "ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False". I have tried to open it with "check_sq=False" but still getting the same error.

[NanoPlot_20240607_1828.log](https://github.com/user-attachments/files/15737764/NanoPlot_20240607_1828.log)

**Comment by wdecoster** [comment]
Pysam suggests that your data may be corrupted. Is your bam file aligned? Could you try with --ubam instead of --bam?

**Comment by mithunbge06** [comment]
My data was not aligned. Also, there were some version conflicts in our HPC system. At last, I have used a virtual environment to install NanoPlot and used --ubam as you suggested. It seems to be working. Thank you.
