### ISSUE TITLE
Q10 to Q30 quality score thresholds not available in latest NanoPlot version

### ISSUE THREAD

**Issue by sandratra-rab** [wdecoster/NanoPlot#371]
Hi, 
I saw that the latest nanomath commit is the following "update quality score thresholds" and that you said that the new 10, 15, 20, 25 and 30 cutoffs should be available with the latest NanoPlot version #366. However, when trying to download the latest staphb NanoPlot docker image (pulled as a Singularity image) and both latest NanoPlot bioconda and pip3 packages but they were all built using nanomath==1.3.0 (and nanomath==1.4.0 does not seem to exist when I try to manually update it). 

So if I'm not wrong, no current installation mode seems to include the latest code modifications for the 10, 15, 20, 25 and 30 cutoffs. 

Did I miss something ? Is there a way to use NanoPlot with the latest nanomath update ?

**Comment by wdecoster** [comment]
Hmm I didn't realize that! I have just pushed nanomath 1.4.0 to pypi, I think conda will follow soon.
What I should really be doing is migrating the code from nanomath into nanoplot itself to get rid of these version issues...

**Comment by sandratra-rab** [comment]
Indeed, it would be easier to maintain this way.

Thank you, I've just updated nanomath and it worked like a charm!

**Comment by wdecoster** [comment]
Awesome, thanks for the feedback!
