### ISSUE TITLE
#!NanoPlot -o nanoplot_output --fastq_rich barcode04.fastq.gz

### ISSUE THREAD

**Issue by ghislain-ctl** [wdecoster/NanoPlot#374]
this command line is telling me that is crashed. can you send me a working command line

**Comment by wdecoster** [comment]
Hi, in order to help you, you will need to give me some more information, such as the log file or the error message you got.

Best,
Wouter

**Comment by ghislain-ctl** [comment]
Hello,
I am trying to generate sam,bam, and vcf files coding using google colab
referencing the plasmodium reference whole genome and reference resistant
genes files.
You can guide me using all the command lines  from mounting drive to
qualimap.
if possible you can send me the google colab with all command lines


Regards
Ghislain

**Comment by wdecoster** [comment]
That is not the level of support you should expect from an unrelated GitHub issue. I suggest finding someone in your institution to help you.
