### ISSUE TITLE
analysis of data using samples containing large amounts of carrier DNA

### ISSUE THREAD

**Issue by tchrisboles** [wdecoster/NanoPlot#38]
Wouter, 
I ran sequencing on samples (50ng genomic mouse DNA) + ~200 ng lambda phage DNA. I obtained the fast5 file, base-called it on Albacore, aligned them in two separate minimap2 procedures. In one, I aligned to mouse (mm38) reference genome. In second process, I aligned the data to the lambda reference. 
After sorting the resulting minimap2 sam aligments using samtools, I plotted the aligned data using NanoPlot. Although I used the same commands for both alignment procedures, and aligned data were produced for lambda DNA (see NanoStats-lambda-annot.txt), Nanoplot only produced the full set of plot outputs with the mouse alignment (see pdf). 
I suspect I am overlooking something elementary. Can you help?

[NanoStats-lambda-annot.txt](https://github.com/wdecoster/NanoPlot/files/1593712/NanoStats-lambda-annot.txt)
[NanoStats-mouse-annot.txt](https://github.com/wdecoster/NanoPlot/files/1593714/NanoStats-mouse-annot.txt)
[20171229_Nanoplot_output_question.pdf](https://github.com/wdecoster/NanoPlot/files/1593716/20171229_Nanoplot_output_question.pdf)

**Comment by tchrisboles** [comment]
Wouter, 

False alarm -- I just found that my internet connection to AWS is abnormally slow/buggy today. WinSCP is having trouble updating my directories - I just inspected the lambda directory and found the rest of the NanoPlot data that I was expecting. Sorry for the false alarm.

**Comment by wdecoster** [comment]
Hi tchrisboles,

Glad this issue solved itself. Don't hesitate to reach out if you encounter issues or have suggestions/feature requests!

Cheers,
Wouter
