### ISSUE TITLE
NanoPlot 1.43.0 crash

### ISSUE THREAD

**Issue by llesley8** [wdecoster/NanoPlot#380]
Hi, 

I ran into some trouble with NanoPlot v 1.43.0 when I included `--legacy hex` in my script and received an output message saying that NanoPlot crashed and to try updating it. In my previous script when I wrote `--plots hex dot kde` I received an html NanoPlot report but this time when I appended my script to `--plots dot kde --legacy hex` I did not. 

I've included the log file below and would appreciate any help! 
[NanoPlot_20240909_0118.log](https://github.com/user-attachments/files/16928713/NanoPlot_20240909_0118.log)

**Comment by wdecoster** [comment]
Hi,

That looks similar to https://github.com/wdecoster/NanoPlot/issues/222, could you try downgrading seaborn to 0.10.1? 
Hope this helps. I keep those legacy plots in there because some of them are nice, but as the name implies, they're not really heavily supported. 

Wouter

**Comment by wdecoster** [comment]
Hmpf, that's a new one. Can you check which version of matplotlib you have installed? You may have to downgrade that one, too. Based on a quick Google search, I suspect v3.1.0 should work. Or you should decide you don't really want the legacy plots :)

**Comment by llesley8** [comment]
Hi Wouter! After downgrading matplotlib to v3.1.0 and seaborn to v.0.10.1 I successfully received a Nanoplot report including the legacy hex plot. Thank you so much for your help!!
