### ISSUE TITLE
Number of reads in Nanoplot

### ISSUE THREAD

**Issue by dfv** [wdecoster/NanoPlot#382]
Hi,

I have used Nanoplot for one of my mapped file from Nanopore sequencing. But the number of input reads in the mapped file are different from number of input reads obtained from fastp or samtools.

Number of reads from Nanoplot: 9658704 

Number of reads from fastp & samtools: 6803340

Is it possible to what can be reason for variation in number of input reads ?

Thanks a lot.

**Comment by wdecoster** [comment]
If I remember correctly, NanoPlot shows the number alignments (not necessarily sequenced reads), i.e. primary and supplementary alignments, excluding secondary and unmapped reads.

**Comment by dfv** [comment]
Hi,

Thanks a lot for replying.

Okay, if it's aligned reads. Then in stats how aligned reads could be higher than total no of input reads?

Input reads: 6,803,340
Number of aligned reads: 9,658,704

Thanks.

**Comment by wdecoster** [comment]
Supplementary alignments
