### ISSUE TITLE
old version of NanoPlot

### ISSUE THREAD

**Issue by QuentinPerriere** [wdecoster/NanoPlot#383]
Hello,

I have a small suggestion, and I hope you will take it into account. Is there a way to retrieve the old version of NaPlot where Q5 and Q7 scores are also displayed? I understand that nanopore sequencing technology has advanced, producing reads with better quality. However, in our case, we still work with reads that have a Q7 score. Unfortunately, with the latest update of the package, we can no longer see the number of reads with this phred score.

It's also a bit complicated for me to modify the original github code locally to address this issue.

Thank you for your consideration!

**Comment by wdecoster** [comment]
You can install specific versions with both pip or conda, e.g. `pip install nanoplot==1.2.3`
