### ISSUE TITLE
[Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by chanster-j** [wdecoster/NanoPlot#385]
Hi all

I am new to nanoplot (and bioinformatics) and had managed to execute the commend ok when not using the barcode option. Unfortunately, most of my work will be barcoded so I am wondering if I could get some help about [Errno 35] Resource temporarily unavailable. Is there any way for me to overcome this? I have attached the log file as prompted. 

Thanks in advance!

[NanoPlot_20241011_0925.log](https://github.com/user-attachments/files/17335273/NanoPlot_20241011_0925.log)

**Comment by wdecoster** [comment]
Hi,

Is this something you see all the time, or just this one time? 
It is from kaleido, the tool that generates statis (png) images from the html files. That results in problems for more users, and you can turn it off with `--no_static`.

Wouter

**Comment by chanster-j** [comment]
Hi Wouter

Thanks for replying, this happens only when I am running a larger data set (~20 samples and 15GB output), seem to have no issue with smaller runs. Is this normal?

Turning it off is helping :) Thanks!
