### ISSUE TITLE
no analytic data is generated 

### ISSUE THREAD

**Issue by Seongmin-Jang-1165** [wdecoster/NanoPlot#387]
hello developer 

i want to analyze my direct RNA seq data wiht Nanoplot, but the error is occured...

i already run nanoplot and generated data with no problem

but when i added option about min/max length, it cannot be processed.

can you advise me how to solve this problem..?

-code-
 NanoPlot  -o /lustre/home/rnagenomics/sm/Nanopore/20240923_Histone_Direct_RNA_seq/analysis/NanoPlot/option1/ --tsv_stats --info_in_report  --fastq /lustre/home/rnagenomics/sm/Nanopore/20240923_Histone_Direct_RNA_seq/analysis/basecalling/DORADO_simplebasecall_notrim_fastq.fastq --plots --N50 --maxlength 250 --minlength 1000

-log-
![image](https://github.com/user-attachments/assets/93da0533-83af-43ef-8754-8d4ae189992a)

**Comment by wdecoster** [comment]
I think you should not have a max length smaller than the min length. You removed all reads that way.
