### ISSUE TITLE
Nanoplot crashes

### ISSUE THREAD

**Issue by AhmedSAHassan** [wdecoster/NanoPlot#388]
I am using Nanoplot for fastq files from ONT but it crashes in a second after I run the code.
[NanoPlot_20241124_1548.log](https://github.com/user-attachments/files/17893724/NanoPlot_20241124_1548.log)

I attached the log file.

Thanks in advance.

**Comment by wdecoster** [comment]
This indicates your input file is not what you think it is, or corrupted. Is it actually .fastq, or could it be compressed?
What do you get from the unix file command?

`file ./FASTQ/PAU84062_pass_SUP_barcode01.fastq`

**Comment by AhmedSAHassan** [comment]
Thank you Wouter, the files were indeed corrupted. I re-downloaded them and the tool runs smoothly now.

**Comment by wdecoster** [comment]
Thanks for letting me know!
