### ISSUE TITLE
NanoStats : discrepancy when working from fastQ or summary file

### ISSUE THREAD

**Issue by FredericBGA** [wdecoster/NanoPlot#4]
Thank you for sharing this tool.

I see a difference in quality score when I work from the summary file or the fastQ file.
From fastQ, scores seem to be higher.

from fastQ (NanoPlot --fastq workspace/fastq_runid_1_0.fastq -t 5 --loglength):
```
Top 5 read lengths and their average basecall quality score:
Length: 454650bp        Q: 12.99
Length: 240170bp        Q: 9.26
Length: 136854bp        Q: 13.07
Length: 103039bp        Q: 16.09
Length: 87759bp Q: 9.74

Top 5 average basecall quality scores and their read lengths:
Length: 520bp   Q: 37.59
Length: 987bp   Q: 35.99
Length: 2200bp  Q: 35.99
Length: 1293bp  Q: 35.6
Length: 4867bp  Q: 35.59
```
from summary (NanoPlot --summary sequencing_summary.txt -t 5 --loglength):
```
Top 5 read lengths and their average basecall quality score:
Length: 454650bp        Q: 8.51
Length: 240170bp        Q: 5.96
Length: 136854bp        Q: 8.06
Length: 103039bp        Q: 10.26
Length: 87759bp Q: 6.19

Top 5 average basecall quality scores and their read lengths:
Length: 407bp   Q: 17.98
Length: 3146bp  Q: 17.3
Length: 4429bp  Q: 17.29
Length: 3556bp  Q: 17.28
Length: 10061bp Q: 1
```

I would prefer fastQ scores of course :). But do you know why it's so different ?

thank you.

**Comment by wdecoster** [comment]
Yes, this issue was already on my list, I also recently identified it. The key difference is that when calculating the average quality of a read I currently take the average of all q-scores, which is not really a correct method. Albacore takes an average of the error probabilities, then converts it back to a Phred score.

I'll probably fix this tomorrow.

**Comment by wdecoster** [comment]
I adapted the function for calculating the averages (in the [nanomath](https://github.com/wdecoster/nanomath) module). To update your installation, use

```
pip install nanomath --upgrade
```

This will get the average read basecall quality scores of the fastq/bam input closer to the one reported by albacore in the summary, but due to unknown reasons, it's not exactly the same. I'm not sure what else albacore does differently.

**Comment by FredericBGA** [comment]
Hi,

Thank you for working as fast on this issue.

I re-run Nanoplot after the pip install nanomath –upgrade,

But the quality values are the same as the previous version (really high in FastQ compared to summary mode).

Fred

De : Wouter De Coster [mailto:notifications@github.com]
Envoyé : dimanche 25 juin 2017 20:29
À : wdecoster/NanoPlot <NanoPlot@noreply.github.com>
Cc : SAPET, Frederic <frederic.sapet@biogemma.com>; Author <author@noreply.github.com>
Objet : Re: [wdecoster/NanoPlot] NanoStats : discrepancy when working from fastQ or summary file (#4)


I adapted the function for calculating the averages (in the nanomath<https://github.com/wdecoster/nanomath> module). To update your installation, use

pip install nanomath --upgrade

This will get the average read basecall quality scores of the fastq/bam input closer to the one reported by albacore in the summary, but due to unknown reasons, it's not exactly the same. I'm not sure what else albacore does differently.

**Comment by wdecoster** [comment]
Could you check (e.g. from the NanoPlot log file) which version of nanomath was used?

**Comment by FredericBGA** [comment]
sorry, it was my fault...
I've updated the wrong version of python using pip instead of pip3.

it works now.

**Comment by wdecoster** [comment]
Good to hear! If you have feedback or suggestion don't hesitate to let me know.

**Comment by Riverzrw** [comment]
Hi,
I installed NanoPlot yesterday, but also encountered the same problem as Fred. That is say, using sequencing summary file and fastq obtained different result. The nanomath version is 0.22.0. I want to know which result is more feasible.

**Comment by wdecoster** [comment]
More feasible? What does that mean?

The average quality scores for fastq files are calculated as described [in this blog post](https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/). I don't calculate the quality scores in the summary files and just use what is provided by the basecaller. The difference between the summary file and fastq is known but is not big enough to be a serious issue in my opinion. I don't know what the basecaller does differently.

**Comment by Riverzrw** [comment]
Sorry, what I want to mean is which of the two results is more credible.

**Comment by ahcm** [comment]
Is it even completely known how albacore, which is currently being replaced by guppy, does exactly calculate the score?
If not, wdecoster's way is more credible ;-)

**Comment by wdecoster** [comment]
I don't know if it's known, but I for sure don't know :-)

**Comment by Riverzrw** [comment]
Thank you for your reply. So can I understand that the results obtained using the fastq file are more credible? Yeah, I just got into sequencing and nanopore, so there are a lot of small questions to ask.

**Comment by wdecoster** [comment]
I expect the difference to be small, and then again what kind of conclusion are you going to draw from this?

**Comment by ahcm** [comment]
You could also question whether a single number can capture the quality of a 100kb read ;-)

**Comment by Riverzrw** [comment]
I found that the read quality are high in the results obtained using the summary file. I don't know how guppy gets the value.
