### ISSUE TITLE
Cumulative Yield Plot

### ISSUE THREAD

**Issue by damientully** [wdecoster/NanoPlot#40]
Hi Wouter,

While NanoPlot outputs a cumulative yield plot this is in terms of yield in gigabase I am wondering is it possible to get this output in terms of the number of reads i.e cumulative # of reads? Secondly, is it possible that given perhaps a bam (alignment) file you could also generate this type of plot. The reason I ask is that given RNA-Seq type of data where you are trying to find a particular pathogen it would be interesting to see time to first detection of read and how the pathogen yield looks over time.

Thanks,
Damien

**Comment by wdecoster** [comment]
_For completeness sake, I also uploaded the example plot you send me earlier over email for your second request.
![example](https://user-images.githubusercontent.com/11660522/34993232-0229ff5c-fad0-11e7-8a93-3fb38fd2b9b7.png)
_

Thanks for the feedback! I'd be happy to look into your suggestions. A cumulative yield plot with the number of reads should definitely be possible and I'll add this later this week. 

The second question is a bit more tricky. The main problem is that after alignment the "time" information is lost. I'll have to think about how to do this the easiest, but I think I'd rather write a separate script to handle this without making NanoPlot too complicated. This script would then take both alignment information and the original summary file generated by albacore to get the time at sequencing.

So after basecalling, you align all reads against your pathogen genome to generate one alignment? Or do you also align against the host genome?

**Comment by damientully** [comment]
Correct, we align against the pathogen genome to generate an alignment file.

**Comment by wdecoster** [comment]
The cumulative yield plot with reads instead of gigabases should be added when you update the nanoplotter submodule to version 0.30.0

    pip install nanoplotter -U

I'll look into the second request, probably later this week.

**Comment by damientully** [comment]
Thanks Wouter. Nice..that worked!

**Comment by wdecoster** [comment]
For your second querstion, I just pushed nanoretrotect to PyPI and GitHub, see https://github.com/wdecoster/nanoretrotect

It's immature but works for my test case, looking forward to your feedback.
Please open an issue on that repository if you have issues/feature requests/suggestions.
