### ISSUE TITLE
conda installed NanoPlot crashing

### ISSUE THREAD

**Issue by michaelbroe** [wdecoster/NanoPlot#41]
NanoPlot is crashing on my latest data file. I have run this before successfully, but this is a new installation against a fresh installation of miniconda3. 

fastq file is 237M.

Log file follows.

`2018-01-16 14:45:24,368 NanoPlot 1.2.2 started with arguments Namespace(alength=False, bam=None, barcoded=False, color='#4CB391', downsample=None, drop_outliers=False, fastq=['fastq_runid_21b7fb54589a62a4e512bee4fc22daaa2cbaffc4.fastq'], fastq_minimal=None, fastq_rich=None, format='png', listcolors=False, loglength=False, maxlength=None, minqual=None, no_N50=False, outdir='NanoPlot', pickle=None, plots=['kde', 'pauvre'], prefix='', readtype='1D', report=False, store=False, summary=None, threads=16, verbose=False)
2018-01-16 14:45:24,368 Python version is: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
2018-01-16 14:45:24,392 Nanoplotter: valid output format png
2018-01-16 14:45:24,408 Nanoget: Starting to collect statistics from plain fastq file.
2018-01-16 14:46:03,116 Nanoget: Gathered all metrics of 11091 reads
2018-01-16 14:46:03,118 string indices must be integers
Traceback (most recent call last):
  File "/mnt/data/broe.1/local/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 60, in main
    nanomath.write_stats(datadf, settings["path"] + "NanoStats.txt")
  File "/mnt/data/broe.1/local/miniconda3/lib/python3.6/site-packages/nanomath/nanomath.py", line 121, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/mnt/data/broe.1/local/miniconda3/lib/python3.6/site-packages/nanomath/nanomath.py", line 121, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/mnt/data/broe.1/local/miniconda3/lib/python3.6/site-packages/nanomath/nanomath.py", line 30, in __init__
    self.number_of_bases = np.sum(df["lengths"])
TypeError: string indices must be integers`

Cheers!

**Comment by wdecoster** [comment]
Hi,

That looks like a version incompatibility between the nanomath submodule and NanoPlot itself. I'll try to update the conda modules as soon as possible. Using pip for installation should work, but I agree that conda is pretty convenient.

Cheers,  
Wouter

**Comment by michaelbroe** [comment]
That's it:

`$ python -c "import nanomath ; print(nanomath.__version__)"`
`0.16.2`

**Comment by wdecoster** [comment]
Oh, what about NanoPlot itself then?
For that you can use:

    NanoPlot -v

**Comment by michaelbroe** [comment]
`$ NanoPlot -v`
`NanoPlot 1.2.2`

**Comment by wdecoster** [comment]
Looks like the NanoPlot itself is outdated but update through bioconda is ongoing (see https://github.com/bioconda/bioconda-recipes/pull/7274)

The pip NanoPlot is at 1.8.1. I'll ask the bioconda team for help :)

**Comment by michaelbroe** [comment]
Uninstalled conda version, installed pip version against existing conda packages: all good. Thanks! Be nice to get conda version updated though...

**Comment by wdecoster** [comment]
Yes absolutely. Essentially, the build recipe for the new version is created, but since it has to go through automatic testing at Travis CI (which is currently very very slow) the latest version of NanoPlot (and NanoComp) are held back. Nanomath already got updated, but is now out of sync.

Please let me know if you encounter issues or have suggestions/feature requests!

**Comment by wdecoster** [comment]
(Bio)conda NanoPlot should be back in sync, with thanks to @druvus !

**Comment by michaelbroe** [comment]
Good stuff! If bioconda were always bleeding edge it would be perfect :)

Thanks,
Michael

On Jan 18, 2018, 3:07 AM -0500, Wouter De Coster <notifications@github.com>, wrote:

(Bio)conda NanoPlot should be back in sync, with thanks to @druvus<https://github.com/druvus> !

**Comment by Vojczech** [comment]
Conda 4.3.31 is giving me 

```
$ conda install NanoPlot
Fetching package metadata ...........

PackageNotFoundError: Packages missing in current channels:
            
  - nanoplot

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/main/linux-32
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-32
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-32
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-32
  - https://repo.continuum.io/pkgs/pro/noarch
```

Is there any fix? Maybe this is connected with this thread. Thank you.

**Comment by wdecoster** [comment]
I guess you don't have the bioconda channel selected,

either look [here](https://bioconda.github.io/#set-up-channels) or try the following

    conda install -c bioconda nanoplot

**Comment by wdecoster** [comment]
I now see you are searching in 32 bit channels for NanoPlot, is that
intentional (due to your computer architecture) or a mistake during
installation?

Op 27 jan. 2018 17:15 schreef "Vojczech" <notifications@github.com>:
