### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Kirk3gaard** [wdecoster/NanoPlot#42]
Hi

Is it possible that there can be an option to report the read quality as a percentage rather than a phred score?

**Comment by wdecoster** [comment]
Hi,

Theoretically, that's absolutely possible. Are you talking about a specific plot in which you think changing this would be interesting, or rather in general? Note that the percent identity compared to the reference genome (~scaled edit distance) is already used for plotting in the case of a bam file, but that's not what sufficient?

Cheers,
Wouter

**Comment by Kirk3gaard** [comment]
Hi Wouter

Wow that was a quick reply. I think it would be nice as a general option when just providing a fastq file as input (without any reference alignment).

Best regards Rasmus

**Comment by wdecoster** [comment]
Alright, this shouldn't be too hard to implement. Thanks for your suggestion!

**Comment by wdecoster** [comment]
Hi Rasmus,

NanoPlot 1.9.0 (available on PyPI) has a `--percentqual` flag which will convert Phred quality to "theoretical" percent quality. I did not edit all axis labels to reflect this new quality measure, partially because I think it's obvious and partially because it's a bit more work.

Can you check if this is as you had in mind?

Cheers,
Wouter

**Comment by Kirk3gaard** [comment]
Hi Wouter

That sounds great, I think that simply changing the tick labels in the plots to the theoretical percent identity would be sufficient. I will ask my sysadmin to update NanoPlot when they have the time. 

Thank you very much.

Best regards
Rasmus Kirkegaard

**Comment by wdecoster** [comment]
This is how it looks like now, for example on a dot plot:

![lengthvsqualityscatterplot_dot](https://user-images.githubusercontent.com/11660522/35100902-ce996e2c-fc5d-11e7-9772-c13b6f25956e.png)

Please let me know if you more suggestions on how to improve NanoPlot.

Cheers,
Wouter
