### ISSUE TITLE
Barcoding Metrics

### ISSUE THREAD

**Issue by tcarlile** [wdecoster/NanoPlot#44]
Great package, it does a much better job than the scripts that I wrote to do the same thing. Would it be possible to add some plots for barcoding information (e.g. a bar plot of numbers of each detected barcode, and number of unclassified barcodes). I've been generating these on my end from the summary file.

**Comment by wdecoster** [comment]
Could you check if NanoComp (https://github.com/wdecoster/nanocomp/) with --barcoded does what you have in mind?

**Comment by tcarlile** [comment]
I was thinking more about a simple barchart that gives you the breakdown of how many reads were assigned to each barcode based. https://imgur.com/1lNzUY4 is my implementation in python.

**Comment by wdecoster** [comment]
That's one of the output plots of NanoComp for a barcoded summary file.

**Comment by wdecoster** [comment]
e.g. ![nanocomp_number_of_reads](https://user-images.githubusercontent.com/11660522/35264266-5f724a1a-001c-11e8-83b5-ae0a38be5e8e.png)

**Comment by tcarlile** [comment]
That's exactly what I was wanting. I didn't see it in the example plots, and didn't have a chance to run nanocomp on my data. Thanks!

**Comment by wdecoster** [comment]
Yes, I should update the examples :-)

If you have more suggestions/feature requests then please let me know!
