### ISSUE TITLE
NanoP

### ISSUE THREAD

**Issue by gwaldbieser** [wdecoster/NanoPlot#46]
Hi Wouter,
I'm running NanoPlot on OpenSUSELeap and receive an error during the analysis. It still produces graphs.
I've attached the log file.

**Command**
# NanoPlot --summary HybSC17L30_1ug_20180209/sequencing_summary_*.txt HybSC17L30_1ugB_20180209/sequencing_summary_*.txt --loglength -o plot2test &

**Written output**
# ll plot2test/
total 492
-rw-r--r-- 1 root root  24688 Feb 12 16:23 ActivityMap_ReadsPerChannel.png
-rw-r--r-- 1 root root  24298 Feb 12 16:23 CumulativeYieldPlot_Gigabases.png
-rw-r--r-- 1 root root  28445 Feb 12 16:23 CumulativeYieldPlot_NumberOfReads.png
-rw-r--r-- 1 root root  20582 Feb 12 16:22 HistogramReadlength.png
-rw-r--r-- 1 root root 250491 Feb 12 16:23 Log_LengthvsQualityScatterPlot_dot.png
-rw-r--r-- 1 root root  53410 Feb 12 16:23 Log_LengthvsQualityScatterPlot_kde.png
-rw-r--r-- 1 root root  20277 Feb 12 16:22 LogTransformed_HistogramReadlength.png
-rw-r--r-- 1 root root   6438 Feb 12 16:23 NanoPlot_20180212_1622.log
-rw-r--r-- 1 root root   1031 Feb 12 16:22 NanoStats.txt
-rw-r--r-- 1 root root  27010 Feb 12 16:22 Weighted_HistogramReadlength.png
-rw-r--r-- 1 root root  21550 Feb 12 16:23 Weighted_LogTransformed_HistogramReadlength.png

--------------------------------------------------------
**Error message:**
# /root/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j

If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/root/anaconda3/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 86, in main
    plots = make_plots(datadf, settings)
  File "/root/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 379, in make_plots
    title=settings["title"])
  File "/root/anaconda3/lib/python3.5/site-packages/nanoplotter/nanoplotter.py", line 324, in time_plots
    labels=labels)
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/tools/tile.py", line 96, in cut
    mn, mx = [mi + 0.0 for mi in rng]
  File "/root/anaconda3/lib/python3.5/site-packages/pandas/tools/tile.py", line 96, in <listcomp>
    mn, mx = [mi + 0.0 for mi in rng]
TypeError: unsupported operand type(s) for +: 'Timedelta' and 'float'

[NanoPlot_20180212_1622.log](https://github.com/wdecoster/NanoPlot/files/1717780/NanoPlot_20180212_1622.log)

**Comment by wdecoster** [comment]
Hi gwaldbieser,

Thank you for reporting this. Could you have a look at your pandas version? 
From the command line you can do that with:
    python -c "import pandas ; print(pandas.__version__)"

The latest version is 0.22.0. If yours is (a lot older) I would suggest updating. Not sure if that explains it, but it might. 

If that doesn't make a difference would you mind sharing your data using the `--store` argument of NanoPlot? That will create a NanoPlot-data.pickle file, which contains the information for plotting (read lengths, qualities, time of sequencing, the channel used for sequencing,... but not the actual read sequence).

Cheers,
Wouter

**Comment by gwaldbieser** [comment]
We updated pandas to 0.22 and reran. BTW, I'm running as root:

$ NanoPlot --summary HybSC17L30_1ug_20180209/sequencing_summary_*.txt HybSC17L30_1ugB_20180209/sequencing_summary_*.txt --loglength -o plot5test --store & 
-------------------------------------------------------------
Error messages

/root/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
/root/anaconda3/lib/python3.5/site-packages/seaborn-0.7.1-py3.5.egg/seaborn/categorical.py:588: FutureWarning: remove_na is deprecated and is a private function. Do not use.
  kde_data = remove_na(group_data)

[1]+  Done                    NanoPlot --summary HybSC17L30_1ug_20180209/sequencing_summary_*.txt HybSC17L30_1ugB_20180209/sequencing_summary_*.txt --loglength -o plot5test --store
-------------------------------------------------------------
Output
$ ll plot5test
total 4232
-rw-r--r-- 1 root root   24688 Feb 12 17:16 ActivityMap_ReadsPerChannel.png
-rw-r--r-- 1 root root   24458 Feb 12 17:16 CumulativeYieldPlot_Gigabases.png
-rw-r--r-- 1 root root   28406 Feb 12 17:16 CumulativeYieldPlot_NumberOfReads.png
-rw-r--r-- 1 root root   20582 Feb 12 17:16 HistogramReadlength.png
-rw-r--r-- 1 root root  250491 Feb 12 17:16 Log_LengthvsQualityScatterPlot_dot.png
-rw-r--r-- 1 root root   53410 Feb 12 17:16 Log_LengthvsQualityScatterPlot_kde.png
-rw-r--r-- 1 root root   20277 Feb 12 17:16 LogTransformed_HistogramReadlength.png
-rw-r--r-- 1 root root    5722 Feb 12 17:17 NanoPlot_20180212_1716.log
-rw-r--r-- 1 root root 3014495 Feb 12 17:16 NanoPlot-data.pickle
-rw-r--r-- 1 root root  744867 Feb 12 17:17 NanoPlot-report.html
-rw-r--r-- 1 root root    1031 Feb 12 17:16 NanoStats.txt
-rw-r--r-- 1 root root   32107 Feb 12 17:16 TimeLengthViolinPlot.png
-rw-r--r-- 1 root root   33038 Feb 12 17:16 TimeQualityViolinPlot.png
-rw-r--r-- 1 root root   27010 Feb 12 17:16 Weighted_HistogramReadlength.png
-rw-r--r-- 1 root root   21550 Feb 12 17:16 Weighted_LogTransformed_HistogramReadlength.png



[NanoPlot-data.pickle.txt](https://github.com/wdecoster/NanoPlot/files/1717917/NanoPlot-data.pickle.txt)

**Comment by wdecoster** [comment]
So you now only have warnings (VisibleDeprecationWarning and FutureWarning) but no longer the TypeError from above? I see a `NanoPlot-report.html` which suggests me that the command ran to completion.

There shouldn't be a reason to run it as root, but shouldn't cause problems either.

**Comment by gwaldbieser** [comment]
Very cool. Thanks for your help. Enjoy the Olympics!
Geoff

**Comment by wdecoster** [comment]
I'm glad that it wasn't too hard to fix this problem! Please let me know if you encounter further issues or have suggestions/feature requests.

Cheers,
W

**Comment by gwaldbieser** [comment]
I really like this package. Thanks for all your work on it.
FYI, NanoPlot seems to run to completion but I receive this error now at the end of the run. All the graphs print.

/root/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
/root/anaconda3/lib/python3.5/site-packages/seaborn-0.7.1-py3.5.egg/seaborn/categorical.py:588: FutureWarning: remove_na is deprecated and is a private function. Do not use.
 kde_data = remove_na(group_data)

**Comment by wdecoster** [comment]
That's not really an error, rather a warning. Could you check your seaborn version using the following command?

    python -c "import seaborn ; print(seaborn.__version__)"


Based on the warning it seems to be 0.7.1, and if so could you try if updating solves these warnings?

    pip install seaborn -U

**Comment by gwaldbieser** [comment]
It was 0.7.1, upgraded to 0.8.1.
NanoPlot -t 32 --summary HybRADb_20180124/*.txt  --loglength -o TestHybRADbPlots

/root/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j

I can live with that.
Thanks!
