### ISSUE TITLE
Axis and title in percent identity graphs

### ISSUE THREAD

**Issue by AnjuniPeiris** [wdecoster/NanoPlot#48]
Hi, thanks for the great piece of software. The graphs named bamPercentIdentityvsAverageBaseQuality_dot and bamPercentIdentityvsAverageBaseQuality_kde had a mistake in their title and axes. They say read quality instead of average base quality. Just wanted to suggest changing them for consistency.

**Comment by wdecoster** [comment]
Thanks for reporting this, I will look into it!

**Comment by wdecoster** [comment]
The names have been adapted in NanoPlot 1.10.3, which I just pushed to PyPI.

Cheers,
Wouter
