### ISSUE TITLE
NanoPlot: error: unrecognized arguments: --fasta

### ISSUE THREAD

**Issue by mictadlo** [wdecoster/NanoPlot#49]
Hi, 
I have got the following error:
```
NanoPlot -t 4 -f png --summary m160911_001544_42229_c101105112550000001823259804261791_s1_p0.fasta.summary --title m160911_001544_42229_c101105112550000001823259804261791_s1_p0.fasta --fasta /work/waterhouse_team/All_RawData/Each_Cell_Raw/RSII_SMRT14/Analysis_Results/m160911_001544_42229_c101105112550000001823259804261791_s1_p0.fasta
usage: NanoPlot [-h] [-v] [-t THREADS] [--verbose] [--store] [--raw]
                [-o OUTDIR] [-p PREFIX] [--maxlength N] [--minlength N]
                [--drop_outliers] [--downsample N] [--loglength] [--alength]
                [--minqual N] [--readtype {1D,2D,1D2}] [--barcoded] [-c COLOR]
                [-f {eps,jpeg,jpg,pdf,pgf,png,ps,raw,rgba,svg,svgz,tif,tiff}]
                [--plots [{kde,hex,dot,pauvre} [{kde,hex,dot,pauvre} ...]]]
                [--listcolors] [--no-N50] [--title TITLE]
                (--fastq file [file ...] | --fastq_rich file [file ...] | --fastq_minimal file [file ...] | --summary file [file ...] | --bam file [file ...] | --cram file [file ...] | --pickle pickle)
NanoPlot: error: unrecognized arguments: --fasta /work/waterhouse_team/All_RawData/Each_Cell_Raw/RSII_SMRT14/Analysis_Results/m160911_001544_42229_c101105112550000001823259804261791_s1_p0.fasta
```

What did I miss?

Thank you in advance.

Michal

**Comment by wdecoster** [comment]
Which version do you have installed?

    NanoPlot -v

Fasta input was added in 1.10.0

**Comment by mictadlo** [comment]
I used `conda install nanoplot` which installed 1.8.1. Do you have any plans to update bioconda?

**Comment by wdecoster** [comment]
Right, the conda installation may lag behind, pip is up to date. Usually @druvus updates the conda package, I'll have a look.

**Comment by druvus** [comment]
I have unfortunately not done it recently

**Comment by wdecoster** [comment]
I will try in about 12 hours to fix it but bioconda made some changes to the workflow as far as I know so I need to see how things go now. Sorry for the inconvenience!

**Comment by wdecoster** [comment]
I'm updating the NanoPack scripts and modules (https://github.com/bioconda/bioconda-recipes/pull/8134) but I'll need some help of the bioconda team. I'll keep you posted.

**Comment by wdecoster** [comment]
Should be fixed now! Thanks to @druvus

Please let me know if you have any further issues or suggestions/feature requests.
