### ISSUE TITLE
'module' object has no attribute 'CSS4_COLORS'

### ISSUE THREAD

**Issue by maquezaihou** [wdecoster/NanoPlot#5]
Hi Wdecoster, I'm having this error when I run NanoPlot in the server:
File "/home/XX/.local/lib/python2.7/site-packages/nanoplotter/nanoplotter.py", line 22, in checkvalidColor
    if color in list(mcolors.CSS4_COLORS.keys()) + ["#4CB391"]:
AttributeError: 'module' object has no attribute 'CSS4_COLORS'

Wonder if you have any insight? Thank you for your time.

**Comment by wdecoster** [comment]
Hi maquezaihou,

Thanks for reporting this. My first guess would be that you have an older version of matplotlib, could you check it's version using the following command?

```
python -c "import matplotlib ; print(matplotlib.__version__)"
```

I think upgrading matplotlib should solve this.

```
pip install matplotlib --upgrade
```

Cheers,
Wouter

**Comment by maquezaihou** [comment]
You are absolutely right! I updated matplotlib, and now it is working! Thank you very much!

**Comment by wdecoster** [comment]
Good to hear! I'll make sure to specify the minimal version of matplotlib for pip installation to avoid this error in the future.
