### ISSUE TITLE
NanoPlot Crashed

### ISSUE THREAD

**Issue by shenuhcide** [wdecoster/NanoPlot#52]
I used this command:
`NanoPlot -t 2 -f pdf -o figs --fastq_rich all_dlon_nanopore.fastq.gz --minlength 1000`

Before it crashed, NanoPlot reported this warning:

> /home/Sheina/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py:6448: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
>   warnings.warn("The 'normed' kwarg is deprecated, and has been "
> /home/Sheina/anaconda3/lib/python3.5/site-packages/pandas/core/series.py:696: FutureWarning:
> Passing list-likes to .loc or [] with any missing label will raise
> KeyError in the future, you can use .reindex() as an alternative.
> 
> See the documentation here:
> http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
>   return self.loc[key]

NanoPlot wrote the following files before crashing:

- HistogramReadlength.pdf
- MinLength-1000_LengthvsQualityScatterPlot_dot.pdf
- NanoStats.txt
- Weighted_LogTransformed_HistogramReadlength.pdf
- LogTransformed_HistogramReadlength.pdf
- Weighted_HistogramReadlength.pdf

Here's the Traceback:

> Traceback (most recent call last):
>   File "/home/Sheina/anaconda3/bin/NanoPlot", line 11, in <module>
>     sys.exit(main())
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 86, in main
>     plots = make_plots(datadf, settings)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 359, in make_plots
>     title=settings["title"])
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/nanoplotter/nanoplotter.py", line 201, in scatter
>     size=10)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/seaborn/axisgrid.py", line 2275, in jointplot
>     grid.plot_marginals(kdeplot, **marginal_kws)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/seaborn/axisgrid.py", line 1780, in plot_marginals
>     func(self.x, **kwargs)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 657, in kdeplot
>     cumulative=cumulative, **kwargs)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 273, in _univariate_kdeplot
>     cumulative=cumulative)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 345, in _statsmodels_univariate_kde
>     kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 146, in fit
>     clip=clip, cut=cut)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 506, in kdensityfft
>     f = revrt(zstar)
>   File "/home/Sheina/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py", line 20, in revrt
>     y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
> TypeError: slice indices must be integers or None or have an __index__ method

[NanoPlot_20180308_1347.log](https://github.com/wdecoster/NanoPlot/files/1795410/NanoPlot_20180308_1347.log)

**Comment by wdecoster** [comment]
Hi, 

Thanks for reporting this. 

Your issue looks similar to https://github.com/wdecoster/NanoPlot/issues/21#issuecomment-340665698

Can you see if the solution proposed in that thread works for you? 

I'll also have a look at the warnings. 

Wouter

**Comment by shenuhcide** [comment]
Hi Wouter,

Thanks for your response. Yes, updating stats models fixed it and it finished. I got a different warning though, this time about a missing symbol (I left the screen and cannot see the warning anymore though).

Thanks!
Sheina
