### ISSUE TITLE
Stats Filtering

### ISSUE THREAD

**Issue by pgtb** [wdecoster/NanoPlot#55]
Hi wouter !
As discussed by mail, I will be glad if can enhance nanoplot by adding a stats table according to filtering.
eg : number of reads and bases over Q9 mean quality and over a specified reads lenght.
According to barcodes division too would be very great.

thanks a lot

Christophe

**Comment by wdecoster** [comment]
Hi Christophe,

I'll update NanoPlot to get both a stats report before and after applying filters. Note that on the command line you already have the option to deal with barcoded summaries, which is not exposed to the webtool for keeping things simple. But this is not impossible either. (Tagging @svennd )
Although I can wholeheartedly recommend getting comfortable with the command line, which will give you so much more options and I'd be happy to help. This [tutorial from codecademy](https://www.codecademy.com/learn/learn-the-command-line) is a rookie-friendly way to get started and learn the basic commands.

In addition to NanoPlot, you can also have a look at [NanoStats](https://github.com/wdecoster/nanostat) and [NanoComp](https://github.com/wdecoster/nanocomp), which both can handle barcoded summaries and provide comparisons. 

Cheers,
Wouter

**Comment by svennd** [comment]
Not impossible, but the webtool was mainly build as a preview for nanoplot. With increasing output (and summary size) for minion/gridion/promethion, the limits of what is viable to upload are closing in fast. When flongle and smidgeon are out (or we get our hands on it) it might be useful to re-evaluate this, as those outputs will be more manageable and analyse on-the-road are more applicable.

**Comment by wdecoster** [comment]
After updating to v1.11.0, NanoPlot will create another stats summary if any filters were applied to the data. The web NanoPlot will be updated in the following days.

Thanks for your suggestion, and please let me know if you have additional feature requests!
