### ISSUE TITLE
Average reads quality score axis

### ISSUE THREAD

**Issue by homeveg** [wdecoster/NanoPlot#57]
Hello

First of all, thanks for a excellent tool!  
I have some pretty strange problem with the visualization.
The data I am analyzing is slightly untypical - it's a cfDNA (trherefore a relatively short fragments). We pre-processing it first with Porchop, to trim adapter sequence, and than with the BBDuk, to set a filter on fragment length and average reads quality score. If one should set up a fixed threshold is a different question, but the reason I am writing is that on "Read lengths vs Average read quality plot " of such quality score-trimmed data always having a shift on "Average read quality" axis by 0.5. 

Please see below  plots for non-trimmed and trimmed data:

**Non-trimmed**

![image](https://user-images.githubusercontent.com/13424939/37820323-8f153f88-2e80-11e8-86ec-cb7a22f95f0f.png)

**Length/Quality-score trimmed  (q-score = 10)**

![image](https://user-images.githubusercontent.com/13424939/37820361-ade34e28-2e80-11e8-9085-01fc354951f6.png)

I've tested a mean quality score with different tools, and never got a value below defined threshold.  
Here for example is the visualization from classical FastQC:

**Per base sequence quality**

![image](https://user-images.githubusercontent.com/13424939/37820490-0e8102fc-2e81-11e8-9917-aac76584d92c.png)

**Per sequence quality scores**

![image](https://user-images.githubusercontent.com/13424939/37820416-d5f232da-2e80-11e8-98a4-4cf45e2f163d.png)

Just in case, I am attaching logs for both, trimmed and non-trimmed data
[trimmed.log](https://github.com/wdecoster/NanoPlot/files/1840813/trimmed.log)
[non_trimmed.log](https://github.com/wdecoster/NanoPlot/files/1840818/non_trimmed.log)

**Comment by wdecoster** [comment]
Hi homeveg,

Thanks for reporting this. I'm a bit puzzled at first. Could you try with your unfiltered data and use --minqual 10 in NanoPlot? That could already tell us something about if this is a visualization or a calculation issue.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Next thought: you could also perform minimum quality filter using [NanoFilt](https://github.com/wdecoster/nanofilt), which uses the same average-quality calculation as NanoPlot.

Note that calculating the average base call quality of a read is not equal to summing the quality scores and dividing by the number of reads: [blog post](https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/)

I'm not sure how BBDuk does average quality score math. I can ask the developer if we figure out more.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Next thought: your trimmed dataset looks quite different from the first: you suddenly have average read qualities above 16?

**Comment by homeveg** [comment]
Thanks for answers! 

Regarding the last question - yes, you are right. With the BBDuk we do the following:
- remove first 20 bases from the left and keep only reads from 50 to 2000 bases long.
- perform quality-based trimming and keep only reads with mean q-score above or equal to 10

Here is the corresponding plot, when using as an input non-trimmed data, but using "--minqual 10" option

![image](https://user-images.githubusercontent.com/13424939/37822535-0979d53a-2e87-11e8-9048-813d269bf1a2.png)

And the log file:

[test_thresholdQ10.log](https://github.com/wdecoster/NanoPlot/files/1840977/test_thresholdQ10.log)

Now I am puzzled too...

**Comment by wdecoster** [comment]
I'll try to contact the BBduk maintainer and see what he thinks.

**Comment by homeveg** [comment]
I've just made a test  with NanoFilt, as you suggested. I used it with the following parameters:
`
cat non_trimmed.fastq | NanoFilt -q 10 -l 50 --headcrop 20 --tailcrop 20 --readtype 1D > NanoFilt_trimmed-reads.fastq
`
Comparing statistics for non-trimmed, but filtered with NonoPlot directly with the NanoFilt trimmed data, we see results are pretty similar (as trey suppose to be) but images and, therefore, underlying dataset, is very different. If the BBDuk trimming does not change distribution, the NanoFilt does

Here is the results of NanoPlot:

![image](https://user-images.githubusercontent.com/13424939/37823774-c4c9bdfc-2e8a-11e8-85e8-8026f770160a.png)

**Comment by wdecoster** [comment]
> Comparing statistics

Do you mean the NanoStats file? If you have a slightly-old NanoPlot version you get only one NanoStats file containing non-filtered metrics, but the latest version(s) should give you both stats from before and after applying filters.

**Comment by homeveg** [comment]
no, i was refering to the overview statistics at the top of  HTML report
[test_NanoStats.txt](https://github.com/wdecoster/NanoPlot/files/1841117/test_NanoStats.txt)

**Comment by wdecoster** [comment]
Oh, but that's the same as the NanoStats file. It just gets converted to some (sloppy) html.

Two stats reports are included if you apply a filter since NanoPlot 1.11.0

**Comment by homeveg** [comment]
I've just upgraded a NanoPlot to the latest version - plots looks the same. I guess, the isuue is with the way how does BBDuk is calculating a mean q-score.

**Comment by bbushnell** [comment]
BBDuk calculates average quality score by converting to probability scale, taking an average, and then converting back to Phred scale.  So for example, a 2bp read with quality scores 10 and 20 would yield an average quality of (0.9+0.99)/2=0.945 -> Q12.6 rather than Q15 with a linear average.

The reason for the 0.5 offset is because BBDuk is rounding the average quality to an int before comparing it to the threshold.  I could change it to a float; there's no particular reason for the rounding.

**Comment by wdecoster** [comment]
Thanks for the info!

**Comment by homeveg** [comment]
@bbushnell, thanks for such detailed answer!
I think, it's a good idea to make comparison working without rounding to integer because otherwise filtering results slightly misleading. Setting a fixed threshold is already kind of a tricky decision and one would like to be sure it works exactly in the way it suppose - discard everything below it.
Anyway, for a current project we are going to use thee BBDuk for a quality-score based trimming to make results more compatible to our previous data. Thanks once more  and therefore it is very important for me to understand what's going with the filtering.

**Comment by homeveg** [comment]
@wdecoster, thanks for your help! Once more, great tool!

**Comment by wdecoster** [comment]
Thanks! So case solved?

**Comment by homeveg** [comment]
yes!

**Comment by wdecoster** [comment]
Let me know if you have any further questions or suggestions!
