### ISSUE TITLE
ImportError: No module named concurrent.futures

### ISSUE THREAD

**Issue by shlomobl** [wdecoster/NanoPlot#58]
Hi,

I'd appreciate some help, please. I got this error when running NanoPlot:

NanoPlot --raw -o ./NanoPlot --fastq VL2874_HMW_MinKnow_NanoLyse.fastq 
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

My computer runs Ubuntu 16.04 with both Python 2.7 AND 3.5. How can I make NanoPlot find Python3?

Thanks!

**Comment by wdecoster** [comment]
Hi,

You should make sure you install it using the correct Python version. Did you use pip for installation?

If so:

You can check which installation of pip was used, it probably was the Python2.7 pip, using:

`which pip`

This will tell you where your pip executable is. If it's in a Python2.7 directory, it's wrong.

On some systems you have a `pip3` which will make sure the pip from python3 is used for the installation:

`pip3 install NanoPlot`

To be entirely sure that the correct python is used, you can also use this:

`python3 -m pip install NanoPlot`

Is the python3 a user/local installation and the python2.7 the system installed version? In that case I would suggest you adapt your $PATH to make sure python3/pip3 is always used first.

Cheers,
Wouter

**Comment by shlomobl** [comment]
Hi,

Thanks for the reply. I trying the following option

> sudo -H python3 -m pip install NanoPlot

And this is what I got :-\

Collecting NanoPlot
  Using cached NanoPlot-1.13.0.tar.gz
Collecting biopython (from NanoPlot)
  Using cached biopython-1.71-cp35-cp35m-manylinux1_x86_64.whl
Collecting pysam>0.10.0.0 (from NanoPlot)
  Using cached pysam-0.14.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pandas>=0.22.0 (from NanoPlot)
  Using cached pandas-0.22.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy (from NanoPlot)
  Using cached numpy-1.14.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting scipy (from NanoPlot)
  Using cached scipy-1.0.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting python-dateutil (from NanoPlot)
  Using cached python_dateutil-2.7.2-py2.py3-none-any.whl
Collecting seaborn (from NanoPlot)
  Using cached seaborn-0.8.1.tar.gz
Collecting nanoplotter>=0.36.0 (from NanoPlot)
  Using cached nanoplotter-0.36.0.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /tmp/pip-install-68m_pr12/nanoplotter/.eggs/setuptools-39.0.1-py3.5.egg
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-68m_pr12/nanoplotter/setup.py", line 42, in <module>
        package_dir={'nanoplotter': 'nanoplotter'})
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-68m_pr12/nanoplotter/

**Comment by wdecoster** [comment]
Could you updating `setuptools` first, then try again?

    sudo -H python3 -m pip install setuptools -U
