### ISSUE TITLE
AttributeError: module 'nanoget' has no attribute 'processSumary'

### ISSUE THREAD

**Issue by devindrown** [wdecoster/NanoPlot#6]
Getting the above error when trying to plot data based on sequencing summary using NanoPlot 0.14.0

Command: `$ NanoPlot --summary sequencing_summary.txt`
Output
```
Traceback (most recent call last):
  File "/home/dmdrown/.local/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/dmdrown/.local/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 46, in main
    datadf, lengthprefix, logBool, readlengthsPointer = getInput(args)
  File "/home/dmdrown/.local/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 146, in getInput
    datadf = nanoget.processSumary(args.summary)
AttributeError: module 'nanoget' has no attribute 'processSumary'
```
I think there is a typo on line 146, missing an letter

**Comment by devindrown** [comment]
This was already fixed. Sorry

**Comment by wdecoster** [comment]
Well yes there was a typo. I'm not sure if it was okay in the 0.14.0 version so your error makes sense. I think I messed up there in keeping the packages in sync. But it should be fixed if you have the current latest version of NanoPlot (0.14.2) and nanoget (0.10.6).

I just made sure that NanoPlot depends on nanoget=>0.10.6 so things should be alright now.
