### ISSUE TITLE
using bam as an input for NanoPlot

### ISSUE THREAD

**Issue by homeveg** [wdecoster/NanoPlot#63]
I was trying to run NanoPlot with BAM file, which was generated using BWA MEM | samtools :

`
bwa mem -x ont2d Homo_sapiens.GRCh38.80.dna.primary_assembly.fa QCtrimmed.fastq -t 100 | samtools view -S -F 4 -b - > QCtrimmed.mapped.bam
`

After sorting the BAM file with "samtools sort  QCtrimmed.mapped.bam" I used it as an input for a NanoPlot:

`
NanoPlot --bam QCtrimmed.mapped.sorted.bam -t 100 --maxlength 2000 -o out/NanoPlot/human --readtype 1D -p QCtrimmed
`

The NanoPlot crashed with the following exception:

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib64/python3.5/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib64/python3.5/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.5/site-packages/nanoget/nanoget.py", line 259, in process_bam
    samfile = check_bam(bam)
  File "/usr/lib/python3.5/site-packages/nanoget/nanoget.py", line 233, in check_bam
    if not samfile.header['HD']['SO'] == 'coordinate':
  File "pysam/libcalignmentfile.pyx", line 540, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
KeyError: 'HD'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/NanoPlot", line 11, in <module>
    load_entry_point('NanoPlot==1.13.0', 'console_scripts', 'NanoPlot')()
  File "/usr/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 62, in main
    barcoded=args.barcoded)
  File "/usr/lib/python3.5/site-packages/nanoget/nanoget.py", line 74, in get_input
    dfs=[out for out in executor.map(extration_function, files)],
  File "/usr/lib/python3.5/site-packages/nanoget/nanoget.py", line 74, in <listcomp>
    dfs=[out for out in executor.map(extration_function, files)],
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib64/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
KeyError: 'HD'

**Comment by wdecoster** [comment]
Does your bam file have a proper header? What's the result of `samtools index QCtrimmed.mapped.sorted.bam`? Can you show some lines of `samtools view QCtrimmed.mapped.sorted.bam | less -S`?

**Comment by homeveg** [comment]
I guess, the issue may be with the Samtools version or BWA itself, because the "@HD VN: SO:coordinates" line is not present in the header. I'll try to add this line manually
hear is few lines from header:

samtools view -H QCtrimmed.mapped.sorted.bam 
@SQ	SN:1	LN:248956422
@SQ	SN:10	LN:133797422
@SQ	SN:11	LN:135086622
...
@SQ	SN:KI270728.1	LN:1872759
@SQ	SN:KI270727.1	LN:448248
@SQ	SN:KI270442.1	LN:392061
...
@PG	ID:bwa	PN:bwa	VN:0.7.17-r1194-dirty	CL:bwa mem -x ont2d Homo_sapiens.GRCh38.80.dna.primary_assembly.fa QCtrimmed.fastq -t 100

samtools view QCtrimmed.mapped.sorted.bam | head
DGKHT8Q1:251:H7HK3BCX2:1:2111:1121:27510        163     chr10   3100001 60      54S87M8S        =       3100001 150     GACTCCAGAAAATCAAATAACCCCATTAAAAAATGGGGCTCAGAGCTGAACAAAGAATTCTCACCTGAGA
DGKHT8Q1:251:H7HK3BCX2:2:1103:17723:70629       163     chr10   3100001 60      14S136M =       3100001 150     CAGAGCTGAACAAAGAATTCTCACCTGAGAAATACCGAATGGCAGAGAAACACCTGAATAAAATGTTCAACATCCTTA
DGKHT8Q1:251:H7HK3BCX2:2:1211:19818:60479       163     chr10   3100001 60      33S117M =       3100001 150     CCCATTAAAAAATGGGGCTCAGAGCTGAACAAAGAATTCTCACCTGAGAAATACCGAATGGCAGAGAAACACCTGAAT
DGKHT8Q1:251:H7HK3BCX2:1:1104:8975:44753        147     chr10   3100001 60      5S145M  =       3100001 -150    ACAAAGAATTCTCACCTGAGAAATACCGAATGGCAGAGAAACACCTGAATAAAATGTTCAACATCCTTAATCATCAGG
DGKHT8Q1:251:H7HK3BCX2:1:1104:8975:44753        99      chr10   3100001 60      7S143M  =       3100001 150     GAACAAAGAATTCTCACCTGAGAAATACCGAATGGCAGAGAAACACCTGAATAAAATGTTCAACATCCTTAATCATCA

**Comment by wdecoster** [comment]
You should always make sure to use up to date versions, so you indeed may want to check your samtools and bwa.

Using a recent samtools version you also don't need the `-S` flag, and you could also pipe your `samtools view` directly to `samtools sort`.

**Comment by homeveg** [comment]
well, unfortunately, I can't re-install samtools to the latest, and have to use slightly outdated version. But anyway, after I've edited manually the header of the SAM file, everything is working now. 
The issue is closed now. Thanks for you help!

**Comment by wdecoster** [comment]
Good to hear.

If you cannot update samtools because you don't have root permission (which I also don't have) you can install anaconda or miniconda and have samtools installed in your home directory.
