### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bust_9gm/nanoplotter/

### ISSUE THREAD

**Issue by Garryf** [wdecoster/NanoPlot#65]
Hi Ive already tried a few things to update pip , setuptools ect . i get same error when I try to install all packages together. Im quite new to troubleshooting installations so any help appreciated.

The instance I am using is running through the MRC CLIMB system in the UK

My system:
ubuntu@pore4:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

I assume Im installing to Python 3.

I have 2 and 3 installed
ubuntu@pore4:~$ python --version
Python 2.7.12
ubuntu@pore4:~$ python3 --version
Python 3.5.2

**heres the pip install output**
ubuntu@pore4:~$ python3 -m pip install NanoPlot
Collecting NanoPlot
  Using cached https://files.pythonhosted.org/packages/0e/a4/d0c8d1a0997be9a6fb3d84ac8479f09985f816c4df6a1e0f65881a1c38f6/NanoPlot-1.13.0.tar.gz
Collecting biopython (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/63/26/198e369dd95c50554ccc9ec76719be8e338d171fb30c7f14439653cd9153/biopython-1.71-cp35-cp35m-manylinux1_x86_64.whl
Collecting pysam>0.10.0.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/09/a9/d74aa164efb28ce328cd4890b0182ccdf2e781c192910072717c965765c6/pysam-0.14.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pandas>=0.22.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/a5/c1/43966a4ce89d0c64111f46c6364ed57d6d87e6fab7d685dca06197a19cf7/pandas-0.23.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from NanoPlot) (1.11.0)
Collecting scipy (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/cd/32/5196b64476bd41d596a8aba43506e2403e019c90e1a3dfc21d51b83db5a6/scipy-1.1.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from NanoPlot) (2.4.2)
Collecting seaborn (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/10/01/dd1c7838cde3b69b247aaeb61016e238cafd8188a276e366d36aa6bcdab4/seaborn-0.8.1.tar.gz
Collecting nanoplotter>=0.36.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/13/48/111eccfee3c8d5d655ff92afb1307d4f1b6cc5d47d865e815d6c8a21e97a/nanoplotter-0.38.0.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-install-bust_9gm/nanoplotter/.eggs/setuptools-39.2.0-py3.5.egg
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2237, in resolve
        return functools.reduce(getattr, self.attrs, module)
    AttributeError: module 'setuptools.dist' has no attribute 'check_specifier'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bust_9gm/nanoplotter/setup.py", line 43, in <module>
        package_dir={'nanoplotter': 'nanoplotter'})
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python3.5/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2239, in resolve
        raise ImportError(str(exc))
    ImportError: module 'setuptools.dist' has no attribute 'check_specifier'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bust_9gm/nanoplotter

many thanks Garry

**Comment by wdecoster** [comment]
Hi Garry,

I'm at London Calling and will look into this when I'm back home this Sunday.

Wouter

**Comment by wdecoster** [comment]
Can you show the output of

`pip --version`

Based on what I see this looks like an outdated `setuptools` module, but you wrote you already updated this. How? Was this succesful? Which version do you have now?
`
python3 -c "import setuptools ; print(setuptools.__version__)"`

**Comment by Garryf** [comment]
Hi Wouter,

here are the versions of setuptools and pip I have installed. Apologies for the delay!

ubuntu@pore4:~$ python3 -c "import setuptools ; print(setuptools.__version__)"
20.7.0
ubuntu@pore4:~$ pip --version
pip 10.0.1 from /home/ubuntu/.local/lib/python2.7/site-packages/pip (python 2.7)
ubuntu@pore4:~$ pip3 --version
pip 10.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)


thanks

**Comment by wdecoster** [comment]
That setuptools version looks outdated to me. Mine is 39.2.0.

Please try `python3 -m pip install setuptools -U`

**Comment by Garryf** [comment]
Hi,

I updated setuptools,
ubuntu@pore4:~$ python3 -c "import setuptools ; print(setuptools.__version__)"
39.2.0
 and ran :+1: ubuntu@pore4:~$ python3 -m pip install NanoPlot
Collecting NanoPlot
  Using cached https://files.pythonhosted.org/packages/0e/a4/d0c8d1a0997be9a6fb3d84ac8479f09985f816c4df6a1e0f65881a1c38f6/NanoPlot-1.13.0.tar.gz
Collecting biopython (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/63/26/198e369dd95c50554ccc9ec76719be8e338d171fb30c7f14439653cd9153/biopython-1.71-cp35-cp35m-manylinux1_x86_64.whl
Collecting pysam>0.10.0.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/09/a9/d74aa164efb28ce328cd4890b0182ccdf2e781c192910072717c965765c6/pysam-0.14.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pandas>=0.22.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/a5/c1/43966a4ce89d0c64111f46c6364ed57d6d87e6fab7d685dca06197a19cf7/pandas-0.23.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from NanoPlot) (1.11.0)
Collecting scipy (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/cd/32/5196b64476bd41d596a8aba43506e2403e019c90e1a3dfc21d51b83db5a6/scipy-1.1.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from NanoPlot) (2.4.2)
Collecting seaborn (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/10/01/dd1c7838cde3b69b247aaeb61016e238cafd8188a276e366d36aa6bcdab4/seaborn-0.8.1.tar.gz
Collecting nanoplotter>=0.36.0 (from NanoPlot)
  Downloading https://files.pythonhosted.org/packages/8a/f7/2177780d122a291e79593fd2dfca40293bd870ee58f1f8d6600e7e9b8fdb/nanoplotter-0.39.1.tar.gz
Collecting nanoget>=1.4.0 (from NanoPlot)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/0a/b0/ce6f2084b81707462ee43f996883b886b347f818fca2c27797bbf4ff6bd3/nanoget-1.5.0.tar.gz
Collecting nanomath>=0.21.0 (from NanoPlot)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/fb/ee/6beb3383ab67c11472271242bf69efa9653fe06ef14efcca3ec3a469653b/nanomath-0.21.0.tar.gz
Collecting pytz>=2011k (from pandas>=0.22.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 6.9MB/s
Collecting matplotlib (from seaborn->NanoPlot)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/81/31/4e261379e0cd4e9bbacfc96b124ebac0706b44374bd1d34ef899796f741b/matplotlib-2.2.2-cp35-cp35m-manylinux1_x86_64.whl (12.6MB)
    100% |████████████████████████████████| 12.6MB 2.3MB/s
Collecting pauvre (from nanoplotter>=0.36.0->NanoPlot)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/f0/70/b1a2c106128156d2f234964caee3f900733f81b67df51ffa62591e5bba46/pauvre-0.1.86.tar.gz
Collecting statsmodels>=0.8.0 (from nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/a5/75/758f980df4d971b909d2bc516d22494a2e871fe1f3968ff9798b52d20fb9/statsmodels-0.9.0-cp35-cp35m-manylinux1_x86_64.whl (7.3MB)
    100% |████████████████████████████████| 7.3MB 5.0MB/s
Collecting plotly>=2.5.1 (from nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/c4/0c/1b8241395302fd66b34a0fe0774ed83632afd14aa5c995b262fb7b3ac540/plotly-2.7.0.tar.gz (25.0MB)
    100% |████████████████████████████████| 25.0MB 1.4MB/s
Collecting cycler>=0.10 (from matplotlib->seaborn->NanoPlot)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->seaborn->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 20.5MB/s
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from matplotlib->seaborn->NanoPlot) (1.10.0)
Collecting kiwisolver>=1.0.1 (from matplotlib->seaborn->NanoPlot)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/7e/31/d6fedd4fb2c94755cd101191e581af30e1650ccce7a35bddb7930fed6574/kiwisolver-1.0.1-cp35-cp35m-manylinux1_x86_64.whl (949kB)
    100% |████████████████████████████████| 952kB 17.0MB/s
Collecting patsy (from statsmodels>=0.8.0->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/5d/eb/92c4b45ca47a2dd1339c958636e083b50ffadb5162a599a1cbbe92f89832/patsy-0.5.0-py2.py3-none-any.whl (232kB)
    100% |████████████████████████████████| 235kB 18.8MB/s
Collecting decorator>=4.0.6 (from plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting nbformat>=4.2 (from plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl (155kB)
    100% |████████████████████████████████| 163kB 30.6MB/s
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot) (2.9.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from kiwisolver>=1.0.1->matplotlib->seaborn->NanoPlot) (39.2.0)
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting jupyter-core (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 30.2MB/s
Collecting traitlets>=4.1 (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 81kB 20.1MB/s
Collecting ipython-genutils (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Building wheels for collected packages: NanoPlot, seaborn, nanoplotter, nanoget, nanomath, pauvre, plotly
  Running setup.py bdist_wheel for NanoPlot ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/5f/80/d8/b5d9754b9a5fc3acb07a6d8a7e573d2d461e878a887fcb2f77
  Running setup.py bdist_wheel for seaborn ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/26/0a/44/53ddd89769e62f7c6691976375b86c6492e7dd20a2d3970e32
  Running setup.py bdist_wheel for nanoplotter ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/13/9d/c5/4908d9ddd07f726aaecf4be9ddee75df8cd91deb0dad37bb20
  Running setup.py bdist_wheel for nanoget ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/e6/20/d9/f10d0dd5384dc5575a0e0f78d26381ac69e4290f4fb01a4c1e
  Running setup.py bdist_wheel for nanomath ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/46/4d/5b/30776e424f9958b68f907623c90b857c05c644a4a0b0b8ed62
  Running setup.py bdist_wheel for pauvre ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/6e/2b/00/0e4d27ead78a742a19bc4705a54bdcaae9cc456974b234bfad
  Running setup.py bdist_wheel for plotly ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/0c/3e/07/4848195c61f659184ca41d5a614845a018ab2d2f2a705b9998
Successfully built NanoPlot seaborn nanoplotter nanoget nanomath pauvre plotly
pauvre 0.1.86 has requirement numpy>=1.12.1, but you'll have numpy 1.11.0 which is incompatible.
pandas 0.23.0 has requirement python-dateutil>=2.5.0, but you'll have python-dateutil 2.4.2 which is incompatible.
Installing collected packages: biopython, pysam, pytz, pandas, scipy, cycler, pyparsing, kiwisolver, matplotlib, seaborn, pauvre, patsy, statsmodels, decorator, jsonschema, ipython-genutils, traitlets, jupyter-core, nbformat, plotly, nanoplotter, nanomath, nanoget, NanoPlot
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/BioSQL'
Consider using the `--user` option or check the permissions.

then just tried NanoPlot --help and got something that looks like it might be a Phython2.7 problem?

ubuntu@pore4:~$  NanoPlot --help
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

**Comment by wdecoster** [comment]
> Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/BioSQL'
> Consider using the --user option or check the permissions.

You don't have permission to install the updates in the python3 directory. Either you need to use `sudo` or add `--user` to the pip install command to install the modules in your home directory.

> then just tried NanoPlot --help and got something that looks like it might be a Phython2.7 problem?

You get this because the installation of NanoPlot in python 3 was not successful yet (see above) and you have a not-functional installation in your python2.7 version which will never work.
You can confirm this by using

`which NanoPlot`

which will show you in which directory the executable can be found

**Comment by Garryf** [comment]
Hi,  
I used the --user as sudo would not play ball which is  unusual on CLIMB. The end of the output suggested it had installed, however it had not

$ python3 -m  pip install --user  NanoPlot
Collecting NanoPlot
Collecting scipy (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/cd/32/5196b64476bd41d596a8aba43506e2403e019c90e1a3dfc21d51b83db5a6/scipy-1.1.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting seaborn (from NanoPlot)
Collecting pysam>0.10.0.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/09/a9/d74aa164efb28ce328cd4890b0182ccdf2e781c192910072717c965765c6/pysam-0.14.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting biopython (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/63/26/198e369dd95c50554ccc9ec76719be8e338d171fb30c7f14439653cd9153/biopython-1.71-cp35-cp35m-manylinux1_x86_64.whl
Collecting nanomath>=0.21.0 (from NanoPlot)
Collecting pandas>=0.22.0 (from NanoPlot)
  Using cached https://files.pythonhosted.org/packages/a5/c1/43966a4ce89d0c64111f46c6364ed57d6d87e6fab7d685dca06197a19cf7/pandas-0.23.0-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: python-dateutil in /usr/lib/python3/dist-packages (from NanoPlot) (2.4.2)
Collecting nanoplotter>=0.36.0 (from NanoPlot)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from NanoPlot) (1.11.0)
Collecting nanoget>=1.4.0 (from NanoPlot)
Collecting matplotlib (from seaborn->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/81/31/4e261379e0cd4e9bbacfc96b124ebac0706b44374bd1d34ef899796f741b/matplotlib-2.2.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting pytz>=2011k (from pandas>=0.22.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl
Collecting pauvre (from nanoplotter>=0.36.0->NanoPlot)
Collecting plotly>=2.5.1 (from nanoplotter>=0.36.0->NanoPlot)
Collecting statsmodels>=0.8.0 (from nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/a5/75/758f980df4d971b909d2bc516d22494a2e871fe1f3968ff9798b52d20fb9/statsmodels-0.9.0-cp35-cp35m-manylinux1_x86_64.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->seaborn->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/7e/31/d6fedd4fb2c94755cd101191e581af30e1650ccce7a35bddb7930fed6574/kiwisolver-1.0.1-cp35-cp35m-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.10 in /usr/lib/python3/dist-packages (from matplotlib->seaborn->NanoPlot) (1.10.0)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->seaborn->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->seaborn->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting decorator>=4.0.6 (from plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting nbformat>=4.2 (from plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot) (2.9.1)
Collecting patsy (from statsmodels>=0.8.0->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/5d/eb/92c4b45ca47a2dd1339c958636e083b50ffadb5162a599a1cbbe92f89832/patsy-0.5.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from kiwisolver>=1.0.1->matplotlib->seaborn->NanoPlot) (39.2.0)
Collecting ipython-genutils (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting traitlets>=4.1 (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting jupyter-core (from nbformat>=4.2->plotly>=2.5.1->nanoplotter>=0.36.0->NanoPlot)
  Using cached https://files.pythonhosted.org/packages/1d/44/065d2d7bae7bebc06f1dd70d23c36da8c50c0f08b4236716743d706762a8/jupyter_core-4.4.0-py2.py3-none-any.whl
pauvre 0.1.86 has requirement numpy>=1.12.1, but you'll have numpy 1.11.0 which is incompatible.
pandas 0.23.0 has requirement python-dateutil>=2.5.0, but you'll have python-dateutil 2.4.2 which is incompatible.
Installing collected packages: scipy, pytz, kiwisolver, pyparsing, cycler, matplotlib, pandas, seaborn, pysam, biopython, nanomath, pauvre, decorator, ipython-genutils, jsonschema, traitlets, jupyter-core, nbformat, plotly, patsy, statsmodels, nanoplotter, nanoget, NanoPlot
Successfully installed NanoPlot-1.13.0 biopython-1.71 cycler-0.10.0 decorator-4.3.0 ipython-genutils-0.2.0 jsonschema-2.6.0 jupyter-core-4.4.0 kiwisolver-1.0.1 matplotlib-2.2.2 nanoget-1.5.0 nanomath-0.21.0 nanoplotter-0.39.1 nbformat-4.4.0 pandas-0.23.0 patsy-0.5.0 pauvre-0.1.86 plotly-2.7.0 pyparsing-2.2.0 pysam-0.14.1 pytz-2018.4 scipy-1.1.0 seaborn-0.8.1 statsmodels-0.9.0 traitlets-4.3.2


**I then ran** 
ubuntu@pore4:~/mybin$ NanoPlot
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

**If I go to the~/.local/bin and enter NanoPlot with path I get a different error message to simply typing Nanoplot.  So I need to specify the path to this version in my local space. Howevere there are still errors.** 

ubuntu@pore4:~/mybin$ cd ~/.local/bin
ubuntu@pore4:~/.local/bin$ ls -lth
total 48K
-rwxrwxr-x 1 ubuntu ubuntu 220 Jun  5 12:19 NanoPlot
-rwxrwxr-x 1 ubuntu ubuntu 256 Jun  5 12:19 jupyter-trust
-rwxrwxr-x 1 ubuntu ubuntu 223 Jun  5 12:19 jupyter
-rwxrwxr-x 1 ubuntu ubuntu 223 Jun  5 12:19 jupyter-migrate
-rwxrwxr-x 1 ubuntu ubuntu 228 Jun  5 12:19 jupyter-troubleshoot
-rwxrwxr-x 1 ubuntu ubuntu 217 Jun  5 12:19 jsonschema
-rwxrwxr-x 1 ubuntu ubuntu 221 Jun  5 12:19 pauvre
-rwxrwxr-x 1 ubuntu ubuntu 232 May 23 22:03 easy_install
-rwxrwxr-x 1 ubuntu ubuntu 232 May 23 22:03 easy_install-2.7
-rwxrwxr-x 1 ubuntu ubuntu 214 May 23 21:51 pip2
-rwxrwxr-x 1 ubuntu ubuntu 214 May 23 21:51 pip2.7
-rwxrwxr-x 1 ubuntu ubuntu 214 May 23 21:51 pip
ubuntu@pore4:~/.local/bin$ ~/.local/bin/NanoPlot
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/home/ubuntu/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 25, in <module>
    import pandas as pd
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/home/ubuntu/.local/lib/python3.5/site-packages/pandas/compat/__init__.py", line 421, in <module>
    raise ImportError('dateutil 2.5.0 is the minimum required version')
ImportError: dateutil 2.5.0 is the minimum required version
ubuntu@pore4:~/.local/bin$ NanoPlot
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 7, in <module>
    from nanoplot.NanoPlot import main
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 18, in <module>
    from nanoget import get_input
  File "/usr/local/lib/python2.7/dist-packages/nanoget/__init__.py", line 1, in <module>
    from .nanoget import *
  File "/usr/local/lib/python2.7/dist-packages/nanoget/nanoget.py", line 29, in <module>
    import concurrent.futures as cfutures
ImportError: No module named concurrent.futures

**Comment by wdecoster** [comment]
While this is not the source of your problem I'd suggest removing the NanoPlot installation in python2.7.  I think the command below should do the trick:

`python2.7 -m pip uninstall NanoPlot`

To fix the python3 installation issue I believe the following should work, as you could have guessed from the error message:
`python3 -m pip install --user -U dateutil`

It appears your system has a few quite old python modules (setuptools, dateutil).

**Comment by Garryf** [comment]
Hi I tried this earlier and it did not apear to identify dateutil. Using the command you provided iget

ubuntu@pore4:~$ python3 -m pip install --user -U dateutil
Collecting dateutil
  Could not find a version that satisfies the requirement dateutil (from versions: )
No matching distribution found for dateutil

This may be something to do with the image I am using which is a porecamp2017 clone?

**Comment by Garryf** [comment]
I will try updateing everything and install again

**Comment by wdecoster** [comment]
I don't know anything about the porecamp2017 clone. It might be that that is the source of your trouble. Personally, I recommend installing the latest [anaconda](https://www.anaconda.com/download/#linux) distribution. Things will get a lot less painful then.

**Comment by Garryf** [comment]
Hi I sorted the pyhton-datutils problem, now I only seem to have to update numpy

pauvre 0.1.86 has requirement numpy>=1.12.1, but you'll have numpy 1.11.0 which is incompatible.

trouble is each time I try to update , it does not recognise a later version than 1.11.0

sudo pip3 install numpy, I also get same result with python3 -m pip install  numpy


The directory '--------/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.11.0)

Ill contact the system admin at CLIMB and see what they suggest.

thanks for your help

**Comment by Garryf** [comment]
Despite the remaining numpy error , NanoPlot seems to have installed. Ill see if ti runs:

ubuntu@pore4:~$ which NanoPlot
/home/ubuntu/.local/bin/NanoPlot
ubuntu@pore4:~$ NanoPlot
usage: NanoPlot [-h] [-v] [-t THREADS] [--verbose] [--store] [--raw]
                [-o OUTDIR] [-p PREFIX] [--maxlength N] [--minlength N]
                [--drop_outliers] [--downsample N] [--loglength]
                [--percentqual] [--alength] [--minqual N]
                [--readtype {1D,2D,1D2}] [--barcoded] [-c COLOR]
                [-f {eps,jpeg,jpg,pdf,pgf,png,ps,raw,rgba,svg,svgz,tif,tiff}]
                [--plots [{kde,hex,dot,pauvre} [{kde,hex,dot,pauvre} ...]]]
                [--listcolors] [--no-N50] [--N50] [--title TITLE]
                (--fastq file [file ...] | --fasta file [file ...] | --fastq_rich file [file ...] | --fastq_minimal file [file ...] | --summary file [file ...] | --bam file [file ...] | --cram file [file ...] | --pickle pickle)
NanoPlot: error: one of the arguments --fastq --fasta --fastq_rich --fastq_minimal --summary --bam --cram --pickle is required

**Comment by wdecoster** [comment]
This will probably be fine. Perhaps you will see issues if you use the `--plot pauvre` type (see [pauvre](https://github.com/conchoecia/pauvre), but I don't foresee issues for the "default" settings of `--plot`.

**Comment by Garryf** [comment]
finally got numpy to update with 

python3 -m pip install --user -U  numpy
Successfully installed numpy-1.14.3
thanks for your time with this. I think I may have learned something.

cheers

Garry

**Comment by wdecoster** [comment]
Great to hear! Hope this solves your issues. Thanks for the feedback!

**Comment by Garryf** [comment]
No Problem, thanks for your patience. I’m looking at my first plots now. Thumbs Up
