### ISSUE TITLE
Mb decimal issue

### ISSUE THREAD

**Issue by pgtb** [wdecoster/NanoPlot#66]
Hi Wouter !
Hope LC2018 is/was good !

Just a lil mistake about statistics on nanoplot online (or maybe on the command line version too ?).
About statistics before and after filtering, the table of "Number, percentage and megabases of reads above quality cutoffs". Megabases numbers are wrong. For example it is displayed 330.4Mb but it's 3.304 Gb for real.

thank you

best

**Comment by wdecoster** [comment]
Hi pgtb,

This has been reported before and fixed, but it's definitely possible that the Web application hasn't been updated yet. I'll tag @svennd here :)

Cheers, 
Wouter

**Comment by svennd** [comment]
I updated to latest version :)

**Comment by wdecoster** [comment]
Thanks! @pgtb issue should be fixed now. Can you confirm?

**Comment by pgtb** [comment]
Thanks !
I confirm, it works.

cheers

--
Christophe Boury
Assistant Ingénieur (Lab Geek)
Plateforme Genome Transcriptome de Bordeaux
INRA - UMR 1202 BIOGECO
69 route d'Arcachon
33612 Cestas - Pierroton
FRANCE

05.35.38.53.36
christophe.boury@inra.fr<mailto:christophe.boury@inra.fr>
pgtb@inra.fr<mailto:pgtb@inra.fr>

https://pgtb.cgfb.u-bordeaux.fr/
https://twitter.com/pgt_bordeaux

De : Wouter De Coster [mailto:notifications@github.com]
Envoyé : lundi 28 mai 2018 14:18
À : wdecoster/NanoPlot <NanoPlot@noreply.github.com>
Cc : pgtb <pgtb@inra.fr>; Mention <mention@noreply.github.com>
Objet : Re: [wdecoster/NanoPlot] Mb decimal issue (#66)


Thanks! @pgtb<https://github.com/pgtb> issue should be fixed now. Can you confirm?
