### ISSUE TITLE
NanoPlot crashed with --barcoded flag

### ISSUE THREAD

**Issue by kapsakcj** [wdecoster/NanoPlot#67]
Hi @wdecoster ,

Thanks for making NanoPlot, I think it's a great tool. I'm going to put a few figures generated w/ NanoPlot in to my MS thesis :)  I'll make sure to cite your publication.

Anyways....I ran NanoPlot without using the `--barcoded` flag first, ran perfectly, no issues. Today, I ran NanoPlot using the `--barcoded` flag and it crashed. I'm thinking it may have to do with the fact that I have a single Nanopore read that was identified as barcode 7, despite the fact that we only used the first 6 native barcodes during our sequencing run.

So I've got a lot of reads for BC's 1 through 6, however only one for barcode 7 and I think that caused the crash.

I've attached the log file.
[NanoPlot_20180530_1824.log](https://github.com/wdecoster/NanoPlot/files/2055893/NanoPlot_20180530_1824.log)

I removed the line from the sequencing_summary.txt that corresponded with that falsely identified BC07 read, re-ran NanoPlot, and no errors this time.

2nd log file (with BC07 read removed).
[NanoPlot_20180530_1848.log](https://github.com/wdecoster/NanoPlot/files/2055914/NanoPlot_20180530_1848.log)

Figured I'd post this issue as this bug may occur for others running their de-multiplexed nanopore reads through NanoPlot.

Sorry I can't offer a solution to fix the bug!

Curtis

**Comment by wdecoster** [comment]
Hi Curtis,

Good thing you already found a way to get the plots, by removing BC07. But this is indeed a bug which shouldn't happen - I'll look into it!

Thanks for reporting!

Wouter

**Comment by wdecoster** [comment]
Hi Curtis,

The bug here might be related to https://github.com/wdecoster/NanoPlot/issues/68
Could you test if updating the submodule nanoplotter to v0.39.1 (available through pip) solves things?

Cheers,
Wouter

**Comment by kapsakcj** [comment]
Sure thing.

I tried this out on a different computer than what I used above ^^ (actually on an Ubuntu 16.04 server, instead of the Windows Subsystem for Linux with Ubuntu 16.04 setup I have at home), but I used the same summary file "sequencing_summary.txt" which includes the one mis-identified BC07 read.

-installed via pip with `pip install NanoPlot` (Previously I installed via bioconda)
-made sure I had latest version with `pip install NanoPlot --upgrade`
-checked nanoplotter submodule version with `pip show --file nanoplotter`
output: `Version: 0.39.1`
-`NanoPlot --summary /home/curtis/nanoplot-results/june-4-nanoplot-test/sequencing_summary.txt --barcoded -o /home/curtis/nanoplot-results/june-4-nanoplot-test/`
-NanoPlot crashed in a similar manner to what I saw the first time I made it crash.

Here's the log file: 
[NanoPlot_20180604_1211.log](https://github.com/wdecoster/NanoPlot/files/2069110/NanoPlot_20180604_1211.log)
End of the log file:
```2018-06-04 12:13:28,501 Processing barcode07
2018-06-04 12:13:28,530 Nanoplotter: Valid color #4CB391.
2018-06-04 12:13:28,530 Nanoplotter: Creating length plots for Read length.
2018-06-04 12:13:28,530 Nanoplotter: Using 1 reads maximum of 557bp.
2018-06-04 12:13:29,834 Created length plots
2018-06-04 12:13:29,834 Nanoplotter: Creating Read lengths vs Average read quality plots using statistics from 1 reads.
2018-06-04 12:13:30,771 The number of observations must be larger than the number of variables.
Traceback (most recent call last):
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 84, in main
    make_plots(dfbarc, settings)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 382, in make_plots
    title=settings["title"])
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/nanoplotter/nanoplotter.py", line 206, in scatter
    size=10)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/seaborn/axisgrid.py", line 2271, in jointplot
    grid.plot_joint(kdeplot, **joint_kws)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1755, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 653, in kdeplot
    cbar, cbar_ax, cbar_kws, ax, **kwargs)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 383, in _bivariate_kdeplot
    xx, yy, z = _statsmodels_bivariate_kde(x, y, bw, gridsize, cut, clip)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 433, in _statsmodels_bivariate_kde
    kde = smnp.KDEMultivariate([x, y], "cc", bw)
  File "/home/curtis/miniconda3/lib/python3.6/site-packages/statsmodels/nonparametric/kernel_density.py", line 111, in __init__
    raise ValueError("The number of observations must be larger " \
ValueError: The number of observations must be larger than the number of variables.
```

So again, I removed the BC07 read from the "sequencing_summary.txt" file and re-ran NanoPlot on it. No errors or crashing this time.
[NanoPlot_20180604_1227.log](https://github.com/wdecoster/NanoPlot/files/2069119/NanoPlot_20180604_1227.log)

I hope this helps! Let me know if you want me to try something else.

Curtis

**Comment by wdecoster** [comment]
Hi Curtis,

Took me a bit longer than anticipated, but apparently, I should be writing my thesis ;-)
Since the issue did not originate from code in NanoPlot, but rather from 'upstream' modules seaborn and statsmodels I have prevented but not fixed the issue by ignoring barcoded datasets with < 5 reads.
I believe that makes sense, plots would be quite useless too and the issue is most likely a misclassification. For transparency, a warning is printed and logged.

This solution is now available on PyPI, NanoPlot v1.14.1.

Please let me know if this doesn't solve your issue.

Cheers,
Wouter

**Comment by kapsakcj** [comment]
Not a problem at all! I'm in the same boat as you - I should be working on my thesis.

I updated to v1.14.1, ran the same command as before using the same `sequencing_summary.txt` with the one BC07 read, and it ran with no issues. I also was able to see the warning message too 

`Found barcode barcode07 less than 5x, ignoring...`

Here's the log file if you're interested. 
[NanoPlot_20180614_0948.log](https://github.com/wdecoster/NanoPlot/files/2102619/NanoPlot_20180614_0948.log)

The fix worked like a charm! Thanks.

Curtis

**Comment by wdecoster** [comment]
Good to hear!

**Comment by husamia** [comment]
For clarification on the context of running the --barcoded option. What would be the input? I already have demultiplex and each barcode folder contains the 4k fastq chunck files. I also have merged the barcode files from each folder i.e. barcode01.fastq

**Comment by wdecoster** [comment]
Please ask separate questions in a new issue. The barcoded argument only applies when using a sequencing_summary file.

**Comment by sivankij** [comment]
Hi @wdecoster !
Thank you so much for your tool! 
I have a similar issue to the one @kapsakcj stated- when running NanoPlot with the --barcoded flag, the program crashes. 

Traceback (most recent call last):
  File "/cs/icore/sivankij/.local/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/cs/icore/sivankij/.local/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 77, in main
    settings["statsfile"] = [make_stats(datadf, settings, suffix="", tsv_stats=args.tsv_stats)]
  File "/cs/icore/sivankij/.local/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 128, in make_stats
    as_tsv=tsv_stats)
  File "/cs/icore/sivankij/.local/lib/python3.7/site-packages/nanomath/nanomath.py", line 176, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/cs/icore/sivankij/.local/lib/python3.7/site-packages/nanomath/nanomath.py", line 176, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/cs/icore/sivankij/.local/lib/python3.7/site-packages/nanomath/nanomath.py", line 37, in __init__
    self.n50 = get_N50(np.sort(df["lengths"]))
  File "/cs/icore/sivankij/.local/lib/python3.7/site-packages/nanomath/nanomath.py", line 116, in get_N50
    return readlengths[np.where(np.cumsum(readlengths) >= 0.5 * np.sum(readlengths))[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0
[NanoPlot_20201210_1627.log](https://github.com/wdecoster/NanoPlot/files/5673417/NanoPlot_20201210_1627.log)

The log file is attached. I would love your input on this! Removing the barcodes that were not used and had a small amount of reads (less than 5 fastq file per folder) also didn't help, and I got the same error. The log file is-
[NanoPlot_20201210_1632.log](https://github.com/wdecoster/NanoPlot/files/5673434/NanoPlot_20201210_1632.log)

Thank you very much!
Sivan

**Comment by wdecoster** [comment]
Do you mean it doesn't crash when you use the summary input without --barcoded?
Did you concatenate multiple summary files together?

**Comment by sivankij** [comment]
It doesn't crush without the --barcoded.
I didn't concatenate multiple summary files- this is a single file generated by guppy_basecaller with demultiplexing in the script.

**Comment by wdecoster** [comment]
Do you think you can share the summary file?

**Comment by sivankij** [comment]
sure, but it's too big even in .zip, so I put it here-
https://drive.google.com/file/d/1JouMbrh7Plv1PrNslMKRV6QDTxxbLu8D/view?usp=sharing

**Comment by wdecoster** [comment]
The last line of your summary is corrupted (incomplete).
NanoPlot works if you do `head -n -1 sequencing_summary.txt > sequencing_summary-without-last.txt` to remove the last line.

**Comment by sivankij** [comment]
It worked! you're the best, thank you!

**Comment by wdecoster** [comment]
This could mean that something went wrong while creating the summary file, and you are potentially missing reads.

**Comment by sivankij** [comment]
oh no. How would you suggest checking this? Do I expect a mismatch between the number of reads in the fastq files and the the summary file, or does this mean that the basecalling and demultiplexing process was interrupted and not all the data was analyzed?

**Comment by wdecoster** [comment]
The first one is easiest to check, but I'm thinking the second might be more likely to blame.

**Comment by sivankij** [comment]
It's quite strange. I feel like things don't add up. It seems like all the reads were processed, so why is the sequencing summary file incomplete?
<img width="1093" alt="Screen Shot 2020-12-15 at 15 50 15" src="https://user-images.githubusercontent.com/75795235/102224785-0f50ee00-3eef-11eb-879b-5db80585f431.png">
