### ISSUE TITLE
nanoplot installation

### ISSUE THREAD

**Issue by weihongqi** [wdecoster/NanoPlot#69]
I installed NanoPlot using pip and the installation went fine. But when I try to run it, I got the appended error. Could you please let me know how to overcome it? Many thanks in advance,
Kind regards,

Weihong

Errors:
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 9, in <module>
    load_entry_point('NanoPlot==1.8.1', 'console_scripts', 'NanoPlot')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 24, in <module>
    import nanoplotter
  File "/usr/local/lib/python2.7/dist-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter import *
  File "/usr/local/lib/python2.7/dist-packages/nanoplotter/nanoplotter.py", line 41, in <module>
    from pauvre.marginplot import margin_plot
  File "/usr/local/lib/python2.7/dist-packages/pauvre/marginplot.py", line 360
    file=stderr)
        ^
SyntaxError: invalid syntax

My computer environment:
Python 2.7.9

pip 9.0.1 from /usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg (python 2.7)

Linux fgcz-s-038 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.10 (jessie)
Release:	8.10
Codename:	jessie

**Comment by wdecoster** [comment]
As written in the README NanoPlot requires a python3 environment.

If installed on your system you can use:

`python3 -m pip install NanoPlot`

If you haven't installed python3 yet I would recommend [the anaconda distribution](https://www.anaconda.com/download/).

**Comment by weihongqi** [comment]
Thanks! Sorry that I overlooked this line. The installation went fine with python3-pip.

**Comment by wdecoster** [comment]
Good to hear, thanks for the feedback.
