### ISSUE TITLE
Feature request: limit input data by time since run start

### ISSUE THREAD

**Issue by homeveg** [wdecoster/NanoPlot#70]
Hi, 

I am currently analyzing the data, limiting data set to specified time span (in my case first 2 or 8 hours after run start). At the moment, I've just created a subset of reads based on the time stamp information from extended fastq file, generated by MinKnow (I guess, this is time when original Fast5 file got created) and than analyse resulting subset. 
It would be nice to have such feature implemented directly into NanoPlot - limit input dataset to specified time span.

Best,
Evgeniy

**Comment by wdecoster** [comment]
Hi Evgeniy,

Thank you for your suggestion. I am getting more and more reluctant to add new features, to avoid making NanoPlot very complex with tens of parameters and flags. Note that, if you would start from a sequencing_summary.txt generated by Albacore/Guppy your request would be as simple as using an awk filter on that summary file. I can however see some applications for your request. Nevertheless, do you think you would use this often?

Would it suffice to have an option like `--runtime-until 8` which removes all reads after 8 hours in the run, or would you also need a `--runtime-from 2` which removes all reads before 2 hours in the run?

I haven't decided yet if I want to implement this, but your answers to the questions above would be helpful. I might provide a stand-alone helper script to perform these "more customized" filtering steps without overloading NanoPlot.

Cheers,
Wouter

**Comment by homeveg** [comment]
Thank for answering!
I can understand it :) Same happening to my own scripts all the time...  
Nevertheless,  I think the  `--runtime-until` option will be at least as useful as `--downsample` option, but providing some additional information. 
For our pipeline we are normally using the MinKnow for real-time basecalling and therefore I don't have any sequencing_summary.txt. 
At the moment I need only`--runtime-until`  option but as well can see a potential in `--runtime-from` option. I can't say how often I will be using such option in the future, but at least for all our generated datasets (dozens) I would be happy to have it.

**Comment by wdecoster** [comment]
Sounds reasonable. I've put adding `--runtime-until` on my to-do list and hope to get it done by the end of this week.

**Comment by wdecoster** [comment]
Took me a bit longer than anticipated, but apparently, I should be writing my thesis ;-)

I added `--runtime_until` in NanoPlot v1.14.0 and just pushed that to PyPI.
Please give feedback!

Cheers,
Wouter

**Comment by homeveg** [comment]
Thanks! :+1:  
Cheers,
Evgeniy

P.s. Good luck with your thesis!
