### ISSUE TITLE
How to enable multi-threaded NanoPlot?

### ISSUE THREAD

**Issue by lfaller** [wdecoster/NanoPlot#72]
Hi all,

I would like to run NanoPlot in multi-threaded mode but the `-t` option does not seem to work. It always uses only one thread.

Do I need any particular packages installed for the multi-threading to kick in?

Thanks for any suggestion!

~Lina

```
$> NanoPlot --version
NanoPlot 1.14.1

$> NanoPlot --fastq data.fastq.gz --loglength --outdir nanoplot_out -t 40
```

**Comment by wdecoster** [comment]
Hi Lina,

The only part that is multithreaded is the extraction of information from the input files. If you would have multiple fastq files those would get processed in parallel. Similarly, extracting information from a bam file is done per chromosome in parallel. Plotting itself unfortunately is only using one thread.

Cheers, 
Wouter

**Comment by lfaller** [comment]
Ah, that makes sense. I have one large fastq input file that contains all the of the nanopore reads.

Thanks for clarifying!
~Lina
