### ISSUE TITLE
Nanoplot crashed while using using with an error '`bins` must be positive, when an integer'

### ISSUE THREAD

**Issue by huzaifahassan** [wdecoster/NanoPlot#77]
I used Nanoplot for a set of filtered reads(read lengths between 100 and 110) and it crashed with an error 'ValueError: `bins` must be positive, when an integer'

Log has been attached for reference.

[NanoPlot_20180719_2225.log](https://github.com/wdecoster/NanoPlot/files/2212253/NanoPlot_20180719_2225.log)

**Comment by wdecoster** [comment]
Hello,

Thanks for reporting this. I have identified the issue. Your read lengths are rather unexpected for this script, therefore it crashed.

This should be solved if you upgrade NanoPlot to 1.14.3 which I just made available on PyPI. Please let me know how it goes.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Closing due to lack of response...
