### ISSUE TITLE
Feature request: plot sequencing speed over time

### ISSUE THREAD

**Issue by jts** [wdecoster/NanoPlot#78]
Hi,

We find NanoPlot to be very useful. Would you be able to add a plot that shows the average sequencing speed over time?

Thanks,
Jared

**Comment by wdecoster** [comment]
I guess that would be possible, do you mean nucleotides per second (per molecule), or molecules/strands per minute? What do you have in mind exactly?

**Comment by jts** [comment]
Nucleotides per second, per molecule. We're found that our runs slow down
near the end and we'd like to quantify this. The plot I have in mind is
something like the average sequencing speed for each hour of the run.

**Comment by wdecoster** [comment]
Hi Jared,

Great suggestion, and looks like you are right about sequencing slowing down. I have added violin plots with sequencing speed per 3 hours of sequencing to NanoPlot v1.15.0, which I just pushed to PyPI.

FYI, it looks like this:

![timesequencingspeed_violinplot](https://user-images.githubusercontent.com/11660522/43018994-b6336336-8c5b-11e8-93ae-bf9509a9a5c1.png)

Let me know if that's not exactly what you are looking for - although I'm out of office from tomorrow and will take other feature requests in August.

Cheers,
Wouter

**Comment by jts** [comment]
That looks great, thank you for adding it so quickly!

**Comment by larsgtoicr** [comment]
Hi Wouter,

I think the Sjödin acknowledgement broke thing when trying to install it. If I do it manually and edit the README.md it seems to work.
``Collecting NanoPlot
  Using cached https://files.pythonhosted.org/packages/47/23/b6abdce250e0a26e3aec2bc5aa33972162fe9de312bdebdc4c86fff5dc71/NanoPlot-1.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/oicr/tmp/pip-build-l1x5f810/NanoPlot/setup.py", line 14, in <module>
        long_description=open(path.join(here, "README.md")).read(),
      File "/.mounts/labs/ont/software/NanoPlot/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6803: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/oicr/tmp/pip-build-l1x5f810/NanoPlot/``

**Comment by wdecoster** [comment]
Thanks for reporting this. It is true that I recently moved the acknowledgments in the README itself, rather than a separate file. I however cannot replicate this issue here. Could you check 
-echo $LANG 
(returns en_US.UTF-8 on my systems)
-the versions of pip and see if updating solves something?

This might depend on your locale (see also https://stackoverflow.com/questions/26473681/pip-install-numpy-throws-an-error-ascii-codec-cant-decode-byte-0xe2, for example).

I guess I could just adapt the README, but I don't really like misspelling someone's name.

Please let me know what you find.

Cheers,
Wouter

**Comment by larsgtoicr** [comment]
I don't have anything in $LANG so that might be the cause. Will try it when I get back.

We have it up and running now.

**Comment by wdecoster** [comment]
FYI: this installation issue should be solved with NanoPlot v1.17.1

**Comment by baracus37** [comment]
Hi,

I would be interested in the sequencing speeds as well, but I can not find any way to implement this into my report file. I am using v 1.20.1 and I am generating the Plots from the summary files. 
Has this feature been removed or is it just that summary files from GridION do not contain the necessary information about sequencing speeds?

Cheers

**Comment by wdecoster** [comment]
The feature has not been removed, and I'm not aware of any changes to the summary files. The plot is named "TimeSequencingSpeed_ViolinPlot.png". This plot requires the "duration" column to be present in the summary file. Is that column in your file? Which command have you been using?

I just tried it on some PromethION data, and "it works on my system".

**Comment by baracus37** [comment]
Hi,

I just updated to 1.20.1 and ran into the same issue as [#88](https://github.com/wdecoster/NanoPlot/issues/88).
Updating seaborn resolved it! Thanks!

**Comment by wdecoster** [comment]
And now you also get the sequencing speed over time plot?

**Comment by baracus37** [comment]
yes, indeed. I forgot to mention that, sorry.

**Comment by wdecoster** [comment]
Thanks for confirming, let me know if you come across other issues or have feature requests!

**Comment by turbo4xl** [comment]
I am using nanoplot online  with the summary file. the summary file appears to be a few line files. starting with instrument and ending with fastq_files_in_fall_back=0. is that the correct file?

**Comment by turbo4xl** [comment]
I think i found the file how ever it is 1.7g quiet large how to reduce the size from your experience?

**Comment by wdecoster** [comment]
I don't think this belongs in this issue. Your question is unrelated to the original question. I would appreciate it if you would make a new thread.
