### ISSUE TITLE
The `size` paramter has been renamed to `height`; please update your code.

### ISSUE THREAD

**Issue by dominik-handler** [wdecoster/NanoPlot#79]
Hi,

when I am running NanoPlot on summary files I get the following error:

> /Software/anaconda3/lib/python3.6/site-packages/seaborn/axisgrid.py:2262: UserWarning:
> The `size` paramter has been renamed to `height`; please update your code.

I am using Python 3.5 and install NanoPlot via Miniconda. 
Do you know this problem?

All the best,
Dominik

**Comment by wdecoster** [comment]
That looks like a harmless warning from the seaborn module, not really an error. Can you confirm you got all output as expected and the log file is complete?

I'll update the code as suggested by the warning but I will first have to test if everything is still correct.

**Comment by wdecoster** [comment]
I have changed the code, updating NanoPlot to v1.15.1 should remove the warning.

**Comment by dominik-handler** [comment]
Sounds perfect.
You were correct, NanoPlot was running without any problem except the warning.

Thank you and all the best,
Dominik

**Comment by Tammy2014** [comment]
Same here with my project. I see the plots I was expecting despite the error  and warning messages. 
Thank you  both . 
Tamrat
