### ISSUE TITLE
output file prefix

### ISSUE THREAD

**Issue by devindrown** [wdecoster/NanoPlot#8]
Perhaps this isn't a bug...

I noticed that the txt summary file written in the output directory as Nanostats.txt doesn't have the user defined prefix. Prefix on the graphs is all correct.

**Comment by wdecoster** [comment]
Thanks for reporting this. That's indeed not as you would expect, so fair enough to consider this a bug. It should be fixed in 0.14.3, which I just made available

Cheers!
