### ISSUE TITLE
Support NanoPlot in MultiQC?

### ISSUE THREAD

**Issue by PertuyF** [wdecoster/NanoPlot#84]
Hi @wdecoster !

Nice job with NanoPlot a the whole suite!
It would be very nice to support `NanoPlot` in [`MultiQC`](https://github.com/ewels/MultiQC), do you think it's possible?

**Comment by wdecoster** [comment]
Hi PertuyF,

Thanks for the suggestion! I'm not really familiar with the internals of MultiQC, and as such don't know what it would take to add NanoPlot. Based on scrolling through the [manual](http://multiqc.info/docs/#writing-new-modules) it doesn't take witchcraft.

However, this cannot really be a priority for me as I'm writing my thesis.
If someone else would work on this I'd happily support and help out where possible.

Cheers,
Wouter

**Comment by PertuyF** [comment]
I'll see what I can do, but violin plots might be a problem as they're not implemented in `MultiQC`.
Anyway, could you provide me a sample file of `NanoPlot` outpout? all files that contains data used for the plotting, I would need this to code the parsing part (and I can't run NanoPlot on data by myself right now).

Best,
Fabien

**Comment by wdecoster** [comment]
NanoPlot creates a stats report and plots, both separate image files (in one of the common image files jpg, png, svg, etc) and an HTML file containing the stats and plots.

Attached to this post you can find an example output (.tar.gz), where a sequencing_summary.txt from albacore was used as input to NanoPlot.

[nanoplot-summary-example.tar.gz](https://github.com/wdecoster/NanoPlot/files/2333022/nanoplot-summary-example.tar.gz)

Did I understand correctly that you pass all data for plotting to MultiQC, which will recreate the plots? Doesn't sound very efficient in this case.
