### ISSUE TITLE
Change bin size of the histogram 

### ISSUE THREAD

**Issue by scogi** [wdecoster/NanoPlot#86]
Hi @wdecoster 

fantastic tool collection, thank you. Is there any option to modify the bin size of the read length histogram? I have several reads in the 0-30 kb size and then a few much longer. The histogram is automatically plotted in 20 kb steps, virtually grouping all my reads in one single bar. I could not find a respective option in the documentation. Thank you!

Best regards
Stefan

**Comment by wdecoster** [comment]
Hi Stefan,

Thanks for reaching out. What you see is actually a bug, introduced when fixing an earlier issue (https://github.com/wdecoster/nanoplotter/commit/5cd9274d82f60cf837f539309ff4bfc65a635a05).
As a consequence of this, the default number of bins was always 5, which is of course ridiculous.

I fixed this and set a -I believe- sensible default. I'm a bit reluctant to expose the option to set the size of bins to users, to avoid adding too many parameters and options to NanoPlot. It's already getting messy enough as it is :)

Updating NanoPlot to v1.17.2 should contain the fix - I just pushed this to PyPI.

Note that it might also help to set a --maxlength cut off to remove the handful longest reads which screw up your plot anyway, and that often the log-transformed plots can be quite informative.

Please let me know if that helps.

Wouter

**Comment by scogi** [comment]
Hi Wouter

Works now like a charm! Thank you for the quick reaction. 
A very minor suggestion: the contrast of the bars in the figure and the overall resolution are rather low. The bars are quite hard to see when e.g. added to a ppt or so... maybe you could consider to increase the contrast and/or resolution of the figures in one of the next versions? Just something like here below or so. This would just allow using the figures without further manipulation (e.g for progress reports assembled in the last minute...)
 ![histogramreadlength](https://user-images.githubusercontent.com/24541473/44645678-bd5fc380-a9d8-11e8-9889-2f31209a8f1d.png)
to 
![histogramreadlength_highcontrast](https://user-images.githubusercontent.com/24541473/44645692-cf416680-a9d8-11e8-9e90-2bf4597c22eb.png)

Great tool, thank you
Stefan

**Comment by scogi** [comment]
Done

**Comment by wdecoster** [comment]
Very well, I'll close this one then.

Cheers,
Wouter
