### ISSUE TITLE
Improve contrast and resolution of report figures

### ISSUE THREAD

**Issue by scogi** [wdecoster/NanoPlot#87]
Hi Wouter,
the contrast of the bars in the figure and the overall resolution are rather low. The bars are quite hard to see when e.g. added to a ppt or so... maybe you could consider to increase the contrast and/or resolution of the figures in one of the next versions? Just something like here below or so. This would  allow using the figures without further manipulation (e.g for progress reports assembled in the last minute...)

![histogramreadlength](https://user-images.githubusercontent.com/24541473/44646437-3f50ec00-a9db-11e8-8044-06d57c60214b.png)

to 

![histogramreadlength_highcontrast](https://user-images.githubusercontent.com/24541473/44646440-424bdc80-a9db-11e8-891b-f52f91305db5.png)

if file size of the report is a concern, also a "--highres" option allowing switching to 300-600 dpi figures (manuscript-ready...) would be probably useful.

Great tool, thank you
Stefan

**Comment by wdecoster** [comment]
As a partial solution, I have added dpi control to NanoPlot (and NanoComp). The next release, which I'll probably push in a couple of hours, will have a `--dpi` argument (default = 100). Putting this to a higher value will obviously also increase the size of the images, and add a bit of runtime.

I'll also try to increase the contrast, which would be a big improvement. It seems to be a bit harder than I anticipated, but I'll dive deeper.

**Comment by scogi** [comment]
Hi Wouter

thank you for coming back to this. I am looking forward to it.

greetings
stefan

**Comment by wdecoster** [comment]
I've made some changes which will make the bars easier to see, they are available from NanoPlot v1.18.2 which is available on PyPI now.

Does that help?

**Comment by scogi** [comment]
Thanks, this is now much better and helps a lot!

**Comment by wdecoster** [comment]
Thanks again for the suggestion, let me know if you think of anything else!
