### ISSUE TITLE
N50 score wrong in NanoStats.txt

### ISSUE THREAD

**Issue by dominik-handler** [wdecoster/NanoPlot#9]
Hi,

I was running NanoPlot with the following options:
`
NanoPlot.img -t 10 --readtype 1D -o NanoPlot-Albacore --format png --fastq_rich=ALBACORE_2.0.1/basecalled-fastq/*/workspace/pass/*
`
I obtained these stats:

```

Number of reads:	61271
Total bases:	1641588524
Median read length:	13422.0
Mean read length:	26792.26
Readlength N50:	1443

Top 5 read lengths and their average basecall quality score:
Length: 339578bp	Q: 11.51
Length: 308174bp	Q: 11.3
Length: 297580bp	Q: 10.79
Length: 296918bp	Q: 11.91
Length: 293418bp	Q: 10.49

Top 5 average basecall quality scores and their read lengths:
Length: 190bp	Q: 17.57
Length: 604bp	Q: 16.55
Length: 919bp	Q: 16.52
Length: 400bp	Q: 16.44
Length: 341bp	Q: 16.34

Number of reads and fraction above quality cutoffs:
Q5:	61271	100.0%
Q10:	52197	85.19%
Q15:	321	0.52%
Q20:	0	0.0%

Data produced using 491 active channels.

Data was produced in run(s) with ID:
5777d07d52f71258b430fef90b98553ccc7bb940
969a2343e7856434ee3eb08375733500fad575c6
aed05196e39bbd909d925fdf8dc07e0144e331ff
bc29db598011f5099c924fb973089d23587c85cc
```

The N50 is pretty low and wrong here. In the  HistogramReadlength it is correct:
![image](https://user-images.githubusercontent.com/12491961/30152865-dea1af76-93b4-11e7-8481-82e3a5d1b194.png)

**Comment by wdecoster** [comment]
Hi dominik-handler,

Thanks for reporting this and my apologies for the late reply, I'm just back from my holidays.
I think I identified what's wrong and made a change in nanomath. If you could upgrade nanomath (to 0.12.6) I think this should be resolved (`pip install nanomath --upgrade`). Can you confirm?

I just relearned today how to type and read after not being close to a keyboard for a lovely 3 weeks, so I might have messed up in my fix. But it looks right.

Cheers,
Wouter
