### ISSUE TITLE
TimeLengthViolinPlot with log y-axis

### ISSUE THREAD

**Issue by tolot27** [wdecoster/NanoPlot#92]
The TimeLengthViolinPlot (Read length vs interval) should have the y-axis log-transformed like it in the "Comparing log length" plot of nanocomp.

**Comment by wdecoster** [comment]
I agree that this would be useful. I do not agree that "it should" be like that, though. I welcome your suggestions (and contributions) and will try to make time for this.

**Comment by tolot27** [comment]
You are right. My wording "should" be "it would be great to have...". Thanks for your time. I know, you're writing your thesis, so do I.

**Comment by wdecoster** [comment]
NanoPlot already had a `--loglength` option, but this was not active in the TimeLengthViolinPlot. I have now changed that, so using `--loglength` should give you what you are looking for.

This change is available from NanoPlot v1.18.0, which I just pushed to PyPI.

**Comment by wdecoster** [comment]
NanoPlot already had a `--loglength` option, but this was not active in the TimeLengthViolinPlot. I have now changed that, so using `--loglength` should give you what you are looking for.

This change is available from NanoPlot v1.18.0, which I just pushed to PyPI.
