### ISSUE TITLE
same scaling for barcoded sub-plots

### ISSUE THREAD

**Issue by tolot27** [wdecoster/NanoPlot#93]
The various "sub-plots" generated with `--barcode` should have the same axis scaling and max value.
Typically, I generate combined pdf sheets (3x2 or 2x4, etc.) for each plot type to compare the demultiplexed datasets visually. As long as the axis does not have the same range/scaling, a quick comparsion cannot be made.

**Comment by wdecoster** [comment]
Have you looked at NanoComp for this?

**Comment by tolot27** [comment]
NanoComp has also a `--barcoded` parameter. That's great. :-) Just the KDE or pauvre plot is missing.

**Comment by wdecoster** [comment]
You mean a bivariate plot of read length vs quality?

The way I currently implemented NanoPlot makes it quite hard to fix the axis, but I'll think about it.

**Comment by tolot27** [comment]
NanoComp is great and sufficient to compare the barcoded samples, but I realy like the the bivariate plots because it shows to dimension in one diagram.

**Comment by wdecoster** [comment]
Yeah, I'm not sure how to incorporate those in NanoComp though. Stacked bivariate plots are going to be messy. Putting them side by side can be done theoretically, with the same scale for the axis, but I can't say I'm looking forward to writing that ;)
