### ISSUE TITLE
Yield_By_Length.png is created if pdf output is requested

### ISSUE THREAD

**Issue by tolot27** [wdecoster/NanoPlot#94]
If `-f pdf` is supplied to NanoPlot, one non-pdf file `..._Yield_By_Length.png` is created instead of the pdf version.

**Comment by wdecoster** [comment]
Oh, remarkable. I'll fix it! Thanks!

**Comment by wdecoster** [comment]
This is fixed in the nanoplotter submodule v0.44.2, which I just pushed to PyPI. Next time I update NanoPlot this module will by default get updated as well.
