### ISSUE TITLE
NanoPlot Crashed

### ISSUE THREAD

**Issue by cpang429** [wdecoster/NanoPlot#97]
Hello, I'm using NanoPlot 1.17.3 to visualize FASTQ files, but received the following message: "AttributeError: module 'nanoplotter' has no attribute 'plot_settings'. Please find attached a screenshot of the parameters I used. Please advise, thank you.

![screen shot 2018-09-24 at 4 47 03 pm](https://user-images.githubusercontent.com/28854830/45943608-93baac00-c019-11e8-9476-05836f05aa04.png)

**Comment by wdecoster** [comment]
This error will probably be solved by updating the nanoplotter submodule, but please give me the answer to these questions:

- How did you install NanoPlot?
- Can you please show me the output of `python -c "import nanoplotter ; print(nanoplotter.__version__)"`

And then try `pip install nanoplotter -U` (if you are using pip) or `conda upgrade nanoplotter` (if you are using conda).

**Comment by cpang429** [comment]
Hello wdecoster,

I installed NanoPlot with Miniconda.

The following is the output I receive:
![screen shot 2018-09-24 at 8 59 49 pm](https://user-images.githubusercontent.com/28854830/45953503-d93ca080-c03c-11e8-9018-f48c4d9e13d2.png)

I also tried conda upgrade nanoplotter:
![screen shot 2018-09-24 at 9 01 16 pm](https://user-images.githubusercontent.com/28854830/45953564-08eba880-c03d-11e8-8a7c-498d6532e475.png)

Upon running NanoPlot again, I recieve the following message:
![screen shot 2018-09-24 at 9 02 37 pm](https://user-images.githubusercontent.com/28854830/45953614-36d0ed00-c03d-11e8-8862-f189bc12171b.png)

**Comment by wdecoster** [comment]
Could you then also update NanoPlot itself in the same way? Looks like the submodules got out of sync somehow.

**Comment by TiHsCh** [comment]
Hello wdecoster,
I've encountered same problem. I ran NanoPlot as
`NanoPlot -t 2 -p Nanoplot --fastq directRNAseq20180928_trimmed.fastq  --plots hex dot --N50`
and then got the error message:
![image](https://user-images.githubusercontent.com/25469337/46266963-fa4a4780-c58e-11e8-9594-27366e607e93.png)

I installed NanoPlot through `conda install NanoPlot`.
I also ran `conda update NanoPlot` and `conda upgrade nanoplotter`.
Running `python -c "import nanoplotter ; print(nanoplotter.__version__)"` showed `0.39.1`

However I still got the same error message when I re-ran the script `NanoPlot -t 2 -p Nanoplot --fastq directRNAseq20180928_trimmed.fastq  --plots hex dot --N50`.
Any advise or guidance would be greatly appreciated!



``

**Comment by TiHsCh** [comment]
Hello wdecoster,
I've encountered same problem. I ran NanoPlot as
`NanoPlot -t 2 -p Nanoplot --fastq directRNAseq20180928_trimmed.fastq  --plots hex dot --N50`
and then got the error message:
![image](https://user-images.githubusercontent.com/25469337/46266963-fa4a4780-c58e-11e8-9594-27366e607e93.png)

I installed NanoPlot through `conda install NanoPlot`.
I also ran `conda update NanoPlot` and `conda upgrade nanoplotter`.
Running `python -c "import nanoplotter ; print(nanoplotter.__version__)"` showed `0.39.1`

However I still got the same error message when I re-ran the script `NanoPlot -t 2 -p Nanoplot --fastq directRNAseq20180928_trimmed.fastq  --plots hex dot --N50`.
Any advise or guidance would be greatly appreciated!

Ting

**Comment by TiHsCh** [comment]
Hi wdecoster,
I removed previously installed NanoPlot and nanoplotter by `conda remove`, reinstalled them using `conda install` but specified the latest versions. Then ran `conda upgrade nanoplotter` and `conda update NanoPlot`. And now it works perfectly. Thank you so much!
Ting

**Comment by wdecoster** [comment]
Thanks for the feedback! I'm going to close this for now, feel free to let me know if you encounter issues.
